### ISSUE TITLE
Docker container is out-of-date

### ISSUE THREAD

**Issue by ywLBhGk2noZLbY7** [nosmokingbandit/watcher#10]
Please create a docker image on docker hub that will automatically rebuild with commits to this git project.

Currently, [the docker container](https://hub.docker.com/r/williambroown/watcherdocker/) linked to in the readme is seven days out of date.

This should be very easy to do and the steps are documented [here](https://docs.docker.com/docker-hub/builds/).

**Comment by CHBMB** [comment]
The docker container isn't maintained by nosmokingbandit as it states in the readme

**Comment by ywLBhGk2noZLbY7** [comment]
I realize this, my understanding is that for the docker hub's autobuild feature to work, it needs a callback from github that only the project manager can configure.

This is more of a request for @nosmokingbandit to maintain his own docker image, so that the benefits that docker hub provides developers are used to their full extent.

**Comment by CHBMB** [comment]
Yeah, I'm currently working on a docker image based on Alpine.  Small size and shares the same base image as the rest of the containers we have, we update all ours each week, so I'd be keen to see nosmokingbandit to add support for moving the database like in your other issue.  Anyways if you want to check out some of our other docker images, they're here.  [linuxserver.io](http://tools.linuxserver.io/dockers)

**Comment by ywLBhGk2noZLbY7** [comment]
Looking forward to that, I'll migrate quickly as I'm currently using your images for nzbget, sonarr, unifi, rutorrent, plexpy, and until the announcement with Plex yesterday, Plex.

Thank you for your work! :)

**Comment by CHBMB** [comment]
Cool.  Once the sqlite location issue is resolved one way or another I'll see if @nosmokingbandit wants to mention our container in the wiki. ;)

**Comment by WilliamJBrown** [comment]
So i have never made a container before, i just threw this together baseing it off another container some made nzbhydra with. Using the same layout. Now I note it's not auto updating (will remove that on the readme's) but I did think the container built using the latest pull off of git when it creates the container. Maybe it stores the files from the git pull at the time the docker container is built i am not sure. 

If someone has better methods of building containers please take over as i hardly know what i am doing :)

**Comment by nosmokingbandit** [comment]
I'm closing this. I don't have the time to dedicate to figuring out Docker. If someone needs specific info they can contact me directly and I'll offer little knowledge I have.
