### ISSUE TITLE
Option to disable title match scoring.

### ISSUE THREAD

**Issue by imba3r** [nosmokingbandit/watcher#102]
Sometimes releases in a foreign language have the original title, sometimes they don't. Since the search happens using the IMDB id the releases with the foreign (release-)titles are found nevertheless.

This leads to results such as:

- Findet.Dorie.German....
- Finding.Dory.German....
- Findet.Dorie.German....

The scoring would prefer (or even remove) the releases with the original title. An option to disable this would be nice.

**Comment by imba3r** [comment]
I didn't quite finish it yet, but I will send you a pull request tomorrow.

**Comment by nosmokingbandit** [comment]
I have pretty strict title matching since it does help cut down on a lot of false-positives.

I can implement this switch pretty quickly if aren't familiar with python.

**Comment by imba3r** [comment]
Is something wrong with the way I did it in PR #104?

**Comment by nosmokingbandit** [comment]
No, I just commented here before I saw that. I try to go through my emails in order, so sometimes I miss things that happened after other things.

**Comment by nosmokingbandit** [comment]
Pulled and closed. :)
