### ISSUE TITLE
Option to prefer smaller size

### ISSUE THREAD

**Issue by brcknr** [nosmokingbandit/watcher#103]
Hello, 

a option to prefer smaller file sizes about big file sizes would be nice. I always download 1080p releases. Sometimes these are very big about to 20GB (i set Watcher to allow such big size). What i want is: Download the next best release which Watcher is founding, but when there is a file with smaller size, download this one and replace the big one.

**Comment by nosmokingbandit** [comment]
Added in commit https://github.com/nosmokingbandit/watcher/commit/73e2ed01548d32db97b1868482c1cc1d653cfb63

In Settings > Quality you can choose to prefer smaller file sizes for releases that have identical scores.
