### ISSUE TITLE
Can't update 

### ISSUE THREAD

**Issue by rickytin** [nosmokingbandit/watcher#104]
404 Page Not Found

**Comment by WilliamJBrown** [comment]
Just adding that also can't update. Don't see any meaningful logs apart from I am on build  a5e888d

Anything you need please ask.

**Comment by soundjester** [comment]
Same.

**Comment by Elfman72** [comment]
Same

**Comment by vertigo235** [comment]
ditto, i restored and old docker snapshot and was able to update from that one.

**Comment by nosmokingbandit** [comment]
I made a dumb error in the javascript that actually starts the update process.

Commit https://github.com/nosmokingbandit/watcher/commit/7cb7e8a1efe0178689cb0866af7761fc510e8eb1 fixes it.

However, you may need to update manually to https://github.com/nosmokingbandit/watcher/commit/7cb7e8a1efe0178689cb0866af7761fc510e8eb1.

First, try starting the update, then change the url from '/update_now' to '/update' and see if that goes through.

If not, try updating from the settings page (manually check for an update then click on that notification).

If that all fails, you may need to manually git pull.

**Comment by Elfman72** [comment]
Unfortunately, neither of those worked for me (Docker on Synology).  Will try a manual refresh of the Docker image.

@WilliamJBrown Would love it if you could get your docker package to auto pull the latest git on restart of the container.

**Comment by vertigo235** [comment]
In would rather it not

**Comment by calebcall** [comment]
Had this same issue, only thing I could get to work was to manually git pull.
