### ISSUE TITLE
Sync IMDB

### ISSUE THREAD

**Issue by rickytin** [nosmokingbandit/watcher#105]
I add my link of export list from IMDB, I did restart Watcher but sill no movie added.

**Comment by nosmokingbandit** [comment]
It syncs 5 minutes after starting/restarting the server, then every 6 hours afterward.

Email your log to

watchernzb@gmail.com and I'll take a look at it.

**Comment by alazare619** [comment]
@nosmokingbandit  can you give and example of a imdb watchlist url that it supports does it need to be in rss format or what this was plagueing me too

**Comment by alazare619** [comment]
http://rss.imdb.com/user/ur71084611/watchlist is one i put together to try.

**Comment by alazare619** [comment]
This is working as of the update that fixed the no nzb indexer results.

**Comment by rickytin** [comment]
Still not working for me.

**Comment by nosmokingbandit** [comment]
I'm going to need an rss link or your logs.

watchernzb@gmail.com

**Comment by rickytin** [comment]
I send the logs to your email,
Thanks for the help.

**Comment by nosmokingbandit** [comment]
I commented on the other issue. Please open only one issue for each problem.
