### ISSUE TITLE
Watcher.sqlite not stored in /config for the docker image

### ISSUE THREAD

**Issue by ywLBhGk2noZLbY7** [nosmokingbandit/watcher#11]
Resetting the docker container (`docker stop watcher && docker rm watcher && docker create --name watcher -v ${blah}:/config`) does not recreate the container properly. This is because the `watcher.sqlite` file which stores the movies requested & their statuses is located under `/opt/watcher/app/watcher.sqlite`.

`watcher.sqlite` (And any other files required for statefulness) should be placed under the `/config` directory.

Adding an option to the `config.cfg` file for the location of the `watcher.sqlite` file could be a quick-and-easy temporary workaround, until a proper solution is found.

**Comment by ywLBhGk2noZLbY7** [comment]
I just learnt that apparently `/opt/watcher/app/static/images/posters` is also required for the statefulness of the application.

Currently this is what my docker script looks like:

`docker create --name=watcher -v ${BASE}/config:/config -v ${BASE}/log:/log -v ${MULTIMEDIA}/Movies:/movies -v ${DOWNLOADS}/Movies:/${NZBGETDownloadDir}/Movies -v ${BASE}/posters:/opt/watcher/app/static/images/posters -v ${BASE}/watcher.sqlite:/opt/watcher/app/watcher.sqlite williambroown/watcherdocker`

As you can see, this is very hacky and is really ingesting itself into the inner-workings of the application.

**Comment by CHBMB** [comment]
I've also found this.

**Comment by nosmokingbandit** [comment]
I have no plans to officially support a docker image right now. Maybe in the future, but until then you are on your own.

**Comment by sparklyballs** [comment]
Hi, i'm also a member of the group @CHBMB is in, and regarding the database and images store being in the application folder tree, it's probably not a good idea in general, git updates and the like can present permissions issues for one thing.

Also linuxserver.io would support the docker image as we do with all of our containers, anything docker specific we handle support for and refer up for anything application specific.
