### ISSUE TITLE
Problem with searching and "Year"

### ISSUE THREAD

**Issue by Flippage** [nosmokingbandit/watcher#110]
Hey,

So when I search for some movies, I get no results unless I add the year after the title.

Example: A search for the movie "Rings" doesn't actually show the movie "Rings" unless I type "Rings 2017"
Example 2: Search for "Assassins Creed" and you won't get the new movie. You need to search for "Assassins Creed 2016"

As an additional note: Can the year be separate from the movie title? Or at least in brackets?

Like, "Assassins Creed (2016)" ?

Thanks :)

**Comment by JoeStratton** [comment]
Searching with the year is pretty standard. There are multiple movies that have the word "ring" in it, how would watcher know which one you want without telling it the year?

Also, The naming convention can be modified under settings->post-processing

**Comment by nosmokingbandit** [comment]
OMDB's api can be a little cantankerous some times and will only show results if the year is included. I'm looking at other options, but it is hard to find a free service that provides a good array of information.
