### ISSUE TITLE
Not working for me.

### ISSUE THREAD

**Issue by rickytin** [nosmokingbandit/watcher#112]
It's not working for me. it give me all the time "Nothing found yet."
I add 7 provider and add a movie that I know my 7 provider have but it still give me "Nothing found yet."
I have delete the application, install again with git and add all the setting but still no lock.

**Comment by JoeStratton** [comment]
Did you add an indexer? Can you download that item outside of Watcher?

**Comment by rickytin** [comment]
Thanks for the replay Joe, yes I have add 7 indexer and yes I can download outside, I use NZB Hydra, CouchPotato and direct link and it download the movie.

**Comment by rickytin** [comment]
The last update fix my problem now is working.
