### ISSUE TITLE
Unable to find movies

### ISSUE THREAD

**Issue by ccnielsen** [nosmokingbandit/watcher#113]
Watcher is setup with two movies which have plenty of hits at the three indexers I have added to Watcher.  The appropriate https api address for each indexer is added as well as the api key.  These connections work within Sonarr.  I am also able to download the movie manually.  Unfortunately whether forced or automatic, the search does not return any movies to download.

Log entries from a manual search

> INFO 2017-01-06 09:57:45,411 core.sqldb.get_user_movies: Retreving list of user's movies.
> INFO 2017-01-06 09:58:52,088 core.sqldb.get_user_movies: Retreving list of user's movies.
> INFO 2017-01-06 09:58:54,076 core.sqldb.get_movie_details: Retreving details for tt2488496.
> INFO 2017-01-06 09:58:54,092 core.sqldb.get_search_results: Retreving Search Results for tt2488496.
> INFO 2017-01-06 09:58:57,428 core.newznab.search_all: SEARCHING: https://api.nzbgeek.info/api?apikey=APIKEY&t=movie&imdbid=2488496
> ERROR 2017-01-06 09:58:59,897 core.newznab.search_all: NewzNab search_all get xml
> Traceback (most recent call last):
>   File "C:\Program Files (x86)\Watcher\core\newznab.py", line 47, in search_all
>     nn_results = self.parse_newznab_xml(results_xml)
>   File "C:\Program Files (x86)\Watcher\core\newznab.py", line 74, in parse_newznab_xml
>     result_item = self.make_item_dict(channel_child)
>   File "C:\Program Files (x86)\Watcher\core\newznab.py", line 108, in make_item_dict
>     if not permalink:
> UnboundLocalError: local variable 'permalink' referenced before assignment
> INFO 2017-01-06 09:58:59,897 core.newznab.search_all: SEARCHING: https://api.nzb.su/api?apikey=APIKEY&t=movie&imdbid=2488496
> ERROR 2017-01-06 09:59:00,601 core.newznab.search_all: NewzNab search_all get xml
> Traceback (most recent call last):
>   File "C:\Program Files (x86)\Watcher\core\newznab.py", line 47, in search_all
>     nn_results = self.parse_newznab_xml(results_xml)
>   File "C:\Program Files (x86)\Watcher\core\newznab.py", line 74, in parse_newznab_xml
>     result_item = self.make_item_dict(channel_child)
>   File "C:\Program Files (x86)\Watcher\core\newznab.py", line 108, in make_item_dict
>     if not permalink:
> UnboundLocalError: local variable 'permalink' referenced before assignment
> INFO 2017-01-06 09:59:00,601 core.newznab.search_all: SEARCHING: https://api.dognzb.cr/api?apikey=APIKEY&t=movie&imdbid=2488496
> INFO 2017-01-06 09:59:01,408 core.sqldb.get_search_results: Retreving Search Results for tt2488496.
> INFO 2017-01-06 09:59:01,408 core.sqldb.get_movie_details: Retreving details for tt2488496.
> INFO 2017-01-06 09:59:01,408 core.sqldb.get_marked_results: Retreving Marked Results for tt2488496.
> INFO 2017-01-06 09:59:01,424 core.sqldb.get_distinct: Getting distinct values for tt2488496 in SEARCHRESULTS
> INFO 2017-01-06 09:59:01,424 core.updatestatus.movie_status: Setting MOVIES tt2488496 status to Wanted.
> INFO 2017-01-06 09:59:01,424 core.sqldb.update: Updating tt2488496 to Wanted in MOVIES.
> INFO 2017-01-06 09:59:01,502 core.sqldb.get_search_results: Retreving Search Results for tt2488496.
> INFO 2017-01-06 09:59:01,517 core.sqldb.get_user_movies: Retreving list of user's movies.
> INFO 2017-01-06 09:59:34,119 core.sqldb.get_user_movies: Retreving list of user's movies.

**Comment by imba3r** [comment]
See #100

**Comment by ccnielsen** [comment]
Ah, thanks.  Hopefully that pr is merged soon.
