### ISSUE TITLE
Can't get any results when searching

### ISSUE THREAD

**Issue by zebner1** [nosmokingbandit/watcher#115]
Using NZBGeek as my indexer, but can't return any results. Have tried several movies (ex. Legend of Tarzan). Clicking the magnifying glass to do a manual search. Any advice?

**Comment by jevb** [comment]
Did you manage too fix this? having the same problem atm.

**Comment by zebner1** [comment]
Yes. Silly mistake. Just needed to check the box next to the provider to activate it. 

> Zach Ebner | Credera
> 512.744.5150 | zebner@credera.com
> www.credera.com
