### ISSUE TITLE
Doesnt work

### ISSUE THREAD

**Issue by jevb** [nosmokingbandit/watcher#116]
When i try to run it i get this

```
Traceback (most recent call last):
  File "watcher/watcher.py", line 23, in <module>
    ssl._create_default_https_context = ssl._create_unverified_context
AttributeError: 'module' object has no attribute '_create_unverified_context'
```

if i edit the python file and comment it out it runs but when i got to localhost:9090 there is nothing

Ubuntu 14.04
Python2.7

**Comment by gewfie** [comment]
jevb,

Check out this pull request:
https://github.com/nosmokingbandit/watcher/pull/69

Need to make these modifications to get it running on Ubuntu 14.04

**Comment by jevb** [comment]
Thx Gewfie, that fixed my ssl problem, but now when i run it the webpage is not there or something is there anything els i need todo?

**Comment by gewfie** [comment]
By default it listens on localhost (127.0.0.1) only.  So if you are trying to access the interface from another machine on your LAN then this will not work.  You will need to edit the config file and change the "serverhost" variable to your LAN IP address.

Hope this helps.

**Comment by jevb** [comment]
First time i have to enter the actual ip into a config file for these kind of things, but it worked

**Comment by nosmokingbandit** [comment]
Python versions earlier than 2.7.9 handle ssl very poorly, hence the requirement for that version.
