### ISSUE TITLE
IMDb sync works for someone.

### ISSUE THREAD

**Issue by rickytin** [nosmokingbandit/watcher#117]
IMDb sync works for someone, can somebody explain how to make it work. 
I try with the method I use for Couchpotato, go to my watchlist, go to export this list and copy link address and paste it to Watcher settings.

**Comment by Elfman72** [comment]
It works for me.  Your link should look something like this http://rss.imdb.com/list/LISTIDHERE/

Remember, this watchlist needs to be publicly viewable.  So when you create your link and paste it into a browser, do you see your XML list of movies?

Paste it into watcher, save then restart.  Go back in and make sure the option is checked too.  When I did it  the first time, the link saved but the option wasn't checked.  Check it, and restart.  Should start working after about 6 hours.

**Comment by nosmokingbandit** [comment]
Since I was going to write all of this anyway I just added it to the wiki. Take a look and report back.

https://github.com/nosmokingbandit/watcher/wiki/Syncing-Watch-Lists

**Comment by 4getit** [comment]
The problem with the RSS feed is that it's limited to 250 entries. 

(Some kind of .csv import would be really helpful. If not automatically pulled, maybe uploading or drag/drop the .csv?)

**Comment by nosmokingbandit** [comment]
Does the RSS feed show the *newest* 250 items? Because the sync module keeps track of the last time it was checked and only goes back to that time.

**Comment by nosmokingbandit** [comment]
In the rss feed there is a section that contains the last modified date and time. It also includes a last modified date and time for each movie entry. Watcher stores this, then the next time it is synced it only looks for results that are newer than that time.

**Comment by 4getit** [comment]
Importing/parsing CSV would be great. Thank you!

**Comment by rickytin** [comment]
Still don't work for me, here is my Rss
http://rss.imdb.com/user/ur24402484/watchlist

**Comment by nosmokingbandit** [comment]
I'm still not sure what is causing your scheduler to not start the imdb timer thread.

Try making a [backup](https://github.com/nosmokingbandit/watcher/blob/master/README.md) (at the bottom of the readme), install fresh, and restore.

Report back regardless, please.

**Comment by rickytin** [comment]
Thanks for the replay, it's working since yesterday it sync and add the movies but my problem now it's that found some movies but it's not downloading automatically, I can download manually.
