### ISSUE TITLE
Cosmetic: Could the titles be "Movie Name (Year)"?

### ISSUE THREAD

**Issue by MartinAyla** [nosmokingbandit/watcher#118]
In the status page, could the titles be shown as "Movie Name (Year)" instead of "Movie Name Year"?

It makes it easier to see that the year number is not part of the title.

**Comment by nosmokingbandit** [comment]
I don't like parenthesis. I don't know why, I just don't.

Hoe about something like this:
http://i.imgur.com/NceEuAE.png

**Comment by soundjester** [comment]
Curse you parenthetical scum!  

Parenthesis for the movie year are both standard and proper form. In lieu of that, a CSS class would suit.

**Comment by MartinAyla** [comment]
If not parentheses, then something like the screenshot looks better too :)

**Comment by nosmokingbandit** [comment]
Cool, then I'm going to close this since I pushed that change anyway.
