### ISSUE TITLE
CSS Theming - Default/Dark option

### ISSUE THREAD

**Issue by soundjester** [nosmokingbandit/watcher#12]
There may be a need to offer the option of providing a dark/night theme for watcher.

I have created a small template whereby the existing theme, along with a dark theme or and any other themes can be quickly integrated into the platform.  This requires an option 'csstheme' to be added to the config file (core/config.py) under the [Server] options, and leverages this core config option on the various python templates (restart.py, shutdown.py, settings.py, etc) that reference CSS files.

This change slightly alters the structure of the static CSS file path by adding sub-folders according to the theme name (Default, Dark, etc). Themes need to only reference the specific CSS element/color they wish to alter, so base (aka default) CSS classes and structure remain untouched.  As future development occurs, new CSS classes and directives will be automatically incorporated into the themes, without the risk of breaking a themed element.

I would be happy to submit a pull request on the testing fork if you are interested.

**Comment by soupy14** [comment]
I'd be interesting it testing this out

**Comment by soundjester** [comment]
Theming is always tricky because it necessarily touches all of the front-facing files, which makes wholesale adoption a dicey proposition for the owner (who has poured a lot of effort into the application).  Fortunately, the codebase, and thus these changes, are fairly straightforward, The CSS is well segregated, and the libraries themselves are unaffected.  One change to the config file, and a few lines added to the python page templates are the main components of this pull request.

**Comment by WilliamJBrown** [comment]
Just adding I love the ability for a dark theme :)

**Comment by soundjester** [comment]
It looks very nice, even if I do say so myself.

**Comment by nosmokingbandit** [comment]
I saw this pull request, but I need to get a few other things figured out first. Running the webroot at any location other than '/' (ie /watcher for behind a proxy) breaks a lot of relative paths and I can't seem to find a good way to get cherrypy to handle this without rewriting every link based on the webroot path.

It is a good way of doing this, but if we implement it now I'm certain it will break when I get the webroot problem figured out.

**Comment by soundjester** [comment]
Yep. I agree that webroot issue is primary, and implementation of this at a later stage should not cause considerable difficulty.  I keep adding this functionality back in to each subsequent clone and it has yet to be a major procedure.

Giving the templates code a cursory look, it feels like there should be some way to control the css area of the python scripts with a control or procedural configuration somehow. That way if something changes with the static files, only one area needs to change. I may think on it a while and see if an idea occurs.  If it does, I'll let you know.

**Comment by soundjester** [comment]
It seems like you've fully figured out the proxy/reverse proxy/webroot situation, so I'd like to get started on this enhancement.

**Comment by nosmokingbandit** [comment]
Sure. I can't guarantee that the css I wrote is efficient at all, but its usable for a stating point.

I'm going to add a settings option to select a theme, which should be pretty easy by just enumerating the folders in /static/css/ and offering the user a choice.

I'm going to go through and change all of mine to a Default folder, implement the picker, then look at merging your request.

**Comment by soundjester** [comment]
Setting option and corresponding config options has already been added in the PR.

Don't care about efficient CSS. Do care about color!

**Comment by nosmokingbandit** [comment]
Yeah, but I didn't like they way you did it ;)

My way you just need to drop a new folder in static/css/ and you are done, nothing needs to be modified on the backend or ui to accommodate new themes.

I'm going to close this since everything is merged into the master branch now. Feel free to add a wiki page if you feel like it. Feel free to not add a page if you don't feel like it.

**Comment by soundjester** [comment]
Yes, your way is procedurally superior.

The tradeoff is that you now need to restart the app to switch themes.

I'll add to the wiki when I figure out what to add...  The CSS theming is (right now) incredibly straight-forward (for a dev).
