### ISSUE TITLE
IMDb list import

### ISSUE THREAD

**Issue by 4getit** [nosmokingbandit/watcher#120]
To automate things, it would be great to be able to import IMDb complete watchlists. 
At this moment, it is possible to let Watcher automatically pull the RSS feed. However, this is limited to 250 entries.

IMDb has an option 'Export this list'. That will create a complete .csv file.
I'm not sure if this .csv can be made publicly available but if not, maybe it would be an idea to make it possible to import this list. Either via an upload function or a drag/drop.  

CP seems to use the complete .csv exports instead of the partial rss lists:
https://github.com/eristoddle/CouchPotato/blob/master/app/lib/imdbwl.py

**Comment by nosmokingbandit** [comment]
Around 2013 IMDB started requiring a user to log in to download a watchlist csv. If you aren't logged in you just get a 404.

What you linked to is from 2012, before the auth requirement, which is just a simple urllib request.

I poked around CouchPotato's code a little and I can't figure out how they do it without a login. That code is kind of all over the place, so I might have to dedicate more time to sifting through it.

**Comment by 4getit** [comment]
Hmm... that's not cool. 
Would it be easier (for now) to make it so we can upload/submit downloaded .csv's?
Or.. is there an API like workaround to (for example) do Post or Get requests with IMDb ID's to some a Watcher url?

**Comment by nosmokingbandit** [comment]
Looking at CP's current code is interesting.

They don't import the csv at all. They use the data in the csv url to construct the url for the list webpage, then scrape the page for imdb #s.

IMDB explicitly prohibits scraping (although they really can't detect it), but I mostly like to avoid scraping because it is inherently unreliable. The only need to change one layout element to break the whole thing.

I'll keep looking into it, but I might just start working on Trakt integration instead.

**Comment by 4getit** [comment]
Good idea. Trakt integration would be a good alternative.
Maybe keep an open mind on creating some API hooks as well so we can submit IMDb's automatically?

**Comment by nosmokingbandit** [comment]
The [api](https://github.com/nosmokingbandit/watcher/wiki/API) already has a method to submit imdb numbers.

I'll eventually work on a method to import a downloaded csv.

**Comment by 4getit** [comment]
Excellent. Thank you

**Comment by nosmokingbandit** [comment]
I'm going to close this.

A longer IMDB import is something I'll keep in mind, but I'm very much opposed to screen scraping. It violates IMDB's TOS (which doesn't really bother me all that much to be completely frank), and it is inherently fragile.

I may add a csv import in the future, but I'm certain that won't be a huge priority.
