### ISSUE TITLE
No results when searching for movies

### ISSUE THREAD

**Issue by jevb** [nosmokingbandit/watcher#121]
When i manualy search for a movie that i know my indexer has (NZBgeek) nothing shows up
i get this in my log file:

`INFO 2017-01-07 23:35:03,812 core.sqldb.get_user_movies: Retreving list of user's movies.
INFO 2017-01-07 23:35:05,794 core.sqldb.get_user_movies: Retreving list of user's movies.
INFO 2017-01-07 23:35:09,292 core.sqldb.get_movie_details: Retreving details for tt0449088.
INFO 2017-01-07 23:35:09,294 core.sqldb.get_search_results: Retreving Search Results for tt0449088.
INFO 2017-01-07 23:35:17,280 core.sqldb.get_movie_details: Retreving details for tt0449088.
INFO 2017-01-07 23:35:17,281 core.rss.predb.check_one: Checking predb.me for new available releases for Pirates of the Caribbean: At World's End.
ERROR 2017-01-07 23:35:17,368 core.rss.predb.search_rss: PREDB search.
Traceback (most recent call last):
  File "/home/jevb/watcher/core/rss/predb.py", line 79, in search_rss
    results_xml = urllib2.urlopen(request).read()
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1222, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1184, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 1] _ssl.c:510: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error>
INFO 2017-01-07 23:35:17,368 core.sqldb.get_movie_details: Retreving details for tt0449088.
INFO 2017-01-07 23:35:17,369 core.rss.predb.check_one: Checking predb.me for new available releases for Pirates of the Caribbean: At World's End.
ERROR 2017-01-07 23:35:17,455 core.rss.predb.search_rss: PREDB search.
Traceback (most recent call last):
  File "/home/jevb/watcher/core/rss/predb.py", line 79, in search_rss
    results_xml = urllib2.urlopen(request).read()
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1222, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1184, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 1] _ssl.c:510: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error>
INFO 2017-01-07 23:35:17,456 core.sqldb.get_movie_details: Retreving details for tt0449088.
INFO 2017-01-07 23:35:17,472 core.sqldb.get_user_movies: Retreving list of user's movies.
INFO 2017-01-07 23:35:17,476 core.sqldb.get_search_results: Retreving Search Results for tt0449088.
`

Any idea?

Ubuntu 14.04
Python 2.7.6

**Comment by soundjester** [comment]
So, this has hasn't really been said in so many words but... Ubuntu 14.04 just isn't going to be a great host OS for this.  The packaged version of Python for 14.04 isn't suitable for this application, and in order to get to the required Python 2.7.9+, you'll need to compile it manually, which is obviously not a great turn-key solution for most folks.

Since the README makes it clear that Python 2.7.9+ is required, you probably aren't going to get much direct help on this issue.

**Comment by jevb** [comment]
Alright, guess il have to update too 16.04.1 LTS

**Comment by nosmokingbandit** [comment]
I haven't used ubuntu in ages but can't you add the 16.04 repo and install with something like this:

`aptitude install -t yakkety python`

I can almost guarantee that syntax is wrong, but I know you can have it manage specific packages from a different releases repo.

**Comment by calebcall** [comment]
I came across this same issue on Mac OS X Sierra (10.12.2) with python 2.7.10.  Changing the link from https to http fixed it.  I'm going to play with the ciphers and see if I can get it working with https.  This may be a new bug as I never had this issue prior to the latest update.

**Comment by soundjester** [comment]
@nosmokingbandit Updated 2.7.12 _can_ be pulled in pre-compiled from an [unsupported canonical repository](https://launchpad.net/~fkrull/+archive/ubuntu/deadsnakes-python2.7/+packages).  [General Instructions Here](http://askubuntu.com/questions/101591/how-do-i-install-python-2-7-2-on-ubuntu). 

That said, there are still a non-trivial number of finicky bits to doing that, and unless a user has a burning desire and technical acumen to use Trusty for whatever reason, an upgrade is probably a good call.
