### ISSUE TITLE
PlexRequests Integration (Feature Request)

### ISSUE THREAD

**Issue by Zirus1701** [nosmokingbandit/watcher#125]
The ability for PlexRequests to integrate to the application, so external users can request movies via PlexRequests and have them automatically added to Watcher via PlexRequests. 

Currently, PlexRequests has Couchpotato integration (but CP sucks), so it would be amazing to have Watcher integration instead.

**Comment by TheRealShiz** [comment]
PlexRequests is adding integration in v2, you should go check the thread over there.

**Comment by calebcall** [comment]
Yep, already being done.  Besides, watcher has provided the API, now it will be up to plexrequests to integrate.

**Comment by Zirus1701** [comment]
Oh, outstanding. Thanks for the information guys, great to hear it's in the works.

**Comment by tidusjar** [comment]
Keep an eye on this: https://github.com/tidusjar/Ombi/issues/878
