### ISSUE TITLE
Search quirk

### ISSUE THREAD

**Issue by Montevideo** [nosmokingbandit/watcher#126]
I was adding some upcoming movies earlier and tried to add A MOVIE (I know it's early, just messing about really) but the search didn't find it, brought up some tv shows and other weirdness.

Tried A MOVIE 2017 and it found it no problem.

Not urgent, just mentioning it to be a good citizen :-)

edit by NSB:
Please don't mention specific media names or titles.

**Comment by nosmokingbandit** [comment]
Yeah, OMDB's search acts really stupid about recently-added movies like that.

I have plans to switch to something better, but its complicated.

You can also search with the imdb # (tt0000000) as well.
