### ISSUE TITLE
Getting permission denied on update now

### ISSUE THREAD

**Issue by Elfman72** [nosmokingbandit/watcher#128]
Trying to update to the latest commit.  Updating through the app has always worked before.  However now when I click update, I get an error telling me to check my logs.  This is what is in my logs:

```
INFO 2017-01-09 06:18:12,733 core.version.execute_update: Update failed: warning: unable to access '/opt/watcher/.config/git/attributes': Permission denied
warning: unable to access '/opt/watcher/.config/git/ignore': Permission denied
error: Your local changes to the following files would be overwritten by merge:
	core/rss/imdb
Please commit your changes or stash them before you merge.
Aborting
Updating 19c4639..6732436
INFO 2017-01-09 06:18:12,734 core.ajax._update_now: Update Failed.
```
 Running this within Docker on a Synology so I don't have direct access to the git files.

**Comment by jevb** [comment]
Had the same problem.

 That imdb file has the date or something in it, and once i removed this i was able too update it

**Comment by Elfman72** [comment]
Thanks, @jevb .  Care to share what you did?  Again, I am running this in Docker on a synology and I don't do much SSHing into that box.  Though I can, I am just not familiar with linux enough to be comfortable to perform such a task.

NZBHydra gives me a similar error.  However since they put all of their files in the /config directory, I am able to just download from git, stop the container, replace the files and then start the container again.

**Comment by nosmokingbandit** [comment]
.gitignore seems to only work when it feels like it...

Everything should be ok now. I'll double check on my next commit that it doesn't push that file over.
