### ISSUE TITLE
Error After Git Pull

### ISSUE THREAD

**Issue by microSCOPED** [nosmokingbandit/watcher#129]
I just did a git pull on the master repo and I am now getting the following error:

500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

```
Traceback (most recent call last):
  File "/opt/watcher/lib/cherrypy/_cprequest.py", line 642, in respond
    self.get_resource(path_info)
  File "/opt/watcher/lib/cherrypy/_cprequest.py", line 760, in get_resource
    dispatch(path)
  File "/opt/watcher/lib/cherrypy/_cpdispatch.py", line 288, in __call__
    func, vpath = self.find_handler(path_info)
  File "/opt/watcher/lib/cherrypy/_cpdispatch.py", line 337, in find_handler
    objname = name.translate(self.translate)
TypeError: character mapping must return integer, None or unicode
```

**Comment by Crowley007** [comment]
I get the same error, not working at all after the most recent update.

**Comment by sugarfunk** [comment]
Same error here. Related to password protected web ui. Removing this option allows server to not throw the 500 error

**Comment by l3uddz** [comment]
having password enabled watcher doesnt work. until it is fixed cannot be used on remote server. looks a great tool and will keep eye on it as want to see good alternative for couchpotato and watcher looks like it may be it one day!

**Comment by nosmokingbandit** [comment]
I went on an angry unicode bender and it broke CherryPy's session storage. It won't use a a unicode string as a session name even though it specifically asks for it. Bleh.

Anyway, this is fixed as of https://github.com/nosmokingbandit/watcher/commit/926dc4b72561641f6b61bb8af2e4ebd541d5f601. You can either manually `git pull` or edit your config to disable authorization, then update and re-enable.
