### ISSUE TITLE
A way to prevent watcher to found trailers as the movie.

### ISSUE THREAD

**Issue by rickytin** [nosmokingbandit/watcher#130]
I try to add trailer to Ignored words in quality settings but it did not work.

**Comment by nosmokingbandit** [comment]
Ignored Words filter the title of the release. I can confirm it is working correctly.

If `Trailer` is not in their title you can adjust your size requirements seeing as trailers should be significantly smaller than a full film.

**Comment by rickytin** [comment]
Thanks for the replay, this is the file I mention and it's a big file.
"Trailer 1 - Arrival 1080p WEB-DL Available Size: 3.5 GB"

**Comment by nosmokingbandit** [comment]
Fixed in https://github.com/nosmokingbandit/watcher/commit/bda947aa45cb2db34f8822454d7eef17e0b3a659.

Weird bug where if the filters removed *all* results it wouldn't trigger a purge of existing results.
