### ISSUE TITLE
Search not working with Nzb-Hydra

### ISSUE THREAD

**Issue by Crowley007** [nosmokingbandit/watcher#131]
I know it did work at some point, but currently it does not.  I get the following in the log, it's the same with everything I search for:

`INFO 2017-01-10 20:15:39,594 core.sqldb.get_user_movies: Retreving list of user's movies.
INFO 2017-01-10 20:15:41,696 core.sqldb.get_movie_details: Retreving details for *******.
INFO 2017-01-10 20:15:41,700 core.sqldb.get_movie_details: Retreving details for *******.
INFO 2017-01-10 20:15:41,706 core.sqldb.get_movie_details: Retreving details for *******.
INFO 2017-01-10 20:15:41,710 core.newznab.search_all: SEARCHING: http://192.168.0.2:5075/nzbhydra/api?apikey=APIKEY&t=movie&imdbid=******
INFO 2017-01-10 20:15:53,881 core.sqldb.get_search_results: Retreving Search Results for *******.
INFO 2017-01-10 20:15:53,885 core.sqldb.get_movie_details: Retreving details for *******.
INFO 2017-01-10 20:15:53,891 cherrypy.error.73470640.error: [10/Jan/2017:20:15:53] HTTP 
Request Headers:
  REFERER: http://**********:9000/watcher/status/
  Remote-Addr: 127.0.0.1
  X-REAL-IP: **********
  Content-Length: 32
  USER-AGENT: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.79 Safari/537.36 Edge/14.14393
  CONNECTION: close
  COOKIE: logged=%242y%2410%24vVSkSgtGw7HFNxMu2xPo1.U7x%2FPVQo2MZ%2FH56W.gNelt38Qoh1EqC; _pk_id.1.c490=4b562e1c30643130.1479674203.213.1484041234.1484041234.; snatched_view=list; soon_view=thumb; suggest_view=thumb; late_view=list; blu_ray_com_new_releases_view=thumb; imdb_movies_in_theaters_view=thumb; imdb_box_office_view=thumb; imdb_top_dvd_rentals_view=thumb; wanted_view=thumb; session=d8c33e21-66a8-4d56-bd37-201b57acc5e0; advanced_toggle_checked=1; manage_view=thumb; user="2|1:0|10:1482419263|4:user|44:YTg4MzBmZmU0MzNjNGUwZmJhYWI5Yzc4NzM3NTg1NTA=|2a40a93dca9fd4950f36fd63b64308cd702128bbb2386c050eb06189bdba6cd6"; _ncfa=Ufi7HL00w8M00bm6W8r2mcxMpz%2bhxYQ1vsW1kG4plmc%3d%2fjtQJaLxWT5p2vSeuspndYK9H62%2fIekwfegTvD3JumNvMFcfrN3Ea1qDhBMGgWHJ; session_id=a474522bdd62a6e5013edbf9ff369372f3672871
  X-REQUESTED-WITH: XMLHttpRequest
  HOST: **********
  CACHE-CONTROL: no-cache
  ACCEPT: */*
  ACCEPT-LANGUAGE: fi,en-US;q=0.7,en;q=0.3
  X-FORWARDED-FOR: **********
  Content-Type: application/x-www-form-urlencoded; charset=UTF-8
  ACCEPT-ENCODING: gzip, deflate
ERROR 2017-01-10 20:15:53,891 cherrypy.error.73470640.error: [10/Jan/2017:20:15:53] HTTP 
Traceback (most recent call last):
  File "c:\Git\watcher\lib\cherrypy\_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "c:\Git\watcher\lib\cherrypy\lib\encoding.py", line 220, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "c:\Git\watcher\lib\cherrypy\_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "c:\Git\watcher\core\ajax.py", line 235, in search
    self.searcher.search(imdbid, title)
  File "c:\Git\watcher\core\searcher.py", line 158, in search
    scored_results = self.score.score(newznab_results, imdbid, 'nzb')
  File "c:\Git\watcher\core\scoreresults.py", line 58, in score
    self.remove_ignored(ignored)
  File "c:\Git\watcher\core\scoreresults.py", line 106, in remove_ignored
    print i['title'].lower()
IOError: [Errno 9] Bad file descriptor`

**Comment by nosmokingbandit** [comment]
It was working fine for me with NZBH, but try it after commit https://github.com/nosmokingbandit/watcher/commit/ba81ffdfa5636601bbebd15897672f73e1b1171c.

The line that was throwing the exception was an old testing print anyway.

**Comment by Crowley007** [comment]
This seems to fix it, thanks!
