### ISSUE TITLE
New Postprocesser not Moving Files

### ISSUE THREAD

**Issue by vertigo235** [nosmokingbandit/watcher#133]
So, NZBGet completes and sends the info over to Watcher, it looks like all the correct paths are sent via the post process script.

It looks like Watcher properly creates the destination folder, but the movie files are not moved, here is a log snippit. 

I had the renamer turned off, because it wasn't working in an earlier build, so I tried to turn that on to see if that fixed the issue, but it did not. 

INFO 2017-01-10 18:55:20,863 core.sqldb.update: Updating REDACTED to Finished in MOVIES.
INFO 2017-01-10 18:55:21,701 core.sqldb.update: Updating REDACTED to 2017-01-10 in MOVIES.
INFO 2017-01-10 18:55:22,336 core.postprocessing.complete: Renamer disabled.
INFO 2017-01-10 18:55:22,355 core.postprocessing.mover: Moving  to /volume1/Video1/Movies/REDACTED
ERROR 2017-01-10 18:55:22,356 core.postprocessing.mover: Mover failed: Could not move file.
Traceback (most recent call last):
  File "/opt/watcher/app/core/postprocessing.py", line 693, in mover
    shutil.move(data['filename'], target_folder)
  File "/usr/lib64/python2.7/shutil.py", line 292, in move
    raise Error, "Destination path '%s' already exists" % real_dst
Error: Destination path '/volume1/Video1/Movies/REDACTED/' already exists
INFO 2017-01-10 18:55:22,429 core.postprocessing.POST: {
  "data": {
    "apikey": "e479d42aa19683f6edf5885c9aaa00eb", 
    "audiocodec": "", 
    "downloadid": "850", 
    "dvd": "01 Nov 2002", 
    "filename": "", 
    "finisheddate": "2017-01-10", 
    "finishedscore": 705, 
    "guid": "REDACTED", 
    "imdbid": "REDACTED", 
    "mode": "complete", 
    "path": "%2Fvolume1%2Fdownloads%2Fnzbget%2Fdst%2Fwatcher%2FREDACTED.Watcher", 
    "poster": "images/poster/REDACTED.jpg", 
    "predb": "found", 
    "rated": "PG-13", 
    "released": "03 May 2002", 
    "releasegroup": "", 
    "resolution": "", 
    "source": "", 
    "status": "Snatched", 
    "title": "REDACTED", 
    "tomatorating": "7.7", 
    "tomatourl": "http://www.rottentomatoes.com/m/REDACTED/", 
    "videocodec": "", 
    "year": "REDACTED"
  }, 
  "status": "finished", 
  "tasks": {
    "cleanup": {
      "enabled": "true", 
      "response": "false"
    }, 
    "REDACTED": {
      "update_MARKEDRESULTS": "true", 
      "update_SEARCHRESULTS": "true"
    }, 
    "mover": {
      "enabled": "true", 
      "response": "false"
    }, 
    "update_movie_status": "true"
  }
}
INFO 2017-01-10 18:55:22,429 core.postprocessing.POST: #################################
INFO 2017-01-10 18:55:22,429 core.postprocessing.POST: Post-processing complete.
INFO 2017-01-10 18:55:22,430 core.postprocessing.POST: #################################

**Comment by vertigo235** [comment]
it's an encoded string %2Fvolume1%2Fdownloads%2Fnzbget%2Fdst%2Fwatcher%2 instead of
/volume1/downloads/nzbget/dst/watcher/

**Comment by vertigo235** [comment]
see this error farther up, shouldn't the URL encoding be removed somewhere before finding the path via filesystem?

ERROR 2017-01-10 18:55:15,490 core.postprocessing.get_filename: Path not found in filesystem.
Traceback (most recent call last):
  File "/opt/watcher/app/core/postprocessing.py", line 204, in get_filename
    files = os.listdir(path)
OSError: [Errno 2] No such file or directory: '%2Fvolume1%2Fdownloads%2Fnzbget%2Fdst%2Fwatcher%2FREDACTED.Watcher'

**Comment by vertigo235** [comment]
OK I fixed the issue, the new nzbget.py post-process script. 

Line 47
-data['path'] = urllib2.quote(os.environ['NZBPP_DIRECTORY'], safe='')
+data['path'] = os.environ['NZBPP_DIRECTORY']

No need to URL encode because it is using POST method now, instead of GET

**Comment by vertigo235** [comment]
I created a pull request https://github.com/nosmokingbandit/watcher/pull/134 , hopefully I did it right this time.

**Comment by nosmokingbandit** [comment]
This is what happens when I stay up too late working on this...

Pulled into Testing. I have a few other things staged, so I'll merge this with Master later on today.

Thanks!
