### ISSUE TITLE
Timeout on Postprocess

### ISSUE THREAD

**Issue by vertigo235** [nosmokingbandit/watcher#135]
Things are moving kind of slow on my NAS that this runs on and sometimes it takes a while to move the movie files, especially big ones. This causes the postprocessing script to timeout waiting for a response from watcher. 

Everything still processes normally in watcher but nzbget logs the post process script as a failure.

Can we have the post process script just report back success once all the necessary bits are sent to watcher for post processing?  Or extend the timout period so that watcher does not return a timeout.  I prefer the former because there is no need for NZBGET to sit around waiting for the file move to finish.  It is time that can be spent downloading other files instead.

**Comment by vertigo235** [comment]
from the console log
192.168.1.5 - - [10/Jan/2017:21:32:53] &quot;POST /postprocessing/ HTTP/1.1&quot; 200 1932 &quot;&quot; &quot;Mozilla/5.0&quot;
stdout
21:32:53
[10/Jan/2017:21:32:53]  Traceback (most recent call last):
stdout
21:32:53
  File &quot;/opt/watcher/app/lib/cherrypy/_cpwsgi.py&quot;, line 189, in trap
stdout
21:32:53
    return func(*args, **kwargs)
stdout
21:32:53
  File &quot;/opt/watcher/app/lib/cherrypy/_cpwsgi.py&quot;, line 105, in __call__
stdout
21:32:53
    return self.nextapp(environ, start_response)
stdout
21:32:53
  File &quot;/opt/watcher/app/lib/cherrypy/_cpwsgi.py&quot;, line 439, in tail
stdout
21:32:53
    return self.response_class(environ, start_response, self.cpapp)
stdout
21:32:53
  File &quot;/opt/watcher/app/lib/cherrypy/_cpwsgi.py&quot;, line 245, in __init__
stdout
21:32:53
    self.run()
stdout
21:32:53
  File &quot;/opt/watcher/app/lib/cherrypy/_cpwsgi.py&quot;, line 348, in run
stdout
21:32:53
    request.run(meth, path, qs, rproto, headers, rfile)
stdout
21:32:53
  File &quot;/opt/watcher/app/lib/cherrypy/_cprequest.py&quot;, line 617, in run
stdout
21:32:53
    raise cherrypy.TimeoutError()
stdout
21:32:53
TimeoutError
stdout
21:32:53
stdout
21:46:05

**Comment by WilliamJBrown** [comment]
Isn't it technically nzbget moving the file i could be wrong. Watcher just points the directory? What nas are you using? It can't get more lightweight then watcher?

**Comment by vertigo235** [comment]
No watcher is definitely moving the file its part of the renaming process. Nzbget just sends the download path to watcher and waits for it to return success.

**Comment by nosmokingbandit** [comment]
No, Watcher does the moving via shutil.copy2()

The problem I see is that NZBGet expects a response from the post-script. So if the script tells Watcher to move the file and doesn't wait for a response it still has to tell NZBGet something.

I wasn't sure about just raising the timeout, but https://github.com/clinton-hall/nzbToMedia uses a 10 minute timeout for some requests.

I'll play with the timeout and see what I like.

**Comment by nosmokingbandit** [comment]
I changed the timeout in commit https://github.com/nosmokingbandit/watcher/commit/b33a7103c4a8c8c95e3eaa517ca5a43bc40f524c.

Replace your post-processing scripts and try again. Let me know what happens.

**Comment by vertigo235** [comment]
I saw that in your test branch and went ahead and updated my post processing script.  I will test tomorrow as I'm out of town at the moment.

**Comment by vertigo235** [comment]
I didn't test it yet, but someone else opened an issue that it failed, I updated my script and it works fine, but it wasn't a long copy. Sent pull request. 

https://github.com/nosmokingbandit/watcher/pull/145
