### ISSUE TITLE
More post process problems.

### ISSUE THREAD

**Issue by Crowley007** [nosmokingbandit/watcher#136]
It seems issue https://github.com/nosmokingbandit/watcher/issues/74 is back. It did work with a few files when I tested, but for some reason not anymore. Again the folder name is correct before moving. 

`"filename": "Z:\\Data\\Download\\Movies\\The.Correct.Movie.Name.AVC.DTS-HD.MA.7.1-BMF\\xWOmgx2CX.mkv", 
    "finisheddate": "2017-01-11", 
    "guid": "http://192.168.0.2:5075/nzbhydra/getnzb?apikey=*********************&downloader=NZBGet", 
    "imdbid": "", 
    "mode": "complete", 
    "**new_file_location": "Z:\\Media\\Leffat\\Lataus\\xWOmgx2CX\\xWOmgx2CX.mkv**",

**Comment by nosmokingbandit** [comment]
Can you send the full post-processing section of the log to watchernzb@gmail.com? Un-redacted please.

**Comment by Crowley007** [comment]
Ok, I'll do a quick test and send the full log. 

Also a question, If a download fails in NZBget, will watcher download the next best release automatically?

**Comment by Crowley007** [comment]
I now got the original error again, full post process log sent by email.

**Comment by Crowley007** [comment]
This seems to be fixed.
