### ISSUE TITLE
Not downloading automatically.

### ISSUE THREAD

**Issue by rickytin** [nosmokingbandit/watcher#137]
Watcher sync with IMDB and found some movies but it's not downloading automatically, I can download manually.

**Comment by Elfman72** [comment]
You know, I hadn't given it much thought but I don't think I have had anything automate either.  Just been so busy tweaking and testing the new software, I don't think I have seen anything automate.  Manual is just fine.

**Comment by lessthantom** [comment]
Yeh me either

**Comment by nosmokingbandit** [comment]
Fixed in 2b6ee4c995739f868566523424be5ca551be43fd.

Broken loop from a long time ago. I'm surprised nobody else brought it up. It just snatched 5 movies at one for me, so you should be ready to go after this.
