### ISSUE TITLE
Post Processing Script Error

### ISSUE THREAD

**Issue by mikepruett3** [nosmokingbandit/watcher#138]
So I have SABnzbd configured correctly,  and is setup to use the sabnzbd.py post-processing script. (I renamed it to watcher.py, as in the wiki.)

Now when I download a file, I get this error from SABnzbd...

```
File "/scripts/watcher.py", line 29
    print u'Post-processing failed. Incorrect args.'
                                                   ^
SyntaxError: Missing parentheses in call to 'print'
```

Any ideas? Not really good with Python.

**Comment by mikepruett3** [comment]
Never-mind, I had to uninstall python3, and install python2. Seems to work fantastic now!

If your like me, and using the [uirel/watcher](https://hub.docker.com/r/uirel/watcher/) docker container, use the following to install the correct version of python...

pacman -S python2

**Comment by vertigo235** [comment]
You should also notify the maintainer of the dockerfile to add that to the included packages that are installed.

**Comment by vertigo235** [comment]
I tested the change and works fine for me, created pull request https://github.com/nosmokingbandit/watcher/pull/145

**Comment by mikepruett3** [comment]
Will do. Thank You.
