### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by poplolnman** [nosmokingbandit/watcher#139]
I was wondering if this was working as developed where i had already manually downloaded the movie successfully the night before(the movie was marked as finished) and yet the next day it redownloaded it again,,,

**Comment by nosmokingbandit** [comment]
There was a bug where the finished movie's score wasn't always recorded. This has been fixed in commit https://github.com/nosmokingbandit/watcher/commit/032fb6ae991df9503684091234a1aa87e9c00e57
