### ISSUE TITLE
Indexer Issues

### ISSUE THREAD

**Issue by TheRealShiz** [nosmokingbandit/watcher#141]
This call:

https://api.dognzb.cr/api?apikey=REMOVED&t=movie&imdbid=3263904

returns:

```
<rss xmlns:atom="http://www.w3.org/2005/Atom" version="2.0">
<channel>
<title>DOGnzb</title>
<link>http://dognzb.cr</link>
<description>DOGnzb Feed 1E</description>
<language>en-us</language>
</channel>
</rss>
```

whereas this call:

https://api.dognzb.cr/api?imdbid=3263904&apikey=REMOVED&t=movie

returns:

```
<rss xmlns:atom="http://www.w3.org/2005/Atom" xmlns:newznab="http://www.newznab.com/DTD/2010/feeds/attributes/" version="2.0">
<channel>
<title>DOGnzb</title>
<description>DOGnzb Feed</description>
<uuid>C282E5A6</uuid>
<newznab:response offset="0" total="29"/>
<item>
<title>Sully.2016.1080p.BluRay.DD5.1.x264-SbR</title>
<guid isPermaLink="true">
https://dognzb.cr/details/212d348405ba63369c9472334a9a571b
</guid>
<link>
https://dognzb.cr/fetch/212d348405ba63369c9472334a9a571b/2317ec159d7ae76680ca0e5768d16d92
</link>
<comments>
...truncated for brevity
```

**Comment by TheRealShiz** [comment]
I guess I should clarify that the first api call above was what I copied out of the Watcher logs and I'm definitely getting 0 results.  Not sure if its a Dog problem or a Watcher problem.  I checked the Newznab docs and its not clear about the order of parameters (not sure why it would matter) and in fact the sample call in the docs had them in a different order from either of these calls.

**Comment by kirkyg** [comment]
I'm having a similar issue.  Sonarr seems to be completed calls to dog and nzbfinder just fine, but watcher returns zero results via API calls.

**Comment by nosmokingbandit** [comment]
GET request parameters are, by definition, non-positional. If you are using the exact same queries in each request (albeit in a different order) and getting different results it is likely a problem on their end.

**Comment by TheRealShiz** [comment]
I posted on the Dog forums about the issue and let them know I would be passing their contact info on.  I've emailed you.

**Comment by TheRealShiz** [comment]
Someone on Dog forum replied to my thread saying the Dog API is just flaky right now.  Make the same call and get a good response 4/5 times.  So I tried the first call that failed and sure enough, working now.  Its probably safe to close this now unless you want to keep it open for others with the same problem to see.

**Comment by nosmokingbandit** [comment]
I'll close this because it makes me feel better seeing the Issues # go down, but this is good to know.

From what I've heard, Dog's api has a history of being kind of wonky.

**Comment by kirkyg** [comment]
I'm still testing this and not able to get a single result set back with dog manually refreshing or adding new to my watch list.  It literally NEVER returns.  If i manually take my key and switch the parameters in my browser and run the url i get the full results every single time.

**Comment by nosmokingbandit** [comment]
Send me your log.

watchernzb@gmail.com

I had a problem with another indexer that was failing because they didn't follow newznab specs.
