### ISSUE TITLE
Layout choice isn't saved ("Display:")

### ISSUE THREAD

**Issue by MartinAyla** [nosmokingbandit/watcher#144]
It seems the layout choice isn't saved. If I set "Display:" to "List" for example and go to Settings and then back to Status, the layout choice resets to "Posters".

**Comment by nosmokingbandit** [comment]
This has been fixed in commit https://github.com/nosmokingbandit/watcher/commit/a6efa41a94d52e4fca641b2816f4e56c09e8a332.

Without explicitly defining an expiration time they are removed immediately after leaving the page.
