### ISSUE TITLE
Request: Categories

### ISSUE THREAD

**Issue by robomercado** [nosmokingbandit/watcher#149]
It would be great if we can create categories. Categories for quality preference or to affect post-processing actions, such as saving to specific folders. Organizing data by genres, video quality or year of release would be great.

**Comment by nosmokingbandit** [comment]
I don't see this happening. At least not to any depth. I have an update ready to roll out that will add quality profiles, but I'm not sure I want to have conditional post-processing.

I'll eventually have a plugin system where scripts can fire after snatch/finish/post-processing, and it would be pretty easy to make a script that sorts movies by whatever you want afterward.
