### ISSUE TITLE
Potential Bug Fix: Revolve persistent SQL error on scheduled search

### ISSUE THREAD

**Issue by soundjester** [nosmokingbandit/watcher#150]
I've been having a persistent SQL error (mentioned in #81) that occurs prior/during the scheduled movie search.  It has been ongoing for a while (since at least Jan 4th).  For good order, the error is as follows:

```

INFO 2017-01-08 00:30:43,082 core.sqldb.get_user_movies: Retreving list of user's movies.
ERROR 2017-01-08 00:30:43,084 core.sqldb.execute: SQL Databse Query: SELECT * FROM MOVIES ORDER BY title ASC
Traceback (most recent call last):
  File "/usr/share/watcher/core/sqldb.py", line 90, in execute
    result = self.engine.execute(command)
  File "/usr/share/watcher/lib/sqlalchemy/engine/base.py", line 2058, in execute
    return connection.execute(statement, *multiparams, **params)
  File "/usr/share/watcher/lib/sqlalchemy/engine/base.py", line 939, in execute
    return self._execute_text(object, multiparams, params)
  File "/usr/share/watcher/lib/sqlalchemy/engine/base.py", line 1097, in _execute_text
    statement, parameters
  File "/usr/share/watcher/lib/sqlalchemy/engine/base.py", line 1189, in _execute_context
    context)
  File "/usr/share/watcher/lib/sqlalchemy/engine/base.py", line 1393, in _handle_dbapi_exception
    exc_info
  File "/usr/share/watcher/lib/sqlalchemy/util/compat.py", line 202, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/share/watcher/lib/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/usr/share/watcher/lib/sqlalchemy/engine/default.py", line 462, in do_execute
    cursor.execute(statement, parameters)
OperationalError: (sqlite3.OperationalError) no such table: MOVIES [SQL: 'SELECT * FROM MOVIES ORDER BY title ASC']
```

I believe that this is due to the use of a relative path in sqldb.py "SQL" class, specifically [line 18](https://github.com/nosmokingbandit/watcher/blob/master/core/sqldb.py#L18).

I was able to resolve this error by converting the relative path to an absolute path:

`DB_NAME = 'sqlite:////{}'.format(os.path.join(core.PROG_PATH, core.DB_FILE))`

I have some inkling as to why this fix works and why it was happening in the first place, but with limited knowledge of the library architecture, my theories are simply conjecture.  In any case, this fix/change has been working for at least 24 searches now on a clean install. I will submit a PR for testing.

**Comment by soundjester** [comment]
After doing some further research, this suggested change would clearly break several things downstream, not least of which would be docker compatibility (which I know you don't directly support).

**Current solution:**
It seems that the proper fix is to specifically indicate the database location using the --db switch during startup, even if that location is the default "watcher" directory path. It is _slightly_ concerning that the default location, i.e. not using the --db switch, doesn't work as expected.  However, as I have no immediate solution to that issue I'm going to shrug it off as ghosts in the machine (for now).

**Comment by soundjester** [comment]
I've left this open for visibility long enough, I think.

**Comment by nosmokingbandit** [comment]
Reopened. Sorry I'm so far behind.

I know *nothing* about docker, so I'll need some advice.

What I think will work is this, but I'm not sure:


```
    if passed_args.db:
        core.DB_FILE = passed_args.db
    else:
        core.DB_FILE = os.path.join(core.PROG_PATH, u'watcher.sqlite3')
```

This way docker users can still pass in whatever they want and it won't handle that any differently. But when not passing in a specific path it creates the absolute path for you.

I still can't recreate this problem for myself, which makes it really difficult to troubleshoot.

**Comment by soundjester** [comment]
I don't use docker, so that isn't (wasn't) the issue.  My "fix" would have impacted Docker (I think), and using the --db switch seems to have fixed my troubles.  I have not tried to launch Watcher without that tag recently, as it is a set-and-forget type of thing with the start-up script.

It may very well be the aforementioned ghost in the machine for me.  My theory was that the relative path got lost when called from an ajax subclass, which may be specific to python on FreeBSD.  Again, I don't know enough about this either to make an overly informed decision.  Which is also why I closed the issue.

**Comment by nosmokingbandit** [comment]
The main script sets the python working directory to the folder that contains watcher.py

I'm going to push that update anyway. It shouldn't hurt anything (in theory), but let me know if you can run it without the --db switch.

**Comment by soundjester** [comment]
Will do.
