### ISSUE TITLE
Bug: PreDB match in searcher.py is preventing newznab search

### ISSUE THREAD

**Issue by soundjester** [nosmokingbandit/watcher#152]
In commit [`9907fef` Better predb checks](https://github.com/nosmokingbandit/watcher/commit/9907feff2975fde4bc46169a20e9b66097b18498) on line 145-146, the predb check/match is preventing the call to the newznab search functionality for all movies in the 'Wanted' status.

**Comment by soundjester** [comment]
**_Adding context:_**
It appears that the goal behind this clause is to not send search requests for movies that do not have a listed media release date beyond a short window from today's date.  Generally speaking, this is a nice behavior, and helps eliminate unnecessary requests to the indexer.

Unfortunately some edge cases exist, particularly for some older movies or foreign language films which have no media release date for whatever reason.  In these cases, the query to the indexer will never fire, since they don't have a release date.

I'm not sure of the trade-off in performance between having the search fire for everything vs only those items that have a release date. For power-users who have over 50 movies in queue, that may be a real consideration.  However, one could also reasonably expect such users would have the appropriate hardware and indexer resources to be able to take the hit.  Perhaps a(nother) config setting would be an appropriate compromise.

**Comment by kirkyg** [comment]
This seems like the same issue posted as item #141  listed as indexer issues - can you confirm?

**Comment by soundjester** [comment]
It may be related, but I am not sure that it is the same. 

This specific issue completely prevents a search call to an indexer, whereas #141 seems to involve result parsing once the indexer search is called. The log will basically show a sidestep of the indexer call (well, more like an omission _see below_).  This specific issue is easily replicable.  Search for an old release that doesn't have an associated media release date and try to do a manual search (Try the a Three Stooges movie, for example).  Releases that have a release date _should_ search just fine (pending the outcome of #141).

**Comment by soundjester** [comment]
This issue has been addressed.
