### ISSUE TITLE
Post-Processing Sabnzbd TypeError

### ISSUE THREAD

**Issue by rickytin** [nosmokingbandit/watcher#153]
Sabnzbd TypeError: __init__() got an unexpected keyword argument 'timeout'

Any idea how to fix.

**Comment by zebner1** [comment]
I'm getting this same error. Were you able to resolve?

**Comment by rickytin** [comment]
No I still have the error, it is doing the Post-Processing and moving the movie but still show the error.

**Comment by nosmokingbandit** [comment]
This was fixed in https://github.com/nosmokingbandit/watcher/commit/71b9f0d0cac2dab90bbe3cc080cf41d65ba0459b.

Copy the new scripts over.

**Comment by zebner1** [comment]
Yup it worked for me now. Thanks!
