### ISSUE TITLE
Post Process Mover Fails

### ISSUE THREAD

**Issue by alazare619** [nosmokingbandit/watcher#157]
Mover fails to move the movie file

**Comment by vertigo235** [comment]
Possibly this ? https://github.com/nosmokingbandit/watcher/issues/142

**Comment by nosmokingbandit** [comment]
This has literally no useful information. Give me logs, an example... anything.

**Comment by alazare619** [comment]
ended up nuking the entire watcher install and rebuilding it with the docker appears to be working as of now.
