### ISSUE TITLE
latest update breaks watcher

### ISSUE THREAD

**Issue by vertigo235** [nosmokingbandit/watcher#159]
Traceback (most recent call last):
  File "/opt/watcher/app/lib/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/opt/watcher/app/lib/cherrypy/lib/encoding.py", line 220, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/opt/watcher/app/lib/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/opt/watcher/app/templates/status.py", line 48, in default
    self.movie_list()
  File "/opt/watcher/app/templates/status.py", line 90, in movie_list
    if data['score'] == 'N/A':
KeyError: 'score'

**Comment by Elfman72** [comment]
Yep.

It serves the login page, but clicking submit produces this error.

**Comment by vertigo235** [comment]
Exactly

**Comment by dancarroll** [comment]
Seeing this as well.  Looks like this commit changed the database schema, but didn't fully account for migration from previous versions: https://github.com/nosmokingbandit/watcher/commit/b51e98355d621d36422f4f5e6747332c2c6ca26b

I'm currently testing out Watcher, so hadn't migrated much of my data to it yet, so I blew away my existing database.sqlite and plan on manually re-adding items.  After deleting the old DB, I am able to get past the login to the main page.

**Comment by vertigo235** [comment]
OK I'll just wipe my DB then

**Comment by calebcall** [comment]
The upgrade automatically does a DB backup.  So look in the db directory and you should have a DB copy dated the say you upgraded.  I had to rollback to this DB to get mine working again.

**Comment by calebcall** [comment]
Just to clarify, there's a db directory in the watcher directory.  The live DB lives in the watcher directory, the backup is one directory deeper in the db directory.

**Comment by nosmokingbandit** [comment]
I'm not sure what happened here.

When updating the schema (which I hate to do and I hope I never need to again), it backs up your current db in watcher/db/ with today's date appended to the filename.

I'm not sure how it would update the schema without creating the 'score' column. I ran db update tests about 20 times before I pushed that update and I had no problems...

If anyone has a backup of a database that didn't migrate correctly send me a copy watcherznb@gmail.com

**Comment by vertigo235** [comment]
I was using the docker image did you test the process when using the command line option for the db like the docker image would be doing?

**Comment by nosmokingbandit** [comment]
I had not, but I just did and it worked fine.

**Comment by calebcall** [comment]
Ager rolling back and it fixed it.  I just tried to update again and it broke again.  Is there a way to increase the logging level?  Right now, the only thing I get is:

```INFO 2017-01-18 13:43:23,096 cherrypy.error.error: [18/Jan/2017:13:43:23] ENGINE Daemonized to PID: 20725
INFO 2017-01-18 13:43:23,099 cherrypy.error.error: [18/Jan/2017:13:43:23] ENGINE Started monitor thread '_TimeoutMonitor'.
INFO 2017-01-18 13:43:23,341 cherrypy.error.error: [18/Jan/2017:13:43:23] ENGINE Serving on http://0.0.0.0:8090
INFO 2017-01-18 13:43:23,342 cherrypy.error.error: [18/Jan/2017:13:43:23] ENGINE Bus STARTED
INFO 2017-01-18 13:43:46,127 cherrypy.error.error: [18/Jan/2017:13:43:46] ENGINE Started monitor thread 'Session cleanup'.
INFO 2017-01-18 13:44:49,098 core.sqldb.get_user_movies: Retreving list of user's movies.```

So it starts fine, then when I try to log in, it dies (the process complete dies off).  Nothing in the log, no errors, etc.  Everything appears fine.

**Comment by calebcall** [comment]
So, my database is migrating correctly (tables are all there) but I can't update to anything after `1e76c43` (I can update to this commit, but the next one that actually alters the DB schema breaks it). I can no longer login and upon trying to login the process crashes.  I even cloned a fresh copy of the repo in a new directory, started that one and I get the same results now.  

This is on OS X if that makes a difference.

**Comment by nosmokingbandit** [comment]
I just cloned a new copy on my mac and it worked fine. I didn't play around too much but I was able to search and add a movie with no trouble at all.

All logging happens either in your terminal window or in the log file. There is nothing else to log.

If something isn't working you should have an traceback in either your log or terminal screen.

**Comment by calebcall** [comment]
The process just dies, there is no traceback produced.

**Comment by calebcall** [comment]
If you would like, I can tar up a copy of my directory and send it to you.

**Comment by nosmokingbandit** [comment]
Yeah, go ahead and do that. I'd like to figure this out.

watchernzb@gmail.com

**Comment by calebcall** [comment]
Sent, let me know if you need anything else from me.
