### ISSUE TITLE
500 / ascii error

### ISSUE THREAD

**Issue by duckduckquack** [nosmokingbandit/watcher#16]
Added the movie Wall-E, got the following error... and honestly not sure how to get back to the status screen?

500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

`Traceback (most recent call last):
  File "/opt/watcher/lib/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/opt/watcher/lib/cherrypy/lib/encoding.py", line 220, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/opt/watcher/lib/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/opt/watcher/templates/status.py", line 32, in index
    self.movie_list()
  File "/opt/watcher/templates/status.py", line 52, in movie_list
    title_year = '{} {}'.format(data['title'], data['year'])
UnicodeEncodeError: 'ascii' codec can't encode character u'\xb7' in position 4: ordinal not in range(128)`

**Comment by duckduckquack** [comment]
I just found a [similar issue](https://github.com/rembo10/headphones/issues/2782) to this. Are there further logs I can send? I have verified my locale is `en_US.UTF-8 UTF-8`

**Comment by nosmokingbandit** [comment]
Unicode is a pain in the ass.

But commit https://github.com/nosmokingbandit/watcher/commit/6d682aacad37b21f965174b20d2bbcc993fbbf16 should have it working correctly. After updating you should be able to keep using Wall-E without any other changes.

**Comment by duckduckquack** [comment]
It appears to have worked. No errors when returning to the status page, and no errors navigating the gui.  Thanks!
