### ISSUE TITLE
FEATURE REQUEST: Call a script on completion

### ISSUE THREAD

**Issue by microSCOPED** [nosmokingbandit/watcher#161]
I would love to be able to call a script when a movie is found and downloaded - in my case the sickbeard_mp4_automator script.

Any plans for this?

**Comment by nosmokingbandit** [comment]
Extra post processing stuff like this is on the to-do list.

**Comment by nosmokingbandit** [comment]
This was added in https://github.com/nosmokingbandit/watcher/commit/27df3bf926c77bfaab9dcbb685fb2114ff0da762.

Check the wiki for instructions.
https://github.com/nosmokingbandit/watcher/wiki/Plugins

If you need specific help check out www.reddit.com/r/watcher and we'll help there.
