### ISSUE TITLE
JQuery error when searching: Cannot use 'in' operator to search for 'length' in Search Error.

### ISSUE THREAD

**Issue by dancarroll** [nosmokingbandit/watcher#164]
Updated to latest Watcher build today (version hash: d6ce824)

Initially ran into the problem detailed in https://github.com/nosmokingbandit/watcher/issues/159, and ended up deleting my DB since I was only tracking a few items.  Now, I'm able to access the Watcher UI, but I hit an error when attempting to add a new movie.

Search looks like its stuck (animation never disappears), and the browser console shows the error:
```
jquery.min.js:2 Uncaught TypeError: Cannot use 'in' operator to search for 'length' in Search Error.
    at w (jquery.min.js:2)
    at Function.each (jquery.min.js:2)
    at Object.<anonymous> (main.js?v=01.14:36)
    at i (jquery.min.js:2)
    at Object.fireWith [as resolveWith] (jquery.min.js:2)
    at A (jquery.min.js:4)
    at XMLHttpRequest.<anonymous> (jquery.min.js:4)
```

**Comment by nosmokingbandit** [comment]
I can't replicate this. Email me with the exact string you were searching for watchernzb@gmail.com
