### ISSUE TITLE
Search not working for some movies

### ISSUE THREAD

**Issue by Crowley007** [nosmokingbandit/watcher#165]
I get following errors in the log every time I press search:

`ERROR 2017-01-16 22:17:13,233 core.rss.predb.search_rss: PREDB search.
Traceback (most recent call last):
  File "C:\Git\watcher\core\rss\predb.py", line 82, in search_rss
    print results_xml
IOError: [Errno 9] Bad file descriptor
INFO 2017-01-16 22:17:13,237 core.sqldb.get_movie_details: Retreving details for **********.
INFO 2017-01-16 22:17:13,253 core.rss.predb.check_one: Checking predb.me for new available releases for ************
ERROR 2017-01-16 22:17:13,730 core.rss.predb.search_rss: PREDB search.
Traceback (most recent call last):
  File "C:\Git\watcher\core\rss\predb.py", line 82, in search_rss
    print results_xml
IOError: [Errno 9] Bad file descriptor`

**Comment by nosmokingbandit** [comment]
There have been some changes to that script today. Update and try again, let me know either way.

**Comment by Crowley007** [comment]
It has been fixed for the same movie that failed previously.
