### ISSUE TITLE
Prevent Git windows from showing up when updating?

### ISSUE THREAD

**Issue by Flippage** [nosmokingbandit/watcher#167]
#### What happened?
When Watcher updates, git windows popup on the primary display, which I also use as my Media Player, so the git windows pop-up on top of my media while I'm watching.

#### What was supposed to happen?
Ideally, I'd like to make the git windows open minimised, or not open at all (silently, like running python as a daemon)
 
#### How can I reproduce this?
Watch the display when you're doing a Watcher update. There are about 3 or 4 windows that popup. Sometimes when I'm watching a movie i'll see the git windows pop up all over the place.

Not saying that this is the fault of Watcher, I am just hoping someone on here can tell me how to make the Git windows hidden? My Google-fu is failing me.

**Comment by nosmokingbandit** [comment]
You must be running this as a daemon in windows?

I'll check the git documentation, there should be a way to run git in quiet mode.

I never run it in daemon mode since I need to restart a lot to test things so I never saw this before.

**Comment by nosmokingbandit** [comment]
Fixed in commit https://github.com/nosmokingbandit/watcher/commit/38c7419fd57acd6b3ae062c3e5253f658f26b7cf

**Comment by Flippage** [comment]
Awesome. Thanks man! I had removed GIT because it was getting annoying, and then I was getting errors every time I clicked something in Watcher. I think Watcher tries to check for a new version every time you change sections, like if I click on "Settings > Server" I get the notification, then if I click "Settings > Quality" it comes up with the same notification.

It's an error saying "File could not be found" or something along those lines. I understand the error message, but maybe make it popup once and then stay hidden. Mostly because of it's location on screen, the notification covers the "Save settings" button, or other parts of the UI.

Either way, I have GIT reinstalled, and I'll let you know if there's any issues with the change you've made.

Thanks for looking into that for me :+1:

**Comment by nosmokingbandit** [comment]
The update failure notifications don't completely clear themselves. This started out as a bug but I left it because it seemed good to have a constant reminder that something important isn't working.

**Comment by Flippage** [comment]
Ok. Is there a plan to move the notification bubbles to somewhere else? Right now it covers at least 1 thing on every page it pops up on.

So you'd have to wait for it to disappear before you can click on whatever is underneath the message.

Just a thought to consider :)

**Comment by nosmokingbandit** [comment]
I think about it on occasion, but usually when I'm working on other, more important things. I'm sure I'll remember it some day.
