### ISSUE TITLE
Send single nzb results in 4 requests for same file to downloader

### ISSUE THREAD

**Issue by kirkyg** [nosmokingbandit/watcher#168]
I found an issue with sending to downloader (sabnzbd); multiples (seems to be exactly 4) of the same nzb requests were sent when only manually selecting one nzb to send to the downloader.  I tested this with the same indexer multiple different nzb's (since my other one isn't currently working) with same result.

To reproduce this simply add a movie to your watch list (or use one that is already in your watch list) select the movie, manually click the search icon if results aren't shown and click the download link.

The following snipet from the logs show the first few traces when this action was taken to send to downloader and as you can see there are four threads sent.  PM me if you need additional info/log details:

INFO 2017-01-16 22:15:23,602 core.sqldb.get_single_search_result: Retreving search result details for https://www.pfmonkey.com/getnzb/2b6475274a6b967f7aeebb842baab11e.nzb&i=9159&r=APIKEY.
INFO 2017-01-16 22:15:23,608 core.sqldb.get_single_search_result: Retreving search result details for https://www.pfmonkey.com/getnzb/2b6475274a6b967f7aeebb842baab11e.nzb&i=9159&r=APIKEY.
INFO 2017-01-16 22:15:23,609 core.sqldb.get_single_search_result: Retreving search result details for https://www.pfmonkey.com/getnzb/2b6475274a6b967f7aeebb842baab11e.nzb&i=9159&r=APIKEY.
INFO 2017-01-16 22:15:23,611 core.sqldb.get_single_search_result: Retreving search result details for https://www.pfmonkey.com/getnzb/2b6475274a6b967f7aeebb842baab11e.nzb&i=9159&r=APIKEY.
INFO 2017-01-16 22:15:23,640 core.snatcher.snatch: Sending nzb to Sabnzbd.
INFO 2017-01-16 22:15:23,640 core.snatcher.snatch: Sending nzb to Sabnzbd.
INFO 2017-01-16 22:15:23,640 core.snatcher.snatch: Sending nzb to Sabnzbd.
INFO 2017-01-16 22:15:23,640 core.snatcher.snatch: Sending nzb to Sabnzbd.

Thanks!

**Comment by TheRealShiz** [comment]
I've had this happen a couple times where it added two of the same nzb (never more than that).  Could never reliably reproduce.

**Comment by nosmokingbandit** [comment]
Does this only happen with pfmonkey?

**Comment by nosmokingbandit** [comment]
Fixed in cd9da16fd7fa9dc1b4a0d51ef86d3ddad3803e64

The click handle was being re-assigned every time the slide-up panel was opened. So if you open one movie and click Download you'll get one nzb.

Close it, open it again and you'll get 2 NZBs per click.

Do it again. 3 NZBs.

It should be fixed now.
