### ISSUE TITLE
Won't start up - Ubuntu server

### ISSUE THREAD

**Issue by infinitepi** [nosmokingbandit/watcher#17]
I've not been able to start watcher after cloning.  
running on a headless ubuntu server
```
mediagrabber:~/.watcher$ python watcher.py
Traceback (most recent call last):
  File "watcher.py", line 13, in <module>
    from cherrypy.process.plugins import Daemonizer
ImportError: No module named process.plugins

```

**Comment by nosmokingbandit** [comment]
What version of python are you using?

Can you try deleting the folder and re-cloning?

Look in watcher/lib/cherrypy/ and see if there is a process folder. If that is missing something didn't clone correctly.

**Comment by blackhawkpr** [comment]
I'm having the same issue on 16.10. Python version is 2.7.12 and the process folder is there.

**Comment by infinitepi** [comment]
Python 2.7.10
deleted and re-clooned, same issue.

i do have a process folder, which contians:
__init__.py
plugins.py
servers.py
win32.py
wspbus.py

**Comment by nosmokingbandit** [comment]
Do you happen to have cherrypy installed through pip? It might be trying to import that before it imports the copy in watcher/lib.

**Comment by infinitepi** [comment]
i do not know what pip is, but i can say i never manually installed anything to do with python or cherrypy.
any time i'm installing things it's via apt or git

**Comment by blackhawkpr** [comment]
I installed cherrypy and I guess something progressed but new errors have arisen. 

"python watcher.py --port 9191   /opt/watcher/lib/fuzzywuzzy/fuzz.py:35: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')
Config file found, merging any new options.
Database found.
Traceback (most recent call last):
  File "watcher.py", line 152, in <module>
    api.API.conf
TypeError: mount() takes at most 4 arguments (5 given)"

Don't know how to format on mobile.

**Comment by soundjester** [comment]
@blackhawkpr You need to grab the latest update and the `TypeError: mount() takes at most 4 arguments (5 given)"` message will be resolved (see #22).

**Comment by blackhawkpr** [comment]
@soundjester Thanks. 

Deleted the whole folder since I'm a noob when it comes to hit and re-cloned it. Ran it and it works so far.

Now gotta figure out how to configure it.

**Comment by infinitepi** [comment]
tried to install cherrypy as suggested by blackhawkpr, but it wouldn't go....
>mediagrabber:~/cherrypy$ python setup.py install
>Traceback (most recent call last):
>  File "setup.py", line 5, in <module>
>    import setuptools
>ImportError: No module named setuptools

not sure this is even necessary, but figured i'd give it a go...

**Comment by blackhawkpr** [comment]
Try without the $'s in the code. I just directly copied that from the cherrypy website.

**Comment by infinitepi** [comment]
it's not a part of the command, that's my prompt... :)

**Comment by blackhawkpr** [comment]
I don't know about that then. It installed without a problem on my end.

**Comment by infinitepi** [comment]
a quick search turns up directories named "cherrypy" in /opt/Mylar/, /opt/headphones/,  /usr/lib/pymodules/python2.7/, /usr/share/pyshared/, & /usr/share/sabnzbdplus/

not sure if it's helpful, but there it is... ;)

**Comment by nosmokingbandit** [comment]
Ok, so this got a little messy. Is it working as intended at the moment? It should be importing cherrypy from watcher/lib before looking anywhere else, so you really shouldn't have to install cherrypy by itself.

If you really want to install Cherrypy you need [setuptools](https://pypi.python.org/pypi/setuptools)

You should actually just be able to run `$ pip install setuptools`

Let me know what your current situation is so I know what I need to do.

**Comment by blackhawkpr** [comment]
In my case, I tried to install setuptools and it said I already had it installed. All I needed to do was upgrade it. I guess it was installed with one of the other Usenet or Plex apps

**Comment by infinitepi** [comment]
no change.
>Traceback (most recent call last):
>  File "./watcher.py", line 14, in <module>
 >   from cherrypy.process.plugins import Daemonizer
>ImportError: No module named process.plugins

i did not install cherrypy

**Comment by nosmokingbandit** [comment]
I'll have to download ubuntu and try this for myself. It runs fine on Arch and Windows 10 (my main testing platforms), so this is really weird to me.

**Comment by nosmokingbandit** [comment]
So I just downloaded an image of 16.10 from osboxes.org, loaded it up in vmware, and cloned watcher in it.

Everything works perfectly.

Are you executing `python watcher.py` or `./watcher.py` ?

If you were using `./watcher.py` grab the latest commit https://github.com/nosmokingbandit/watcher/commit/08a8ca9995e6ebf21c1f42d09ab35f4e1bcd243a and try again.

It is always good practice to execute `python script.py`, but this should take care of your problems.

Please report back.

**Comment by infinitepi** [comment]
hmm, pulled the update from git, still having the same trouble.  
running with python watcher.py, still getting the same error

**Comment by nosmokingbandit** [comment]
Run this and post the output.

`python -c "import sys, pprint; pprint.pprint(sys.path)"`

**Comment by infinitepi** [comment]
> $ python -c "import sys, pprint; pprint.pprint(sys.path)"
> ['',
>  '/usr/lib/python2.7',
>  '/usr/lib/python2.7/plat-x86_64-linux-gnu',
>  '/usr/lib/python2.7/lib-tk',
>  '/usr/lib/python2.7/lib-old',
>  '/usr/lib/python2.7/lib-dynload',
>  '/home/ryan/.local/lib/python2.7/site-packages',
>  '/usr/local/lib/python2.7/dist-packages',
>  '/usr/lib/python2.7/dist-packages',
>  '/usr/lib/pymodules/python2.7']

**Comment by nosmokingbandit** [comment]
That looks perfectly normal. Which is odd.

Try this for me

`pip uninstall cherrypy`

or if that says cherrypy isn't installed try

`pip uninstall python-cherrypy`

**Comment by infinitepi** [comment]
can't seem to uninstall via either method....

```
$ pip uninstall cherrypy
Not uninstalling CherryPy at /usr/lib/pymodules/python2.7, owned by OS
$ pip uninstall python-cherrypy
Cannot uninstall requirement python-cherrypy, not installed
Storing debug log for failure in /home/xxxx/.pip/pip.log
```
Contents of pip.log:
```
Cannot uninstall requirement python-cherrypy, not installed
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/uninstall.py", line 59, in run
    requirement_set.uninstall(auto_confirm=options.yes)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1036, in uninstall
    req.uninstall(auto_confirm=auto_confirm)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 506, in uninstall
    raise UninstallationError("Cannot uninstall requirement %s, not installed" % (self.name,))
UninstallationError: Cannot uninstall requirement python-cherrypy, not installed
```

**Comment by nosmokingbandit** [comment]
It looks like, for whatever reason, your install os ubuntu came with cherrypy, but perhaps an older version.

Try running this:

`sudo pip install cherrypy --upgrade`

**Comment by infinitepi** [comment]
woo hoo!  that got it! 
hope my struggle can help you build in a check for the version?

**Comment by nosmokingbandit** [comment]
...maybe.

Unfortunately I can't have you help test a fix since everything works for you now. I was mistaken about the order in which python looks for modules. I changed the order in a test commit I'm working on -- In theory it should fix it permanently.
