### ISSUE TITLE
Issue with access to program

### ISSUE THREAD

**Issue by veritas2884** [nosmokingbandit/watcher#170]
#### What happened?
Cannot connect to web interface
#### How can I reproduce this?
Every time I try to run the program and connect.

I must stress I am a linux newbi and apologize if I am missing something obvious. It seems like there are a lot of errors in the log, but I do not know what they indicate is wrong.

Thank you for any help!

[log.txt](https://github.com/nosmokingbandit/watcher/files/711913/log.txt)

Including logs of the event are often neccessary to find out exactly what is going on.
If the log section is short feel free to post is here, but make sure to remove any personal information (ie IP address) and remove any references to movie or release titles.
If the logs are long, or require release title names to troubleshoot, submit an issue here, then send the logs to watchernzb@gmail.com.
Put a link to your issue in the email body so we know exactly who it belongs to.

**Comment by Elfman72** [comment]
Try editing your config manually and changing 127.0.0.1:9090 to 0.0.0.0:9090

**Comment by nosmokingbandit** [comment]
Closing to do lack of response from OP.

127.0.0.1 allows access from the same machine. 0.0.0.0 allows access from other ips.
