### ISSUE TITLE
FEATURE REQUEST: JSON List Import

### ISSUE THREAD

**Issue by ThisNerdyGuy** [nosmokingbandit/watcher#172]
Hello! 

Absolutely loving the simplicity of Watcher and love the light-weight feel that is being accomplished here! 

Understanding that development is not wanting to re-invent CP, but wants to focus on quickly obtaining and post-processing media - I request - 

The ability to integrate a JSON list. 

Within CP, I loved running the Popular Movies script (https://github.com/sjlu/popular-movies) and rarely had to manually add a movie. 

I have less than zero development experience so I have no idea if this is possible. Just throwing the idea out there. 

This feature request notwithstanding - absolutely fantastic work!

**Comment by Technifocal** [comment]
Under the assumption the pull request I made above is declined, you can always make a small program that calls the API of Watcher with the imdbids from the popular movie JSON.

If my pull request gets declined, I'll make one and post it here, because I'm actually genuinely interested in how well this popular-movies setup works, and I'd rather run on the main branch of this program, rather than my own fork.

**Comment by nosmokingbandit** [comment]
I finally got back to this request and I was about to close it.

However, are there other lists like this people generally use? I can add more integration options if I know what sources I'm working with.

If all you cared about was the Popular Movies list I'll just close this.

**Comment by ThisNerdyGuy** [comment]
nosmokingbandit - that is the one list that I primarily use. 

However, I am fully updated and your statement "I was about to close it" makes me think that you've implemented my request. 

Yet I am not seeing it. Am I overlooking the feature somewhere? Or is it being outright denied?

**Comment by Technifocal** [comment]
@ThisNerdyGuy `/settings/search/` -> `Watchlists` -> `Sync Popular Movies list at` -> Restart

**Comment by ThisNerdyGuy** [comment]
@Technifocal Wow! If that were a snake, huh? 

Thank you VERY much for pointing that out and thank YOU VERY much @nosmokingbandit for adding this! 
Schwiiiiing!
