### ISSUE TITLE
FEATURE REQUEST: Sort by DVD release date

### ISSUE THREAD

**Issue by nuentes** [nosmokingbandit/watcher#173]
I was told in #154 that "If the movie in question is a new-ish release (e.g. still in or semi-recently out of theaters) and either does not have a DVD release date, or has a DVD release date beyond the next several days, the query from Watcher will not fire."

I'd like for this value to be displayed in the List view, and be sortable. This way I can find movies that SHOULD have a release, and manually search if I deem it necessary.

So I'd imagine the "Order by" list having the following options:

- Status
- Title
- Theatrical Release Date
- DVD Release Date

**Comment by soundjester** [comment]
I was a bit wrong about that, btw.  Media release date is only tangentially important. The main controller is PreDB and whether or not a reasonable title match for the release is found there.

That said, having a way to view a potential/general time frame for an expected release would be nice to have, even if it isn't sortable.  OMDB has it some of the time, and the date used to be there prior to TMDB integration.  It may be possible to add it back to the display.

**Comment by nosmokingbandit** [comment]
I only put in a dvd release date because omdb supplied it. I don't actually use it for anything since digital releases are often *way* earlier.

After I changed the search method I don't store dvd release date at all any more.

I plan on adding more sort options soon, but dvd release date won't be among them.
