### ISSUE TITLE
Feature Request: Custom Qualities

### ISSUE THREAD

**Issue by Quiksmage** [nosmokingbandit/watcher#175]
I would like to request the ability to have custom Qualities and the ability to define them.

For instance, I would like to mark HDcam, HD-TS, CAM, HDTS, TS, TELESYNC, HQHDT as a CAM quality.

or the ability to add a golden popcorn quality in the case of passthepopcorn.

I find that in Couchpotato, Cams can often get marked as BRRIP. I would like more ability to control what gets marked as what for better processing.

**Comment by soundjester** [comment]
duplicate: #35

**Comment by Quiksmage** [comment]
It looks to be different than that request to me. Their request is to have different quality profiles like there currently are in couchpotato, but mine is that I want to define qualities themselves.

I want to be able to decide what gets categorized as BR-Rip, Screener, R5, etc based on its processing of the file name.

For instance,

Cam: HDcam, HD-TS, CAM, HDTS, TS, TELESYNC, HQHDT
Screener: DVDScr 
WEB-DL: WEBRip, HDRip, WEB-DL,
DVD: DVDRip, DVD,
BR-Rip: BR-Rip, BRRip

Does this further clarify what I'm asking for you? If not, I can try further.

I know this isn't Couchpotato, and you currently only have 4k, 1080p, 720p, SD, but I'd like the ability to define what everything gets classified as beyond size of the file, if possible.

Thanks for taking on such a huge project. I hope it takes off and becomes the new defacto movie downloader :).

**Comment by soundjester** [comment]
Seems pretty similar, e.g. the ability to define keywords associated with a specific profile. #35 was referencing language, but if you have to add one customizable keyword, might as well add functionality to accommodate anything.

Anyway, your explanation is good and adds some depth.

**Comment by Quiksmage** [comment]
Thanks, I understand your point now with the language reference. I'll add my additional information to that post :)

**Comment by nosmokingbandit** [comment]
The problem with this is that you are mixing resolutions and sources. Semantically this is a flaky way to filter any results. 

If you want to restrict a movie to a screener just add 'DVDScr' to its required words.

**Comment by Quiksmage** [comment]
It's not about restricting a specific movie to a type. It's about automatic downloading and how sources get filtered into qualities.

For instance, I have movie X

when X comes out, the first quality available will be CAM
The application will download this and put it in the proper folder.
After this, usually a WEB-DL will come out.
The application will download this and delete the old CAM and replace it with WEB-DL updating the current highest version as WEB-DL.
This process continues until it gets to your final quality, whichever you specify.
See the below image
http://i.imgur.com/3U6pkCI.png
The goal is to end on 1080p BluRay in this case.

The reason I'd want to customize this is because couchpotato currently has a problem with classifying sources properly. I'll find that WEB-DL's get put in as BR-Rip and i've seen cams get classified as 720p or BR-Rip. It's all a mess currently in that sense and that is what I'd like to rectify.

**Comment by soundjester** [comment]
That is an interesting take on it. 

Being able to group keywords with resolutions, while not semantically ideal, is sort of the devil's bargain with NZBs and torrents, as you could, theoretically, have the same listed resolution and a similar file size, but a different source.  Having user-defined profiles that are ordered/scored according to desirability would necessarily need to include some keywords that do not relate specifically to resolution.

Just talking/thinking about it makes it clear that this is something that is developmentally complex... Perhaps this is why custom keywords are generally not integrated into profiles.  TV auto-downloaders generally couple resolution with specific keywords (720p HDTV, 720p Web-DL, etc), but to the best of my knowledge, they are hard-coded and not user editable.

**Comment by Quiksmage** [comment]
you are correct, that every downloader has it hard coded currently with no way of editing. I think the biggest issue with movie downloaders, in this instance, is that there are too many naming conventions. tv is quite standard.

if they won't be user editable, I understand, but I'd certainly at least want to make it so lower qualities don't get detected as higher qualities. files marked as 720p or 1080p cams, screeners, and web-dls tend to be the issue. I don't tend to want cams, so I generally filter them out, but I assume there's someone out there that does. my beginning quality is usually the korsub/webdl releases as they're usually high quality, followed by bluray releases. I understand that this may not be implemented, but I'd like it to be recognized :)

**Comment by soundjester** [comment]
Yeah, I was also wondering about fragmentation as it related to naming conventions for movies (vs. TV).

My downloading style aligns well with yours. The way I have things set up currently, I exclude Cams, screeners, and telesyncs using keywords you have already mentioned, and have the 1080p filesize threshold low enough to pick up Web-DLs when they hit.

In my preferred keywords, I have several variations of bluray listed, so that when those show up, they score higher. I also set my upper bound on 1080p/4K file size to be pretty high. Far higher than the default values.

Finally, I have the "continue searching days" field set for 20 days, which seems to adequately bridge the gap between a digital release and a physical one, accommodating the well respected release groups.

So far, this has seemed to work.  I have the mover/renamer script create a subfolder according to `{source}` so that I (hopefully) avoid collisions at the file name level.

**Comment by Quiksmage** [comment]
I do the same as you, mentioned as above. The main reason I created this request would be to prevent the need to set it up as we do, I guess. I also wanted the ability to expand upon it further down the line to possibly include cams. it feels like what we do in couch potato is a dirty fix although it works well for what we currently use it as :)

**Comment by nosmokingbandit** [comment]
Custom profiles is on the table. Torrent support is implemented, so after I hit a bunch of bugfixes this will be next. Or next-ish.

**Comment by Quiksmage** [comment]
profiles were added, but not the meat of what I requested, so I'll reopen this one for now. if there is no intention to add this feature, I could request the qualities to be done on the backend if you don't want them to be user customizable. If neither of those options work, we can close this again. In any case, thank you for the continued development of this project.

**Comment by nosmokingbandit** [comment]
I don't think I understand what you are trying to do. The only way to know what a source a release comes from (ie BRRip, webrip, cam) is by reading the title. So if you don't want these sources simply add them to the ignored words in your desired quality profile.

Couchpotato treats sources and resolutions as the same thing, which makes no sense at all. Trying to make Watcher work like Couchpotato isn't going to get you anywhere.

**Comment by Quiksmage** [comment]
Hi, I don't mean to try to keep comparing to couchpotato. Maybe I am misunderstanding the intended eventual function of watcher.

I'm not trying to ignore specific types on specific movies. That's what a profile is for, you are correct.

I am comparing to Couchpotato in the following manner.

in Couchpotato, you can set set up a quality profile, where you dictate the quality priority for releases.
See this image for example: http://i.imgur.com/KSXOep5.png

I have it searching for different types of media based on its title.

In this instance, it starts with r5 and doesn't stop searching till it has found 1080p BluRay.

To the best of my knowledge, Watcher currently bases the quality of a file entirely based on its size.
Keywords seem to be the best way to dictate what an item is, not necessarily its size, unless all you're searching for is 1 type of quality.

I understand that mixing resolutions and types doesn't make sense in the way couchpotato does it, that's why i'd like to refine it.

For instance, instead of 1080p, we could have 1080p BluRay.

Is there currently a way in watcher to have a movie automatically download specific types of a movie up to a desired final quality at which point it stops?

Currently, you have resolution priorities, but I am asking it to be switched to type priorities where you can dictate what types of search for.

For instance, starting at a cam quality and ending on a golden popcorn release from PTP.

That is what my request entails. If there is no intention of adding this type of functionality, I have no problem with closing this request nor am I trying to step on anyone's toes as that is functionality of couchpotato I'd require to switch to watcher full time. 

Thanks for considering my request :)

**Comment by Quiksmage** [comment]
To refine my request further,

You currently have resolutions with size restrictions.

It would be nice to be able to add resolutions with ignored and required keywords on each resolution.

for instance,

1080p 
required words: Blu-Ray, BluRay

1080p
required words: HC.HDRip,
ignored words: BluRay, Blu-Ray

This requires the ability to add a resolution multiple types as well as add required/ignored words for each resolution type.

a profile like this would search for both 1080p WEB-DL and 1080p BluRay, with it stopping its search after finding 1080p BluRay. Does this further clarify what I'm asking for?

**Comment by nosmokingbandit** [comment]
Early on in development (*really* early) I had a section in the Quality config that would allow you to prioritize sources as well as resolutions. So to follow your example, I would prioritize BluRay > HDRip >Webrip > etc, which should get the results you desire.

I'm not sure why I removed it, but I'm going to look at adding that back in.

**Comment by Quiksmage** [comment]
Sounds good :) Thanks for looking into this.

**Comment by nosmokingbandit** [comment]
FYI, this was a whole lot easier to do than I thought, so I decided to switch some of the html generation from after the ajax response in javascript to part of the ajax handling method on the server. This took twice as long as actually adding this feature.

This tells me two things I already know.
* Python is amazing and I'm getting pretty good at it.
* Javascript is the worst language I've ever had to work with.

So here is a little teaser:
http://imgur.com/a/bDsQ0

It is set up a bit more like Sonarr, where you have pick size restrictions based on resolution *and* source material, then you can enable and set priority for each source in each quality. I should have done it this way to begin with, but Watcher started out as an experiment that kind of worked so I just kept adding to it.

**Comment by Quiksmage** [comment]
Hey man, that looks great! If I may ask. can you list what words are used to detect each source? And if possible, can we have these words use editable in advanced settings? It would help for troubleshooting in the future for sure, thanks!

**Comment by nosmokingbandit** [comment]
I just pushed this out, commit 3007c9e3e1046d89da9ba8bc34740a99a5e74b73.

You can customize what consists of a BluRay release (ie 'bluray, blu-ray, blueray'), so it is pretty flexible.

**Comment by Quiksmage** [comment]
You have NO IDEA how moist you have made me :)
http://i.imgur.com/itaHlZu.png

You have literally added exactly what I wanted while improving on what couchpotato is lacking (user editable sources). 

I LOVE YOU :P

**Comment by nosmokingbandit** [comment]
I need an adult.


And I'm closing this ;)

**Comment by Quiksmage** [comment]
The only thing I'd change or add is that cams can be in 720p or 1080p. I'm not sure how you made the resolutions mix here. will "CAM-SD" grab any item with "cam, camrip" or will it specify a resolution in there as well.
