### ISSUE TITLE
Keyerror:'status' error for SABNZbd post process.

### ISSUE THREAD

**Issue by Elfman72** [nosmokingbandit/watcher#176]
Grabbed the latest sabnzbd.py script for post processing.  Edited it for my environment.  Watcher sends to SAB just fine.  When SAB is done, it attempts to run this script but fails with the following message:

```
Sending NAMEREMOVED.Watcher to Watcher as Complete.
Traceback (most recent call last):
  File "/config/scripts/sabnzbd.py", line 70, in <module>
    if response['status'] == 'finished':
KeyError: 'status'
```

This is the error that SAB returns.

I am running the latest on all, including the newly released 1.2.0 version of SAB.  There are no log entries since it appears that it is the script failing as opposed to Watcher erroring.  Needless to say, the file does not get renamed or moved.

**Comment by nosmokingbandit** [comment]
Watcher should have a log of that post-processing request. Can you send it to me at watchernzb@gmail.com

**Comment by Elfman72** [comment]
Update to this.  As of the latest script, this appears to be working now in at least that SAB is running the script and sending a successful status back to Watcher.  Now I just need to get it to move the files.  I think my naming might be to blame here.  Again, running in a docker package, my paths are in variables.  I'll play with it and open a new issue if I can't get it to work.  Thanks!

**Comment by nosmokingbandit** [comment]
Cool beans. I'm going to close this then.

Docker's paths confuse the daylight out of me. I've honestly never put much effort into figuring it out.
My main media server has an aarm64 cpu, so there are very few pre-built containers for that architecture. I don't even keep Docker installed any more.
