### ISSUE TITLE
Missing css file in Dark-jester

### ISSUE THREAD

**Issue by calebcall** [nosmokingbandit/watcher#177]
The following file is missing in the Dark-Jester theme.

/watcher/static/css/Dark-Soundjester/movie_status_popup.css

**Comment by soundjester** [comment]
It isn't needed... unless you are seeing an odd color or something?

**Comment by calebcall** [comment]
Nothing odd other than it's trying to access it and throwing a 404 when looking in Developer tools.

**Comment by soundjester** [comment]
What version are you on?  There was an old version that had an `@import` statement, but that went out a while ago.

**Comment by calebcall** [comment]
The most recent, just updated within the hour.

It looks like in templates/status.py, there's the following line:

```
link(rel='stylesheet', href=core.URL_BASE + '/static/css/{}/movie_status_popup.css'.format(core.CONFIG['Server']['theme']))
```

So, not sure how Dark-Soundjester wouldn't try and pull that file even if it doesn't use it.

**Comment by soundjester** [comment]
Ah, I see it.  Hmm.  It would just be an empty file. No specific CSS is needed or differs fro m the base CSS classes..

**Comment by soundjester** [comment]
PR issued.

**Comment by nosmokingbandit** [comment]
Merged with master branch https://github.com/nosmokingbandit/watcher/commit/0ce79ca5be8fad432f6a10b4f58541e8577f00de
