### ISSUE TITLE
Base URL/webroot doesn't seem to work

### ISSUE THREAD

**Issue by Cook66** [nosmokingbandit/watcher#179]
Having a problem? Bummer. Watcher is under constant development, so bear with us while we sort this out.

Meanwhile, you can help us get this fixed more quickly by following this format:

#### What happened?
Tried using Base URL to use watcher on localhost:9090/watcher
Set it in config.cfg under Proxy->webroot  and core/__init__.py  as URL_BASE.

When starting the browser on startup with --browser it loads the URL set, but it gives a 404 and the webserver answers calls like it always does.

#### What was supposed to happen?
All URLs of the app should be nested under the webroot set, but they seem to be hardcoded or something.

#### How can I reproduce this?
Alter line 16 on core/__init__.py

I'd really love to have this feature work. I can if I have to try to fix it myself, but I haven't worked with Cherrypy before.

**Comment by calebcall** [comment]
Why are you alerting init.py?  All you should need to do is set behindproxy = true and set your webroot path in the config file.  Then restart and you're done.  I'm using /watcher as mine and it works fine.

**Comment by Cook66** [comment]
Thanks!

**Comment by nosmokingbandit** [comment]
*Always* check the wiki.

At least that is what my mama taught me.
