### ISSUE TITLE
Post Process Notifications

### ISSUE THREAD

**Issue by Mochaka** [nosmokingbandit/watcher#18]
Ability to notify services once a movie has been processed? Like Plex/Kodi or Growl/Prowl.

if you make a plugin system for notifications, i'll help make plugins.

**Comment by nosmokingbandit** [comment]
I planned on doing this at some point, but I want to get the core problems straightened out first. I'll leave this issue open until I get to it then I'll get your help.

It should be relatively easy, but for now we'll shelve it.

**Comment by nosmokingbandit** [comment]
Added in https://github.com/nosmokingbandit/watcher/commit/73e2ed01548d32db97b1868482c1cc1d653cfb63.

Check the wiki for more explanation.

https://github.com/nosmokingbandit/watcher/wiki/Plugins
