### ISSUE TITLE
PREDB search. Traceback (most recent call last):

### ISSUE THREAD

**Issue by averagecdn** [nosmokingbandit/watcher#180]
#### What happened?

No search results when clicking to search

#### What was supposed to happen?

Search for movie

#### How can I reproduce this?

####Log Files####

INFO 2017-01-19 14:37:42,320 core.rss.predb.check_one: Checking predb.me for new available releases for Bleed for This.
ERROR 2017-01-19 14:37:42,385 core.rss.predb.search_rss: PREDB search.
Traceback (most recent call last):
  File "/Users/mark/Downloads/watcher/core/rss/predb.py", line 81, in search_rss
    results_xml = urllib2.urlopen(request).read().replace('&', '%26')
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1240, in https_open
    context=self._context)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1197, in do_open
    raise URLError(err)
URLError: <urlopen error [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:590)>
INFO 2017-01-19 14:37:42,386 core.sqldb.get_movie_details: Retreving details for tt1620935.
INFO 2017-01-19 14:37:42,404 core.sqldb.get_search_results: Retreving Search Results for tt1620935.
INFO 2017-01-19 14:37:42,412 core.sqldb.get_user_movies: Retreving list of user's movies.
INFO 2017-01-19 14:37:42,925 core.sqldb.get_movie_details: Retreving details for tt1620935.

**Comment by averagecdn** [comment]
Python version is above required level.

**Comment by nosmokingbandit** [comment]
If the version is too low I'm surprised it got past line 23 in watcher.py

```
ssl._create_default_https_context = ssl._create_unverified_context
```

When you start python in a terminal, what does it say in the first line?
`
Python 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:19:22) [MSC v.1500 32 bit (Intel)] on win32
`

**Comment by averagecdn** [comment]
Python 2.7.10 (default, Jul 30 2016, 19:40:32) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>>

**Comment by nosmokingbandit** [comment]
Does this problem persist? I can't seem to find any reason it should happen unless predb just happened to be down when that request was made.

**Comment by averagecdn** [comment]
I have just deleted and recloned from the GIT source, resetup integration to SAB, and added one search provider and searched a movie and immediately (no delay) with no results.

**Comment by nosmokingbandit** [comment]
Does the log still show the ssl handshake error?

**Comment by averagecdn** [comment]
You must have done something in the recent commits because i am not getting the error any longer.

**Comment by nosmokingbandit** [comment]
I don't think I did, but I'll take the win regardless.

**Comment by calebcall** [comment]
I see this error on mine with the most recent commit.  I've seen this for a while and have just always changed watcher/core/rss/predb.py and changed https://predb.me to http://predb.me.  Python version is above the minimum:

Python 2.7.10 (default, Jul 30 2016, 19:40:32) 

Since it shouldn't be sending anything sensitive to predb, I don't care about changing it to non-ssl.  Just figured I'd mention it since this has popped-up a couple times.
