### ISSUE TITLE
Add popular movies list in addition to imdb watchlists.

### ISSUE THREAD

**Issue by vladware** [nosmokingbandit/watcher#182]
Possible to integrate the popular movies list provided by the below.

https://github.com/sjlu/popular-movies

There's a json feed available: https://s3.amazonaws.com/popular-movies/movies.json

**Comment by ywLBhGk2noZLbY7** [comment]
Worth checking with @sjlu if that domain is acceptable for mass public use, as I'm not sure on the S3 pricing model.

**Comment by sjlu** [comment]
Free to use it, costs are minimal.

**Comment by Technifocal** [comment]
I've managed to get this working locally based on the code in `./core/rss/imdb.py` and I will make a pull request soon.

I do have some issues, which will have to be addressed by @nosmokingbandit when I make the request though, but so far so good.

**Comment by nosmokingbandit** [comment]
Added in 5413a7f666558288e9ffc5c0e5591c29e0fc3d0a.

Syncs once a day, since anything more frequent won't do any good.
