### ISSUE TITLE
PreDB can't match for titles with a colon and possibly a hyphen

### ISSUE THREAD

**Issue by TheRealShiz** [nosmokingbandit/watcher#183]
Having a problem? Bummer. Watcher is under constant development, so bear with us while we sort this out.

Meanwhile, you can help us get this fixed more quickly by following this format:

#### What happened?
Added a movie with both a colon and a hyphen in the name.  Hint: contains a character with a name rhyming with Har Har Dinks.  No results returned.

#### What was supposed to happen?
I was supposed to get results

#### How can I reproduce this?
Do what I did

It seems the PreDB search is failing.  At least when I do it myself I had to remove both the colon and the hyphen to get search results from PreDB.  I assume that this failure is what is never firing the calls to the indexers which results in 0 results.  Logging is bad for this type of event.  No idea that the failure has occurred yet I never see a call go out to the indexers either.

**Comment by nosmokingbandit** [comment]
Both the colon and hyphen caused a null result.

I can confirm it is fixed in cedc45dac3e3da026c279b78f23eb11a19e93398. There may be more characters that break it, so keep me posted. For now I'm calling this closed.
