### ISSUE TITLE
Cannot save Indexers

### ISSUE THREAD

**Issue by t4nkw4rt** [nosmokingbandit/watcher#187]
Having a problem? Bummer. Watcher is under constant development, so bear with us while we sort this out.

Meanwhile, you can help us get this fixed more quickly by following this format:

#### What happened?
I've installed watcher and tried to fill in the settings. Everything was saved to config.cfg, except the indexer section. (watcher main branch, python 2.7.13)

#### What was supposed to happen?
Save the indexers to the config.cfg file  :)

#### How can I reproduce this?
Everytime I go to indexer section, fill in my newznab indexers (dog & geek), and try to save them.
No "Settings saved" message, no errors in Log file. Nothing.  :/

**Comment by soundjester** [comment]
same as/similar to: #184

**Comment by t4nkw4rt** [comment]
yes, dupe.
closing this one.
