### ISSUE TITLE
/postprocessing 404s

### ISSUE THREAD

**Issue by ywLBhGk2noZLbY7** [nosmokingbandit/watcher#19]
Since the update yesterday enabling http reverse proxies, the following happens to me:

`INFO 2016-12-25 05:07:23,795 cherrypy.access.${BLAH}.access: 172.19.0.3 - - [25/Dec/2016:05:07:23] "GET /postprocessing?apikey=${BLAH}&mode=complete&guid=${BLAH}&downloadid=${BLAH}&path=${BLAH}.Watcher HTTP/1.1" 404 1030 "" "Mozilla/5.0"`

From the NZBGet postprocessing script. I have verified this behavior on both `/postprocessing` and `/watcher/postprocessing` as documented in the change [here](https://github.com/nosmokingbandit/watcher/commit/0b966559e1b654222580b1618beeb445bb1f2c2c#diff-6849f0d6deb6021485c10ab08e3c5f15R220). My configuration is set to false for reverse proxy in the config file.

**Comment by ywLBhGk2noZLbY7** [comment]
I went ahead and hosted another instance of `watcher`, this time however with the setting `behindproxy = true`. This time /postprocessing works only, as expected, when queried through `/watcher/postprocessing`.

As this is a reproducible error (Affects a brand new configuration of watcher), I won't include additional logs, but the tl;dr is:

| behindproxy | path | response |
| - | - | - |
| false | /postprocessing | 404 |
| false | /watcher/postprocessing | 404 |
| true | /postprocessing | 404 |
| true | /watcher/postprocessing | 200 |

**Comment by duckduckquack** [comment]
I would help test this, but I can't even get the postprocess script to successfully run at all... 
Address commented out (default)
`Sun Dec 25 11:17:05 2016        INFO    watcher: Traceback (most recent call last):  
Sun Dec 25 11:17:05 2016        INFO    watcher:   File "/storage/opt/nzbget/scripts/watcher.py", line 36, in <module>  
Sun Dec 25 11:17:05 2016        INFO    watcher:     watcheraddress = os.environ['NZBPO_ADDRESS']  
Sun Dec 25 11:17:05 2016        INFO    watcher:   File "/usr/lib/python2.7/UserDict.py", line 23, in __getitem__  
Sun Dec 25 11:17:05 2016        INFO    watcher:     raise KeyError(key)  
Sun Dec 25 11:17:05 2016        INFO    watcher: KeyError: 'NZBPO_ADDRESS'`

Uncommented
`Sun Dec 25 11:15:25 2016        INFO    watcher:   File "/storage/opt/nzbget/scripts/watcher.py", line 21
Sun Dec 25 11:15:25 2016        INFO    watcher:     Host=http://127.0.0.1:9090/
Sun Dec 25 11:15:25 2016        INFO    watcher:              ^
Sun Dec 25 11:15:25 2016        INFO    watcher: SyntaxError: invalid syntax`

Just the host
`Sun Dec 25 11:17:37 2016        INFO    watcher:   File "/storage/opt/nzbget/scripts/watcher.py", line 22
Sun Dec 25 11:17:37 2016        INFO    watcher:     Host=127.0.0.1
Sun Dec 25 11:17:37 2016        INFO    watcher:                ^
Sun Dec 25 11:17:37 2016        INFO    watcher: SyntaxError: invalid syntax`

**Comment by ywLBhGk2noZLbY7** [comment]
I was able to fix the issue by replacing:

`mount = '/'`

with

`mount = ''`

[here](https://github.com/nosmokingbandit/watcher/blob/master/watcher.py#L141).

I am unsure what the solution is here, and it's a matter of code readability. Either to strip the "/" from all instances of the code where `mount` is used (I.E. `'{}postprocessing'.format(mount),` rather than `'{}/postprocessing'.format(mount),`), or for `mount` to not include the root path delimiter.

**Comment by soundjester** [comment]
I was having the same issue and can confirm this fix (`mount = '/'` -> `mount = ''`) worked for me.

**Comment by nosmokingbandit** [comment]
Fixed in commit 2a84f90. Revert your changes before updating. Mounting the main application at '' will cause weird problems.

https://github.com/nosmokingbandit/watcher/commit/2a84f90b660dc42c3e21d6c0bedb62782ef9396f
