### ISSUE TITLE
Testing newznab connection to hosted NZBHydra

### ISSUE THREAD

**Issue by Elfman72** [nosmokingbandit/watcher#190]
#### What happened?
I get an error when trying to test my connection to NZBHydra.  [This is the same issue being discussed on Reddit](https://www.reddit.com/r/watcher/comments/5ppe69/trouble_with_indexer/).

```
ERROR 2017-01-23 17:40:19,900 core.newznab.test_connection: NewzNab connection check.
Traceback (most recent call last):
  File "/opt/watcher/app/core/newznab.py", line 162, in test_connection
    xml = urllib2.urlopen(request).read()
  File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib64/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 500: INTERNAL SERVER ERROR
```

#### What was supposed to happen?
It had been previously connecting fine but as of updating to [4236d7 ](https://github.com/nosmokingbandit/watcher/commit/42363d7fb1639069ec3a8fcfa0be6fd3efb71923)this morning. 

I have tested it by creating the following link
`https://MYNZBHYDRAINSTANCE/api?apikey=MYAPI&t=movie&imdbid=0063350`

It returns proper XML with the proper header of:
`<rss xmlns:newznab="http://www.newznab.com/DTD/2010/feeds/attributes/" version="2.0">`

I know NZBHydra just updated recently but not sure if they are related

**Comment by soundjester** [comment]
I rolled back to NZBHydra 0.2.184 (from 0.2.186) to test and I'm getting the same error.

Xposted from reddit: 

> Seems to be an issue related specifically to Hydra's API. The testing request is sent with a 'user' parameter that seems to be unsupported by Hydra, leading to the "Unknown API request. Supported functions: search, tvsearch, movie, get, caps, details, getnfo" message.
>
> For reference, the testing URL that is sent (for me, obv) is:
>
> `http://192.168.1.71:5075/api?apikey=MYAPIKEY&t=user`

**Comment by nosmokingbandit** [comment]
Everything seems to be working for me. I did change a few things around when adding torrent support. Update and try again. Let me know either way.

**Comment by soundjester** [comment]
Upon update, I can report success (for me)!

Testing NZBHydra connection returns:
`{"message": "Connection successful.", "response": "true"}`

**Comment by defubar** [comment]
I updated and it is also working for me now if I run it manually. However, I am having issues running Watcher via systemd and getting the following error:

```
Jan 24 20:21:25 odin python2.7[20796]: Traceback (most recent call last):
Jan 24 20:21:25 odin python2.7[20796]:   File "/opt/watcher/watcher.py", line 65, in <module>
Jan 24 20:21:25 odin python2.7[20796]:     conf.merge_new_options()
Jan 24 20:21:25 odin python2.7[20796]:   File "/opt/watcher/core/config.py", line 113, in merge_new_options
Jan 24 20:21:25 odin python2.7[20796]:     with open(self.file, 'w') as cfgfile:
Jan 24 20:21:25 odin python2.7[20796]: IOError: [Errno 13] Permission denied: u'config.cfg'
Jan 24 20:21:25 odin systemd[1]: watcher.service: Control process exited, code=exited status=1
Jan 24 20:21:25 odin systemd[1]: Failed to start Watcher Daemon.
Jan 24 20:21:25 odin systemd[1]: watcher.service: Unit entered failed state.
Jan 24 20:21:25 odin systemd[1]: watcher.service: Failed with result 'exit-code'.
```

I didn't change my watcher.service at all, which worked prior to updating. I'm a bit of a novice, but any help?

**Comment by Elfman72** [comment]
Strange.

I'm still seeing the 'Actively refused message' after updating.

Looks like the error is the same:
```

ERROR 2017-01-25 01:25:31,682 core.newznab.test_connection: NewzNab connection check.
Traceback (most recent call last):
  File "/opt/watcher/app/core/newznab.py", line 163, in test_connection
    response = urllib2.urlopen(request).read()
  File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib64/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 500: INTERNAL SERVER ERROR
```

I tested with Dog seprately and it works find.  However with PF Monkey, I am getting a 'No Such Function' error message in the UI and no entries in the log file.

Again, running this in a Docker on Synology.

**Comment by Elfman72** [comment]
Whoa.  Scratch that.  Strange things.  Due to being run behind a reverse proxy my instance of Hydra is like this: hydra.myurl.com/nzbhyra.  Removing the trailing /nzbhydra appears to have fixed the issue.

Strange.  I'll run a couple tests to see if it is executing searches properly as well.

**Comment by soundjester** [comment]
I had to clean house a little bit, since I had goofed with the code in testing.  Consequently I started fresh (e.g. python backup.py -b). 

Using Chrome's dev tools, I think the major change I noticed was the the POST request was sent to NZBHydra with a new (to me) variable called `mode` which had a value of `newznab`.

```
General
Request URL:http://192.168.1.71:9090/ajax/indexer_test
Request Method:POST
Status Code:200 OK

Form Data
indexer: http://192.168.1.71:5075/
apikey:MYAPIKEY
mode:newznab
```

I'm running NZBHydra and Watcher in the same FreeBSD jail, but the location of the applications shouldn't really matter (I don't think).

**Comment by nosmokingbandit** [comment]
@defubar 
You don't have write permission for the config file. Make sure the user in the systemd script has write permission to the watcher/ folder.

@soundjester 
That POST request doesn't go to NZBHydra, it just goes to the backend of Watcher. The ajax handler takes all connection tests (newznab, torrent potato) and runs the appropriate method from there. The actual request used to test is a GET in newznab.py and torrent.py.

**Comment by defubar** [comment]
@nosmokingbandit 
I ran chown -R for the user in the systemd script and am still having the same error. I even tried pointing to a copy of the config in the users home directory. Could permissions elsewhere be causing it?

**Comment by nosmokingbandit** [comment]
That use might need write permission to the folder as well. I've not dug that deep in to python's open function.
