### ISSUE TITLE
Watcher does not search for every movie automatically

### ISSUE THREAD

**Issue by Crowley007** [nosmokingbandit/watcher#192]
#### What happened?

When letting Watcher search automatically, it only searched of 3/5 movies. Or at least in the log there are only 3 mentions of "Checking predb.me for new available releases for ***********" even though my wanted list has 5 movies. 

#### What was supposed to happen?

Every movie was supposed to be searched, manual search found one of the "missing" movies just fine. But, for some reason the status stays at "found", it won't snatch it.

#### How can I reproduce this?

Not sure. 

Below is a clean log from restart to automatic search, only movie names are redacted. It shows some errors, but those might be unrelated, they seem show up often.

`INFO 2017-01-25 06:35:33,236 __main__.<module>: SQL DB found.
INFO 2017-01-25 06:35:37,832 core.version.update_check: Checking git for a new version.
INFO 2017-01-25 06:35:45,240 core.version.update_check: Current local hash: 09d97edc66234bc6519ff0939c2959df6dcca264
INFO 2017-01-25 06:35:47,693 cherrypy.error.error: [25/Jan/2017:06:35:47] ENGINE Listening for SIGTERM.
INFO 2017-01-25 06:35:47,696 cherrypy.error.error: [25/Jan/2017:06:35:47] ENGINE Bus STARTING
INFO 2017-01-25 06:35:47,701 cherrypy.error.error: [25/Jan/2017:06:35:47] ENGINE Started monitor thread '_TimeoutMonitor'.
INFO 2017-01-25 06:35:47,964 cherrypy.error.error: [25/Jan/2017:06:35:47] ENGINE Serving on http://127.0.0.1:3535
INFO 2017-01-25 06:35:47,967 cherrypy.error.error: [25/Jan/2017:06:35:47] ENGINE Bus STARTED
INFO 2017-01-25 06:36:52,280 core.version.update_check: Checking git for a new version.
INFO 2017-01-25 06:36:59,539 core.version.update_check: Current local hash: 09d97edc66234bc6519ff0939c2959df6dcca264
INFO 2017-01-25 06:37:01,680 core.sqldb.get_user_movies: Retreving list of user's movies.
INFO 2017-01-25 06:40:48,039 core.rss.predb.check_all: Checking predb.me for new available releases.
INFO 2017-01-25 06:40:48,040 core.sqldb.get_user_movies: Retreving list of user's movies.
INFO 2017-01-25 06:40:48,066 core.rss.predb.check_one: Checking predb.me for new available releases for **********.
INFO 2017-01-25 06:40:49,969 core.rss.predb.check_one: Checking predb.me for new available releases for *************.
INFO 2017-01-25 06:40:50,677 core.rss.predb.check_one: Checking predb.me for new available releases for *******************
INFO 2017-01-25 06:42:22,819 core.sqldb.get_user_movies: Retreving list of user's movies.
INFO 2017-01-25 06:43:58,259 core.sqldb.get_user_movies: Retreving list of user's movies.
INFO 2017-01-25 06:45:01,188 core.sqldb.get_user_movies: Retreving list of user's movies.
INFO 2017-01-25 06:47:05,654 __main__.<module>: SQL DB found.
INFO 2017-01-25 06:47:10,457 core.version.update_check: Checking git for a new version.
INFO 2017-01-25 06:47:18,151 core.version.update_check: Current local hash: 09d97edc66234bc6519ff0939c2959df6dcca264
INFO 2017-01-25 06:47:20,694 cherrypy.error.error: [25/Jan/2017:06:47:20] ENGINE Listening for SIGTERM.
INFO 2017-01-25 06:47:20,697 cherrypy.error.error: [25/Jan/2017:06:47:20] ENGINE Bus STARTING
INFO 2017-01-25 06:47:20,703 cherrypy.error.error: [25/Jan/2017:06:47:20] ENGINE Started monitor thread '_TimeoutMonitor'.
ERROR 2017-01-25 06:47:25,887 cherrypy.error.error: [25/Jan/2017:06:47:25] ENGINE Error in 'start' listener <bound method Server.start of <cherrypy._cpserver.Server object at 0x0000000003BE77F0>>
Traceback (most recent call last):
  File "c:\Git\watcher\lib\cherrypy\process\wspbus.py", line 202, in publish
    output.append(listener(*args, **kwargs))
  File "c:\Git\watcher\lib\cherrypy\_cpserver.py", line 168, in start
    ServerAdapter.start(self)
  File "c:\Git\watcher\lib\cherrypy\process\servers.py", line 172, in start
    wait_for_free_port(*self.bind_addr)
  File "c:\Git\watcher\lib\cherrypy\process\servers.py", line 443, in wait_for_free_port
    raise IOError("Port %r not free on %r" % (port, host))
IOError: Port 3535 not free on '127.0.0.1'

ERROR 2017-01-25 06:47:25,890 cherrypy.error.error: [25/Jan/2017:06:47:25] ENGINE Shutting down due to error in start listener:
Traceback (most recent call last):
  File "c:\Git\watcher\lib\cherrypy\process\wspbus.py", line 240, in start
    self.publish('start')
  File "c:\Git\watcher\lib\cherrypy\process\wspbus.py", line 220, in publish
    raise exc
ChannelFailures: IOError("Port 3535 not free on '127.0.0.1'",)

INFO 2017-01-25 06:47:25,891 cherrypy.error.error: [25/Jan/2017:06:47:25] ENGINE Bus STOPPING
INFO 2017-01-25 06:47:25,894 cherrypy.error.error: [25/Jan/2017:06:47:25] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('127.0.0.1', 3535)) already shut down
INFO 2017-01-25 06:47:25,895 cherrypy.error.error: [25/Jan/2017:06:47:25] ENGINE Stopped thread '_TimeoutMonitor'.
INFO 2017-01-25 06:47:25,898 cherrypy.error.error: [25/Jan/2017:06:47:25] ENGINE Bus STOPPED
INFO 2017-01-25 06:47:25,901 cherrypy.error.error: [25/Jan/2017:06:47:25] ENGINE Bus EXITING
INFO 2017-01-25 06:47:25,904 cherrypy.error.error: [25/Jan/2017:06:47:25] ENGINE Bus EXITED`

**Comment by nosmokingbandit** [comment]
Update to the latest version, then open the status page for the movies that weren't looked for on predb. Do they have a checkmark on the bottom right?

**Comment by Crowley007** [comment]
I tested with version   09d97ed, updated 14 hours ago. No check marks. 

I'm not sure if this is related, but even when I add movies that have been releases months ago, I only get "found" status, it never automatically snatches anymore.

**Comment by Crowley007** [comment]
I made some progress, I deleted the database an added 4 movies, everything seems like it's searched, but nothing is found. But like before, manual search finds releases instantly, only it does not snatch. And these errors keep repeating in the log, not sure if related:

`INFO 2017-01-25 22:31:12,217 core.sqldb.get_search_results: Retreving Search Results for *********.
INFO 2017-01-25 22:31:57,142 core.sqldb.get_user_movies: Retreving list of user's movies.
INFO 2017-01-25 22:32:33,335 core.sqldb.get_user_movies: Retreving list of user's movies.
INFO 2017-01-25 22:34:33,908 __main__.<module>: SQL DB found.
INFO 2017-01-25 22:34:37,640 core.version.update_check: Checking git for a new version.
INFO 2017-01-25 22:34:43,536 core.version.update_check: Current local hash: 09d97edc66234bc6519ff0939c2959df6dcca264
INFO 2017-01-25 22:34:45,484 cherrypy.error.error: [25/Jan/2017:22:34:45] ENGINE Listening for SIGTERM.
INFO 2017-01-25 22:34:45,486 cherrypy.error.error: [25/Jan/2017:22:34:45] ENGINE Bus STARTING
INFO 2017-01-25 22:34:45,492 cherrypy.error.error: [25/Jan/2017:22:34:45] ENGINE Started monitor thread '_TimeoutMonitor'.
ERROR 2017-01-25 22:34:50,667 cherrypy.error.error: [25/Jan/2017:22:34:50] ENGINE Error in 'start' listener <bound method Server.start of <cherrypy._cpserver.Server object at 0x00000000033AD7F0>>
Traceback (most recent call last):
  File "c:\Git\watcher\lib\cherrypy\process\wspbus.py", line 202, in publish
    output.append(listener(*args, **kwargs))
  File "c:\Git\watcher\lib\cherrypy\_cpserver.py", line 168, in start
    ServerAdapter.start(self)
  File "c:\Git\watcher\lib\cherrypy\process\servers.py", line 172, in start
    wait_for_free_port(*self.bind_addr)
  File "c:\Git\watcher\lib\cherrypy\process\servers.py", line 443, in wait_for_free_port
    raise IOError("Port %r not free on %r" % (port, host))
IOError: Port 3535 not free on '127.0.0.1'

ERROR 2017-01-25 22:34:50,674 cherrypy.error.error: [25/Jan/2017:22:34:50] ENGINE Shutting down due to error in start listener:
Traceback (most recent call last):
  File "c:\Git\watcher\lib\cherrypy\process\wspbus.py", line 240, in start
    self.publish('start')
  File "c:\Git\watcher\lib\cherrypy\process\wspbus.py", line 220, in publish
    raise exc
ChannelFailures: IOError("Port 3535 not free on '127.0.0.1'",)

INFO 2017-01-25 22:34:50,677 cherrypy.error.error: [25/Jan/2017:22:34:50] ENGINE Bus STOPPING
INFO 2017-01-25 22:34:50,680 cherrypy.error.error: [25/Jan/2017:22:34:50] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('127.0.0.1', 3535)) already shut down
INFO 2017-01-25 22:34:50,683 cherrypy.error.error: [25/Jan/2017:22:34:50] ENGINE Stopped thread '_TimeoutMonitor'.
INFO 2017-01-25 22:34:50,686 cherrypy.error.error: [25/Jan/2017:22:34:50] ENGINE Bus STOPPED
INFO 2017-01-25 22:34:50,688 cherrypy.error.error: [25/Jan/2017:22:34:50] ENGINE Bus EXITING
INFO 2017-01-25 22:34:50,691 cherrypy.error.error: [25/Jan/2017:22:34:50] ENGINE Bus EXITED
`

**Comment by nosmokingbandit** [comment]
Should be ok after b030d0bfdbc7a3d67f46ce407dbc339afe7967a8.

The port not free error means you have something else using that port. But if you are able to access Watcher at localhost:3535 you probably are trying to run two instances of Watcher.

There is no way to know which python instance is Watcher in Windows (at least not that I'm aware of) so open your task manager and kill all python.exe tasks. You'll terminate anything else that uses python (ie sickrage, sabnzbd, etc), so be aware of that.

**Comment by Crowley007** [comment]
Yeah, now I have the check marks. But automatic search still doesn't get any results, only manual search does. And it never snatches automatically either.

The only python instance I have running is watcher, so that's not it. I'm using windows abd launching it using "start "" pythonw c:\Git\watcher\watcher.py --daemon" and I have only the single pythonw.exe running.

**Comment by nosmokingbandit** [comment]
Ok, this got it back in working order 4fcdda1df1a4ff327c3219311578d703a288e598.

That popped up when I changed how predb searches work. I just tested it and grabbed 4 different movies at once.

**Comment by Crowley007** [comment]
Yeah, these problems seem to be fixed now. Not sure whats going on with the port thing, but that does not seem to affect functionality.
