### ISSUE TITLE
Post process can't create movie folder

### ISSUE THREAD

**Issue by Crowley007** [nosmokingbandit/watcher#193]
Post process is failing again. Log:

`ERROR 2017-01-26 10:18:01,506 core.postprocessing.renamer: Renamer failed: Could not rename file.
Traceback (most recent call last):
  File "c:\Git\watcher\core\postprocessing.py", line 682, in renamer
    os.rename(abs_path_old, abs_path_new)
WindowsError: [Error 123] The filename, directory name, or volume label syntax is incorrect
ERROR 2017-01-26 10:18:01,529 core.postprocessing.mover: Mover failed: Could not create missing directory Z:\Media\Leffat\Lataus\Word1 Word2: Word3 Word4 Word5 2016.
Traceback (most recent call last):
  File "c:\Git\watcher\core\postprocessing.py", line 713, in mover
    os.makedirs(target_folder)
  File "C:\Python27\lib\os.py", line 157, in makedirs
    mkdir(name, mode)
`

**Comment by nosmokingbandit** [comment]
There is a stray colon sneaking into the filename. You don't happen to have
':' set as the character to replace illegal characters?

**Comment by Crowley007** [comment]
Nope the box is empty, but there is one in the name of the movie so that must be why its failing, it doe not get replaced.

**Comment by nosmokingbandit** [comment]
Do you have the renamer turned off?

**Comment by Crowley007** [comment]
Renamer is on with: {title} {year} {resolution} {source}

**Comment by nosmokingbandit** [comment]
Send me the post-processing section of your log. Starting with the lines
that are a bunch of #s.

Don't edit release names or anything, I need to figure out how that colon
is getting through...

**Comment by Crowley007** [comment]
Sent to your email. The colon is in the official movie name, so that must be where it's coming from. It seems the renamer does not replace it.

**Comment by nosmokingbandit** [comment]
Thanks for the logs, should be fixed in commit 78d4d0520183bb9773227e65df28fc02c983f79d.
