### ISSUE TITLE
updating failed

### ISSUE THREAD

**Issue by soupy14** [nosmokingbandit/watcher#20]
keep getting this error "Update failed. Check logs for more information." using chrome browser

as per logs , 

INFO 2016-12-25 09:08:55,503 core.ajax.update_now: Update Failed.
INFO 2016-12-25 09:08:55,503 cherrypy.access.66005704.access: 127.0.0.1 - - [25/Dec/2016:09:08:55] "POST /update_now HTTP/1.1" 200 6 "http://localhost:9090/update/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36"
INFO 2016-12-25 10:54:04,721 cherrypy.access.66005704.access: 127.0.0.1 - - [25/Dec/2016:10:54:04] "GET / HTTP/1.1" 303 102 "" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36"
INFO 2016-12-25 10:54:04,805 core.sqldb.get_user_movies: Retreving list of user's movies.
INFO 2016-12-25 10:54:04,819 cherrypy.access.66005704.access: 127.0.0.1 - - [25/Dec/2016:10:54:04] "GET /status/ HTTP/1.1" 200 4182 "" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36"
INFO 2016-12-25 10:54:08,627 cherrypy.access.66005704.access: 127.0.0.1 - - [25/Dec/2016:10:54:08] "GET /settings/postprocessing HTTP/1.1" 200 4434 "http://localhost:9090/status/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36"
INFO 2016-12-25 10:54:10,551 cherrypy.access.66005704.access: 127.0.0.1 - - [25/Dec/2016:10:54:10] "GET /settings/downloader HTTP/1.1" 200 6174 "http://localhost:9090/settings/postprocessing" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36"
INFO 2016-12-25 10:54:12,561 cherrypy.access.66005704.access: 127.0.0.1 - - [25/Dec/2016:10:54:12] "GET /settings/server HTTP/1.1" 200 5355 "http://localhost:9090/settings/downloader" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36"
INFO 2016-12-25 10:54:34,028 core.version.update_check: Checking git for a new Zip.
INFO 2016-12-25 10:54:34,029 core.version.update_check: Getting local version hash.
INFO 2016-12-25 10:54:34,029 core.version.update_check: Getting newest version hash.
INFO 2016-12-25 10:54:34,503 cherrypy.access.66005704.access: 127.0.0.1 - - [25/Dec/2016:10:54:34] "POST /update_check HTTP/1.1" 200 154 "http://localhost:9090/settings/server" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36"
INFO 2016-12-25 10:54:35,730 cherrypy.access.66005704.access: 127.0.0.1 - - [25/Dec/2016:10:54:35] "POST /update_now HTTP/1.1" 200 7 "http://localhost:9090/settings/server" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36"
INFO 2016-12-25 10:54:35,782 cherrypy.access.66005704.access: 127.0.0.1 - - [25/Dec/2016:10:54:35] "GET /update/ HTTP/1.1" 200 588 "http://localhost:9090/settings/server" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36"
INFO 2016-12-25 10:54:36,380 core.version.execute_update: Updating from Zip file.
INFO 2016-12-25 10:54:36,381 core.version.execute_update: Cleaning up old update files.
INFO 2016-12-25 10:54:36,381 core.version.execute_update: Downloading latest Zip.
INFO 2016-12-25 10:54:37,746 core.version.execute_update: Extracting Zip to temporary directory.
INFO 2016-12-25 10:54:44,977 core.version.execute_update: Backing up user files.
ERROR 2016-12-25 10:54:44,996 core.version.execute_update: Could not back up user files.
Traceback (most recent call last):
  File "C:\Users\Media PC\Downloads\watcher-master\core\version.py", line 376, in execute_update
    if os.path.path('logs'):
AttributeError: 'module' object has no attribute 'path'
INFO 2016-12-25 10:54:44,999 core.ajax.update_now: Update Failed.
INFO 2016-12-25 10:54:45,000 cherrypy.access.66005704.access: 127.0.0.1 - - [25/Dec/2016:10:54:45] "POST /update_now HTTP/1.1" 200 6 "http://localhost:9090/update/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36"

**Comment by nosmokingbandit** [comment]
I just pushed a fix for this. You'll have to manually back up and reinstall to get it working again.

Check for backup/restore instructions:
https://github.com/nosmokingbandit/watcher/blob/master/README.md
