### ISSUE TITLE
Plugin folder access for docker? 

### ISSUE THREAD

**Issue by WilliamJBrown** [nosmokingbandit/watcher#201]
Hey our Watcher Lord and Saviour. 

Just wondering if you can give us the ability to map out the access for plugin folders.

--plugin /plugin/

This way we can plop in plugins to the folders we have mapped out. I was wanting to put the pushbullet plugin to the finished section :)

This is by no means a rush but let us know if this can be done. 👍 

Thanks for all the great work!

**Comment by WilliamJBrown** [comment]
Also not sure if there is a way to map out the whole installation to a certain folder. That way we could do --main /main/ then everything for docker can be used in the folder? 

Not sure if thats something that could be done either :)

**Comment by Elfman72** [comment]
> Also not sure if there is a way to map out the whole installation to a certain folder. That way we could do --main /main/ then everything for docker can be used in the folder?

All my other Docker containers do this and it is really handy for troubleshooting on Synology.  Most of them just dump all the files in the /config variable.  So I would second this feature.

**Comment by nosmokingbandit** [comment]
> Also not sure if there is a way to map out the whole installation to a certain folder. That way we could do --main /main/ then everything for docker can be used in the folder?

I don't know anything about how docker works. If there is an easier way to do this i'll need more explanation.

If you map the entire watcher folder to an external (relative to the container) path, what is the point of the container?

**Comment by WilliamJBrown** [comment]
It avoids the issue of certain OS or package installations requirements. It packages it all together and the user doesn't need to worry about specifics. Also anyone that can use docker on their device can use any container that is on the docker hub. All they do need to worry about is folder destinations :)

**Comment by nosmokingbandit** [comment]
My server uses an aarm64 cpu, so there are no pre-made containers for it.

It just seems silly to have to tell it where every single file is and adds a lot of garbage to the code to point it toward everything.

**Comment by nosmokingbandit** [comment]
As of 7f48da8b06699adf9455bc8d60bdd3c4d5986ad4, map plugins dir with `--plugins /path/to/plugins/`
