### ISSUE TITLE
Movie Search fails - always suggests to add IMDB #

### ISSUE THREAD

**Issue by yoleska** [nosmokingbandit/watcher#208]
For the last two releases, it seems that whenever I search for any movie (new or old), the error always comes up as "Could not find IMDB for [movie].  Try entering IMDB id in search bar". 

So I search IMDB, grab the ID from the URL, and put it in the search bar.  It finds it and adds to the queue without any problems. 

Logs:

ERROR 2017-02-05 22:05:36,761 core.movieinfo.get_info: OMDB search.
Traceback (most recent call last):
  File "/opt/watcher/core/movieinfo.py", line 54, in get_info
    result = json.load(urllib2.urlopen(request))
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 503: Service Temporarily Unavailable

>:/opt/watcher/post scripts$ ls -lrt /usr/lib/python2.7/urllib2.py
-rw-r--r-- 1 root root 52513 Nov 19 01:32 /usr/lib/python2.7/urllib2.py
>:/opt/watcher/post scripts$
>:/opt/watcher/post scripts$ python --version
Python 2.7.12

OS: 
NAME="Ubuntu"
VERSION="16.04.1 LTS (Xenial Xerus)"

**Comment by nosmokingbandit** [comment]
OMDB has been having troubles the last few days. We just have to wait until they fix it.

They normally get ~45 million requests and hour, but someone was spamming the api with 300 million *additional* requests and hour.

So they owner had to basically shut down the api to figure out what is going on.

**Comment by yoleska** [comment]
Great, thanks for the quick reply!
