### ISSUE TITLE
Watcher.py Post-Script error

### ISSUE THREAD

**Issue by yoleska** [nosmokingbandit/watcher#209]
Cant quite figure this one out.  I'm wondering if it's related to the other bug I just filed #208  with the urllib2 library as both issues reference this library.

Edit:  This WAS working just fine up until about a week ago.   I'm not sure the exact time/release it started failing. 

NZBGet throws this error when the post-process script is run:

ERROR	Sun Feb 05 2017 21:55:05	Post-process-script watcher-nzbget.py for The Movie.Watcher failed (terminated with unknown status)
INFO	Sun Feb 05 2017 21:55:05	watcher-nzbget: SyntaxError: invalid syntax
INFO	Sun Feb 05 2017 21:55:05	watcher-nzbget: ^
INFO	Sun Feb 05 2017 21:55:05	watcher-nzbget: user@server:/opt/watcher/post scripts$ ls -lrt
INFO	Sun Feb 05 2017 21:55:05	watcher-nzbget: File "/usr/local/nzbget/share/nzbget/scripts/watcher-nzbget.py", line 30
INFO	Sun Feb 05 2017 21:55:05	Executing post-process-script watcher-nzbget.py for The Movie.Watcher
INFO	Sun Feb 05 2017 21:55:05	Queueing The Movie.Watcher for post-processing

Lines 22-34 in script are: 

#####################################

import json
import os
import sys
import urllib
import urllib2

POSTPROCESS_SUCCESS = 93
POSTPROCESS_ERROR = 94
POSTPROCESS_NONE = 95

**Comment by nosmokingbandit** [comment]
When I run that script by itself `python nzbget.py` it doesn't throw an exception until line 36, which is where it should fail in that circumstance.

Your other issue is the result of some OMDB problems, which I commented on in greater detail there.

If you can, open python on the machine running nzbget and enter the following one line at a time and see if anything goes wrong.

```
import json
import os
import sys
import urllib
import urllib2

POSTPROCESS_SUCCESS = 93
POSTPROCESS_ERROR = 94
POSTPROCESS_NONE = 95

```

**Comment by yoleska** [comment]
Damn, chalk this one up to user error.  Copy/paste error when I  moved the script from one machine to another. 

Sorry for the trouble.  Works good now.  

There is one lingering question though that is related to this script and the watcher program.  When Watcher adds the script to nzbget, it adds it as "moviename watcher" instead of the file details, like resolution, provider,release group, etc... 

i.e. "The Best Movie Ever 2016 BRRip x264 720p-NPW"

 Any way to get that information to stay with the filename? 


Thanks!


`

**Comment by nosmokingbandit** [comment]
I don't know why I ever changed that to the movie title instead of the release title.

I changed it back, but I want to test all of the downloaders again to see if it was breaking something doing it this way. I'll probably push that update tomorrow.
