### ISSUE TITLE
NZBGet postprocessing script is invalid

### ISSUE THREAD

**Issue by ywLBhGk2noZLbY7** [nosmokingbandit/watcher#21]
Variable name in the configuration is "[Host](https://github.com/nosmokingbandit/watcher/blob/master/post%20scripts/nzbget.py#L21)", however the variable is later referenced as "[Address](https://github.com/nosmokingbandit/watcher/blob/master/post%20scripts/nzbget.py#L36)".

You should either change host to address or address to host, as currently this produces an error.

@duckduckquack was having this issue in #19, however they have since deleted their post.

**Comment by nosmokingbandit** [comment]
Fixed in commit 63919a7. This is what happens when I make changes in a hurry, during christmas, and while drugged up fighting a sinus infection. Remember to switch in the new post-scripts.

https://github.com/nosmokingbandit/watcher/commit/63919a75e79d6cc9a50c99d734bbe863b87030c8

**Comment by duckduckquack** [comment]
oops, my bad.. i assumed it was something i had done wrong and didn't want to mess up your thread... i was collecting info and going to open my own. But I'll go ahead and test with the new files.

**Comment by ywLBhGk2noZLbY7** [comment]
>while drugged up fighting a sinus infection

Glad I'm not the only one on drugs feeling shitty this festive season, no offense!
