### ISSUE TITLE
Invalid comparison between 'true' (String) and True (Boolean)

### ISSUE THREAD

**Issue by Technifocal** [nosmokingbandit/watcher#211]
Throughout the entirety of [this](https://github.com/nosmokingbandit/watcher/blob/819f9e2677ebdac6c899922169c06d46a3745aec/core/postprocessing.py#L572-L625) section you are running:

`if config['moverenabled'] == u'true':`

Whereas the configuration file stores the files as native 'true' boolean values, not strings:

```
	"Postprocessing": {
		"cleanupenabled": false,
		"cleanupfailed": true,
		"createhardlink": false,
		"moveextensions": "",
		"moverenabled": false,
		"moverpath": "",
		"renamerenabled": true,
		"renamerstring": "",
		"replaceillegal": ""
	},
```

I am not going to create a pull request as I'm not 100% sure how deep this error goes (Need to compare all instances of `'true'` and `'false'` with `true` and `false`), but I can confirm:

```
>>> json.loads('{"test": true}')['test'] == u'true'
False
```

**Comment by nosmokingbandit** [comment]
I got it fixed in eb00941f1c3ee9618faeb661237c2986a6a9c668
