### ISSUE TITLE
running Watcher on Freenas

### ISSUE THREAD

**Issue by seed1234** [nosmokingbandit/watcher#212]
Having a problem? Bummer. Watcher is under constant development, so bear with us while we sort this out.

Meanwhile, you can help us get this fixed more quickly by following this format:

#### What happened?
Erro when trying to  python watcher/watcher.py
#### What was supposed to happen?
/watcher/lib/fuzzywuzzy/fuzz.py:35: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')
Config file found, merging any new options.
Traceback (most recent call last):
  File "watcher/watcher.py", line 96, in <module>
    sql = sqldb.SQL()
  File "/watcher/core/sqldb.py", line 24, in __init__
    self.engine = create_engine(DB_NAME, echo=False, connect_args={'timeout': 30})
  File "/watcher/lib/sqlalchemy/engine/__init__.py", line 387, in create_engine
    return strategy.create(*args, **kwargs)
  File "/watcher/lib/sqlalchemy/engine/strategies.py", line 80, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/watcher/lib/sqlalchemy/dialects/sqlite/pysqlite.py", line 339, in dbapi
    raise e
#### How can I reproduce this?

Including logs of the event are often neccessary to find out exactly what is going on.
If the log section is short feel free to post is here, but make sure to remove any personal information (ie IP address) and remove any references to movie or release titles.
If the logs are long, or require release title names to troubleshoot, submit an issue here, then send the logs to watchernzb@gmail.com.
Put a link to your issue in the email body so we know exactly who it belongs to.

**Comment by nosmokingbandit** [comment]
I don't know how I completely missed this issue, sorry I took so long to address this.

Unfortunately the exception doesn't give much useful info, but it looks like sqlalchemy is failing to `import sqlite3`, which is part of the standard library. Perhaps the python build for Freenas doesn't include this package.

Try something out for me. SSH into your Freenas and run the following:
```
python

import sqlite3

```

If I'm correct it will throw an exception that looks like this:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named sqlite3
```

If it does, close python with `exit()` and try running `pip install sqlite3` to install the package, then fire up Watcher again.
