### ISSUE TITLE
Torrent black hole support?

### ISSUE THREAD

**Issue by bleomycin** [nosmokingbandit/watcher#213]
Thanks for the great work you've done! 

Sorry if this has been brought up but my search didn't turn up much. Is it possible to have watcher monitor a specific local directory for content to be post processed? The way my current setup works is CP sends a torrent to a remote seedbox, then the machine running watcher downloads anything new in the completed folder on the seedbox (script checks every 5 mins via cron) to itself to a folder CP monitors for releases then post processes. Is this possible with watcher?

**Comment by nosmokingbandit** [comment]
It is, but how does that setup handle magnet links? Some torrent providers don't offer files, just the magnet. Some give just the hash, with which I construct my own magnet links.

**Comment by bleomycin** [comment]
I hadn't even thought about magnet links. Can those not be sent to the torrent clients directly through their api? Deluge daemon for example? 

I suppose my question really had less to do with getting the torrent file/magnet link to the torrent client and more with post processing a movie file that ends up being dumped into a folder watched by watcher regardless of origin. In this scenario a torrent is downloaded to a remote machine, then synced to the local machine to a folder that then needs to be watched for post processing. This is how I currently do things with Sonarr and CP.

**Comment by nosmokingbandit** [comment]
All of the supported downloads can take both magnets and torrent files (Deluge Daemon, Deluge via web interface, Transmission, and QBittorrent). All I do is send them the link through the api and they do the rest.

Monitoring a directory for new content is something I probably will never get to. If you want to get fancy you can fire off a script every time you sync from your seedbox that tells Watcher what just got added.

Or, if you have your seedbox set up with samba sharing (you might be able to do this with an ftp mount as well, I've never tried), you can have Watcher copy the move as soon as the download client finishes up. Sonarr has a Remote Mapping feature that I copied to facilitate this.

https://github.com/nosmokingbandit/watcher/wiki/Remote-Mapping

**Comment by bleomycin** [comment]
Awesome, sure if you don't mind pointing me in the right direction to setting up the Post request script I can probably muddle my way through making one. I have a basic understanding of bash scripting and python but with enough google i usually muddle my way into something that works for me.

All my current script does is use lftp over sftp to search the remote seedbox for new content every few minutes (because it supports segmented downloading), download it to a local post processing directory, delete the remote symlinks to the downloaded content so it doesn't download the same crap endlessly, extract rar's/zips if needed and CP/Sonarr just picks up anything in that directory on its own.

With your method once the files have completed their download and extraction to a local folder Watcher has access to I just need to add some type of post request that sends the filenames of available files to watcher? Or am I way off?  Thanks for any help!

**Comment by nosmokingbandit** [comment]
I added a bit more to the wiki under post-processing.
https://github.com/nosmokingbandit/watcher/wiki/Post-Processing

The main problem I see with this configuration is that you won't be able to shift a search result from Snatched to Finished because you won't be able to identify which search result this is responding to. But you'll be able to mark the movie itself as Finished and have Watcher do any post-processing you like.


Depending on your set up you probably want to pass the info to the post-script as command line vars.

So you can send the command:
`python postprocessingscript.py '123456789watcherapikey' '/path/to/movie/file'`

Then I'd set up the python script as such:
```
import json
import urllib
import urllib2
import sys

script, apikey, path = sys.argv

data = {'apikey': apikey, 'mode': 'complete', 'guid': None, 'path': path}
post_data = urllib.urlencode(data)

url = 'http://localhost:9090/postprocessing/'

request = urllib2.Request(url, post_data)

response = json.loads(urllib2.urlopen(request, timeout=300))

if response['status'] == 'finished':
    # Do something if post-processing was a success
else:
    # Do something if post-processing failed

```

That is mostly off the top of my head but it is easy enough to test it for your environment when you decide how to best handle it.
