### ISSUE TITLE
Nothing is ever found.

### ISSUE THREAD

**Issue by crazyman143** [nosmokingbandit/watcher#214]
Hi Folks, not sure if this is a bug or just me being an idiot, but I installed Watcher a couple weeks ago and it still hasn't found a single thing. 

My indexers are althub, usenet-crawler, and pirate bay via jackett running locally.
Running on a windows 7 machine with python installed. 
Running Watcher as a system service using NSSM.

Testing the indexers passes, updating works, adding movies works, etc. Just never finds a thing either via schedule or manual searches. I know the movies are there because I logged into the indexers and they're there.

logs from my searches:
`INFO 2017-02-12 00:07:38,155 core.sqldb.get_user_movies: Retreving list of user's movies.
INFO 2017-02-12 00:07:39,994 core.sqldb.get_movie_details: Retreving details for tt1211837.
INFO 2017-02-12 00:07:39,996 core.sqldb.get_search_results: Retreving Search Results for tt1211837.
INFO 2017-02-12 00:07:41,470 core.newznab.search_all: SEARCHING: https://althub.co.za/api?apikey=APIKEY&t=movie&imdbid=1211837
INFO 2017-02-12 00:07:43,003 core.newznab.search_all: SEARCHING: http://www.usenet-crawler.com/api?apikey=APIKEY&t=movie&imdbid=1211837
INFO 2017-02-12 00:07:45,799 core.newznab.search_all: SEARCHING: http://127.0.0.1:9117/torznab/thepiratebay/api?apikey=APIKEY&t=movie&imdbid=1211837
ERROR 2017-02-12 00:07:47,377 core.newznab.search_all: NewzNab search_all get xml
Traceback (most recent call last):
  File "C:\watcher\core\newznab.py", line 54, in search_all
    nn_results = self.parse_newznab_xml(results_xml)
  File "C:\watcher\core\newznab.py", line 84, in parse_newznab_xml
    result_item = self.make_item_dict(channel_child)
  File "C:\watcher\core\newznab.py", line 110, in make_item_dict
    if ic.tag == u'guid' and ic.attrib['isPermaLink'] == u'false':
KeyError: 'isPermaLink'
INFO 2017-02-12 00:07:47,380 core.sqldb.get_search_results: Retreving Search Results for tt1211837.
INFO 2017-02-12 00:07:47,384 core.sqldb.get_movie_details: Retreving details for tt1211837.
INFO 2017-02-12 00:07:47,391 core.sqldb.get_marked_results: Retreving Marked Results for tt1211837.
INFO 2017-02-12 00:07:47,391 core.searcher.store_results: 0 results found for tt1211837. Storing results.
INFO 2017-02-12 00:07:47,394 core.sqldb.get_distinct: Getting distinct values for tt1211837 in SEARCHRESULTS
INFO 2017-02-12 00:07:47,398 core.updatestatus.movie_status: Setting MOVIES tt1211837 status to Wanted.
INFO 2017-02-12 00:07:47,398 core.sqldb.update: Updating tt1211837 to Wanted in MOVIES.
INFO 2017-02-12 00:07:47,516 core.sqldb.get_search_results: Retreving Search Results for tt1211837.
INFO 2017-02-12 00:07:47,523 core.sqldb.get_user_movies: Retreving list of user's movies.
INFO 2017-02-12 00:09:36,719 core.sqldb.get_user_movies: Retreving list of user's movies.
INFO 2017-02-12 00:10:18,072 core.newznab.test_connection: Testing connection to http://127.0.0.1:9117/torznab/thepiratebay
INFO 2017-02-12 00:10:18,137 core.newznab.test_connection: Testing connection to http://127.0.0.1:9117/torznab/thepiratebay
INFO 2017-02-12 00:10:34,881 core.ajax.save_settings: Saving settings.
INFO 2017-02-12 00:10:38,923 core.sqldb.get_user_movies: Retreving list of user's movies.
INFO 2017-02-12 00:10:40,678 core.sqldb.get_movie_details: Retreving details for tt1211837.
INFO 2017-02-12 00:10:40,687 core.sqldb.get_search_results: Retreving Search Results for tt1211837.
INFO 2017-02-12 00:10:41,839 core.newznab.search_all: SEARCHING: https://althub.co.za/api?apikey=APIKEY&t=movie&imdbid=1211837
INFO 2017-02-12 00:10:43,558 core.newznab.search_all: SEARCHING: http://127.0.0.1:9117/torznab/thepiratebay/api?apikey=APIKEY&t=movie&imdbid=1211837
ERROR 2017-02-12 00:10:45,279 core.newznab.search_all: NewzNab search_all get xml
Traceback (most recent call last):
  File "C:\watcher\core\newznab.py", line 54, in search_all
    nn_results = self.parse_newznab_xml(results_xml)
  File "C:\watcher\core\newznab.py", line 84, in parse_newznab_xml
    result_item = self.make_item_dict(channel_child)
  File "C:\watcher\core\newznab.py", line 110, in make_item_dict
    if ic.tag == u'guid' and ic.attrib['isPermaLink'] == u'false':
KeyError: 'isPermaLink'
INFO 2017-02-12 00:10:45,280 core.newznab.search_all: SEARCHING: http://www.usenet-crawler.com/api?apikey=APIKEY&t=movie&imdbid=1211837
INFO 2017-02-12 00:10:48,216 core.sqldb.get_search_results: Retreving Search Results for tt1211837.
INFO 2017-02-12 00:10:48,219 core.sqldb.get_movie_details: Retreving details for tt1211837.
INFO 2017-02-12 00:10:48,220 core.sqldb.get_marked_results: Retreving Marked Results for tt1211837.
INFO 2017-02-12 00:10:48,223 core.searcher.store_results: 0 results found for tt1211837. Storing results.
INFO 2017-02-12 00:10:48,223 core.sqldb.get_distinct: Getting distinct values for tt1211837 in SEARCHRESULTS
INFO 2017-02-12 00:10:48,226 core.updatestatus.movie_status: Setting MOVIES tt1211837 status to Wanted.
INFO 2017-02-12 00:10:48,226 core.sqldb.update: Updating tt1211837 to Wanted in MOVIES.
INFO 2017-02-12 00:10:48,426 core.sqldb.get_search_results: Retreving Search Results for tt1211837.
INFO 2017-02-12 00:10:48,467 core.sqldb.get_user_movies: Retreving list of user's movies.
INFO 2017-02-12 00:13:11,884 core.sqldb.get_user_movies: Retreving list of user's movies.`

**Comment by nosmokingbandit** [comment]
What I'm most intrigued by is that you use UsenetCrawler. I wasn't aware that they came back. They were always one of the best free indexers and I was bummed when they started to fall apart.

Unfortunately, the log gets pretty mangled when posting it here.

Would you mind sending it to me at watchernzb@gmail.com

**Comment by crazyman143** [comment]
UsenetCrawler seems to come and go for me. Watcher was configured for the Torznab host on Jackett for TPB. For some reason jackett isn't showing a potato feed, separate problem. 

For testing I just removed the other indexers and only have AltHub and the default Torrent Indexers enabled in Watcher.

still no results in my searches. Maybe a problem with althub and watcher? Nothing picked up from the torrent indexers either, though.

I'll email you the logfile now. Thanks for your time.

**Comment by nosmokingbandit** [comment]
I didn't forget about you, I just haven't been able to figure out exactly what was going on.

I've made a bunch of changes to the filtering methods lately. Try updating and searching again. If it still comes up with no results the logs should at least be a little more descriptive now.

**Comment by nosmokingbandit** [comment]
Closed due to inactivity.
