### ISSUE TITLE
Last version broke movie searcher

### ISSUE THREAD

**Issue by SuperPotatoMen** [nosmokingbandit/watcher#218]
Having a problem? Bummer. Watcher is under constant development, so bear with us while we sort this out.

Meanwhile, you can help us get this fixed more quickly by following this format:

#### What happened?
If you add a movie or search manualy Watcher can't find any movies.
#### How can I reproduce this?

If you add a movie he didn't find any movies.

```
INFO 2017-02-13 00:43:03,025 core.newznab.search_all: SEARCHING: https://api.oznzb.com/api?apikey=APIKEY&t=movie&imdbid=1074638
INFO 2017-02-13 00:43:05,141 core.sqldb.get_search_results: Retreving Search Results for tt1074638.
INFO 2017-02-13 00:43:05,142 core.sqldb.get_movie_details: Retreving details for tt1074638.
INFO 2017-02-13 00:43:03,025 core.newznab.search_all: SEARCHING: https://api.oznzb.com/api?apikey=APIKEY&t=movie&imdbid=1074638
INFO 2017-02-13 00:43:05,141 core.sqldb.get_search_results: Retreving Search Results for tt1074638.
INFO 2017-02-13 00:43:05,142 core.sqldb.get_movie_details: Retreving details for tt1074638.

```
If you search by manualy watcher will forever searching and in the logs you found this error:

```
INFO 2017-02-13 00:43:05,176 cherrypy.error.70451184.error: [13/Feb/2017:00:43:05] HTTP 
Request Headers:
  Content-Length: 56
  COOKIE: _ga=GA1.1.906124510.1484752094; manage_view=thumb; _pk_id.1.1fff=bf1857cb70ef1f99.1483658498.28.1486855080.1486855078.; user="2|1:0|10:1486899450|4:user|44:YjgxOTY0ZGIxMmQ1NDA4Yjk0ZmRiYTgyNjcxNzFhMzY=|78daee4e1cbc270b6df95f41457defb36747993d760c21ca384ad6d1352ad0a9"; snatched_view=list; soon_view=thumb; suggest_view=thumb; late_view=list; advanced_toggle_checked=1; blu_ray_com_new_releases_view=thumb; imdb_box_office_view=thumb; list_style=posters; wanted_view=thumb; session_id=a7497b34de8a978ad6c21f6fc8d4bddf9e1b8c49
  HOST: localhost:9090
  ORIGIN: http://localhost:9090
  CONNECTION: keep-alive
  Remote-Addr: 127.0.0.1
  ACCEPT: */*
  USER-AGENT: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36
  X-REQUESTED-WITH: XMLHttpRequest
  ACCEPT-LANGUAGE: nl-NL,nl;q=0.8,en-US;q=0.6,en;q=0.4
  Content-Type: application/x-www-form-urlencoded; charset=UTF-8
  REFERER: http://localhost:9090/status/
  ACCEPT-ENCODING: gzip, deflate, br
ERROR 2017-02-13 00:43:05,203 cherrypy.error.70451184.error: [13/Feb/2017:00:43:05] HTTP 
Traceback (most recent call last):
  File "C:\watcher\watcher-master\lib\cherrypy\_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "C:\watcher\watcher-master\lib\cherrypy\lib\encoding.py", line 220, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "C:\watcher\watcher-master\lib\cherrypy\_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "C:\watcher\watcher-master\core\ajax.py", line 268, in search
    self.searcher.search(imdbid, title, year, quality)
  File "C:\watcher\watcher-master\core\searcher.py", line 183, in search
    scored_results = self.score.score(results, imdbid=imdbid)
  File "C:\watcher\watcher-master\core\scoreresults.py", line 78, in score
    self.retention_check(retention, today)
  File "C:\watcher\watcher-master\core\scoreresults.py", line 192, in retention_check
    pubdate = datetime.strptime(result['pubdate'], '%d %b %Y')
  File "C:\Python27\lib\_strptime.py", line 325, in _strptime
    (data_string, format))
ValueError: time data '15 May 2014' does not match format '%d %b %Y'
```

**Comment by nosmokingbandit** [comment]
That seems to be incompatibility with oznzb's date format. I am able to search other indexers without trouble.


Enter this in your browser
`https://api.oznzb.com/api?apikey=APIKEY&t=movie&imdbid=1074638`
but with your api key, of course.

Find a tag that looks like this: `<pubDate>Tue, 22 Nov 2016 00:00:37 +0100</pubDate>`

Copy that here so I can see how they format their published dates.

**Comment by SuperPotatoMen** [comment]
<pubDate>Sat, 11 Oct 2014 00:58:42 +1000</pubDate>

**Comment by SuperPotatoMen** [comment]
@nosmokingbandit 
I got a better error message know:
`Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\Python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\watcher\watcher-master\core\ajax.py", line 110, in thread_search_grab
    if self.searcher.search(imdbid, title, year, quality):
  File "C:\watcher\watcher-master\core\searcher.py", line 183, in search
    scored_results = self.score.score(results, imdbid=imdbid)
  File "C:\watcher\watcher-master\core\scoreresults.py", line 78, in score
    self.retention_check(retention, today)
  File "C:\watcher\watcher-master\core\scoreresults.py", line 200, in retention_check
    pubdate = datetime.strptime(result['pubdate'], '%d %b %Y')
  File "C:\Python27\lib\_strptime.py", line 325, in _strptime
    (data_string, format))
ValueError: time data '15 May 2014' does not match format '%d %b %Y'`

**Comment by nosmokingbandit** [comment]
This one has been really confusing me for a while, because '15 May 2014' *does* match '%d %b %Y'.

Your computer wouldn't happen to be set to use a different language than English, would it? It could be expecting a different month abbreviation. I can force the parser to use a different locale if this is the case.

**Comment by SuperPotatoMen** [comment]
I'm now on NLD (dutch). I will change it and try it out.

**Comment by SuperPotatoMen** [comment]
@nosmokingbandit i fixed this issue now with changing my language to US english 👍 
Is it possible to make fix? (A)

**Comment by nosmokingbandit** [comment]
Commit 3717c1a7237a1652165ea592a40ff195110213b7 *should* fix this.

**Comment by SuperPotatoMen** [comment]
fixed!
