### ISSUE TITLE
Watcher says 0 results found for release although indexer returns results

### ISSUE THREAD

**Issue by theotherp** [nosmokingbandit/watcher#219]
#### What happened?
I run Watcher against my own NZBHydra instance. I know from the log that Hydra does return results. Watcher's log says 0 results were found for the release. At least some of the results match the file restrictions and I haven't configured any forbidden or required words.
#### What was supposed to happen?
It should use the releases or at least log a proper message why.
#### How can I reproduce this?
Don't think you can.

Watcher log line:
`INFO 2017-02-13 19:44:05,774 core.searcher.store_results: 0 results found for tt2119532. Storing results.`

NZBHydra log:
```
2017-02-13 19:44:04,505 - DEBUG - web - Thread-37 - http://127.0.0.1:5060/api?apikey=<APIKEY>&t=movie&imdbid=2119532
2017-02-13 19:44:05,722 - INFO - search - Thread-37 - Returning 34 results
```

Unfortunately your log output is a bit sparse so I haven't found any information that would allow me to fix this myself.

Cheers.

**Comment by nosmokingbandit** [comment]
I'm unable to replicate this. I just got about a dozen results going through nzbhydra.

In commit 46c6788d653c9b69c2d22376762ede2c0cecc7a1 I made the logging a bit more verbose, let me know if that gives any more insight.

**Comment by theotherp** [comment]
Will do, thanks.

**Comment by theotherp** [comment]
Hm, unfortunately the log doesn't say anything more. I added an indexer directly and watcher found a release. Weird. I'll debug my code and check what Hydra actually returns, perhaps that will help.

**Comment by yoleska** [comment]
I'm also seeing similar problems.  Manual search returns several hits for shows, but Watcher returns 0:

`INFO 2017-02-24 16:48:28,333 core.sqldb.get_search_results: Retreving Search Results for ttMovie.
INFO 2017-02-24 16:48:28,335 core.sqldb.get_movie_details: Retreving details for ttMovie.
INFO 2017-02-24 16:48:28,336 core.scoreresults.score: Scoring 4 results.
INFO 2017-02-24 16:48:28,336 core.scoreresults.remove_ignored: Filtering Ignored Words.
INFO 2017-02-24 16:48:28,336 core.scoreresults.remove_ignored: Keeping 3 results.
INFO 2017-02-24 16:48:28,336 core.scoreresults.retention_check: Checking retention.
INFO 2017-02-24 16:48:28,337 core.scoreresults.retention_check: Keeping 3 results.
INFO 2017-02-24 16:48:28,337 core.scoreresults.seed_check: Checking torrent seeds.
INFO 2017-02-24 16:48:28,337 core.scoreresults.seed_check: Keeping 3 results.
INFO 2017-02-24 16:48:28,338 core.scoreresults.score_sources: Filtering resolution and size requirements.
INFO 2017-02-24 16:48:28,338 core.scoreresults.score_sources: Keeping 0 results.
INFO 2017-02-24 16:48:28,338 core.scoreresults.fuzzy_title: Checking title match.
INFO 2017-02-24 16:48:28,338 core.scoreresults.fuzzy_title: Keeping 0 results.
INFO 2017-02-24 16:48:28,338 core.scoreresults.score_preferred: Scoring Preferred Words.
INFO 2017-02-24 16:48:28,338 core.sqldb.get_marked_results: Retreving Marked Results for ttMovie.
INFO 2017-02-24 16:48:28,339 core.searcher.store_results: 0 results found for ttMovie. Storing results.
INFO 2017-02-24 16:48:28,340 core.sqldb.get_movie_details: Retreving details for ttMovie.
INFO 2017-02-24 16:48:28,341 core.sqldb.get_distinct: Getting distinct values for ttMovie in SEARCHRESULTS
INFO 2017-02-24 16:48:28,342 core.updatestatus.movie_status: Setting MOVIES ttMovie status to Wanted.
INFO 2017-02-24 16:48:28,343 core.sqldb.update: Updating ttMovie to Wanted in MOVIES.
INFO 2017-02-24 16:48:28,378 core.sqldb.get_search_results: Retreving Search Results for ttMovie.
INFO 2017-02-24 16:48:28,390 core.sqldb.get_user_movies: Retreving list of user's movies.`

**Comment by yoleska** [comment]
Seems like it's filtering out, but I haven't changed any of the filter settings.  What's odd is that movies that were added a week ago return tons of results - but any new movies added in the last week return 0 results.

**Comment by shippern** [comment]
I had the same issue. Figured out that all results had been parsed to a `Telesync` even though that was not true. 

I discovered the reason for this was that the tracker I was using contained the substring `ts` in its name and all results were postfixed with the name of the tracker and thus https://github.com/nosmokingbandit/watcher/blob/14447ea72a4064373405bad0338434c3e36d9fb0/core/searcher.py#L257 would map it to a telesync.

I simply removed `ts` as an alias for `Telesync` and started working again. It can be done in Settings -> Quality -> Alias in Watcher.

A code fix could be to improve the matching for aliases and maybe require a space or a dot before `ts`

**Comment by nosmokingbandit** [comment]
As of commit https://github.com/nosmokingbandit/watcher/commit/9f89720c49b6080b6e201e8d2f2a119ec5cf3391, sources are parsed with delimiters.

So instead of finding 'blu-ray' it looks for '.blu-ray', '-blu-ray', '_blu-ray', or ' blu-ray'.

This should all but eliminate incorrect sources.

**Comment by shippern** [comment]
I pulled the latest and added `ts` as an alias again. Works great now.

Thanks @nosmokingbandit

**Comment by untitledxi** [comment]
I think the issue is invalid ```newznab``` URL generation. The log shows the following URL:

```
http://<host>/api?apikey=<actual_api_key>&t=movie&imdbid=<imdbid>api?apikey=APIKEY&t=movie&imdbid=<imdbid>
```

I would suggest using [urllib](https://docs.python.org/2/library/urllib.html) to build the url.

**Comment by untitledxi** [comment]
The issue that I've experienced is unique to ```NZBHydra``` (i believe) as ```watcher``` is checking if the indexer's ```url``` is present in the result ```guid```, but as ```NZBHydra``` is merely a proxy, ```watcher``` removes all results as it marks every result as coming from an inactive indexer.

IMHO there shouldn't be a inactive filtering, the inactive indexer should never be queried in the first place.

However its a bit more complicated as its an issue only when ```NZBHydra``` have enabled ```useLocalUrlForApiAccess``` or when an ```externalUrl``` is not being set.

**Comment by theotherp** [comment]
That's interesting. I don't understand why having the indexer's URL in the GUID matters.

**Comment by nosmokingbandit** [comment]
Do you have NZBHydra passing the actual URL to Watcher or do you use its own generated link.

Watcher pulls marked results from the database (so it can assign a 'bad', 'snatched', or 'finished' status to them as necessary, but filters out any results from indexers you no longer have active. It might be filtering the whole list instead of just the old results. I haven't looked at that code in a long time.

**Comment by theotherp** [comment]
I use Hydra's search result links.

I've only ever added Hydra to Watcher so it shouldn't interpret any of the indexers as inactive. It's possible that it checks if the host of the configured indexer appears in the search result link but that would be bad.

**Comment by nosmokingbandit** [comment]
The url in the config should match the base url of the nzbhydra link, no?

**Comment by untitledxi** [comment]
If you're proxying the results, ```NZBHydra``` always returns an internal url.

**Comment by untitledxi** [comment]
I think filtering results by searching for active/inactive is useless as there should never be results from inactive indexers anyway. An inactive indexer should never be queried.

To make it a bit clear, this is my setup:

* ```NZBHydra``` behind nginx.
* ```watcher``` setup to use ```NZBhydra``` as indexer, using nginx FQDN

When you enable ```useLocalUrlForApiAccess``` or have an empty ```externalUrl``` in ```NZBHydra```, the search results are always using the internal IP, i.e.

```http://127.0.0.1/?apikey=```

And watcher filters them out, because they do not match the indexer url setup in settings, which is:

```http://<fqdn>/?apikey```

This is easily fixed by leaving a note in README/Wiki (i don't know in which project) or by removing the ```inactive``` filtering and simply query only the active indexers in ```watcher```

**Comment by theotherp** [comment]
I agree that it would make absolutely no sense to query inactive indexers. There's a reason they're disabled. But I'd like to hear what @nosmokingbandit has to say about this, perhaps you/we're assuming the wrong things.

**Comment by nosmokingbandit** [comment]
> Watcher pulls marked results from the database (so it can assign a 'bad', 'snatched', or 'finished' status to them as necessary, but filters out any results from indexers you no longer have active. It might be filtering the whole list instead of just the old results. I haven't looked at that code in a long time.

Please read what I write.

**Comment by untitledxi** [comment]
Yeah, sorry about that, haven't considered the caching layer with SQLite.

**Comment by untitledxi** [comment]
Pulled the latest, everything seems to be working fine, regardless of the settings chosen in ```NZBHydra```

**Comment by theotherp** [comment]
This is fixed for me. Don't ask why, I just made the first update after my last post and now it finds results.
