### ISSUE TITLE
import existing library triggers a snatch

### ISSUE THREAD

**Issue by SuperPotatoMen** [nosmokingbandit/watcher#220]
I imported my existing library it set a finished flag but it also triggers a search and snatching!!

**Comment by nosmokingbandit** [comment]
Easy oversight to fix. Fixed for me in ee814f41b0b0a18eb69ec4513dccd76847150f0d.

**Comment by SuperPotatoMen** [comment]
@nosmokingbandit if you push code to github and you use the #220 included with a text with fix or fixed blablabla it will auto close the issue. pritty nice feature of github :)

**Comment by SuperPotatoMen** [comment]
Thanks for the fix!
