### ISSUE TITLE
don't add "watcher" in nzb name

### ISSUE THREAD

**Issue by SuperPotatoMen** [nosmokingbandit/watcher#221]
Is it possible to don't add watcher in the nzb name?
My rename script will rename it with the watcher title and matching with a good subtitle will be difficult.

XXXXX 2016 MULTi 1080p BluRay x264-VENUE _**Watcher**_

**Comment by nosmokingbandit** [comment]
This was left over from some early post-processing test and doesn't do anything anyway.

Removed in 930f1526b11e8ba8640ad1e7e764645d14086174.
