### ISSUE TITLE
"api key" field must not be mandatory in providers settings

### ISSUE THREAD

**Issue by tl-pierre** [nosmokingbandit/watcher#223]
Hi, 
I try to add NZB-Hydra in my list of indexers in Watcher. With this indexer, it's possible to not generate api key, so I just want to complete the url field on Watcher.

#### What happened?
Error message : "Please complete or clear out incomplete providers." and impossible to save settings.

#### What was supposed to happen?
No error message :D (or just a warning message, it's true that an indexer without api key is not very common.)

#### How can I reproduce this?
Add an indexer in "providers settings" without api key.

Thank you for this beautiful application, I love it !

**Comment by nosmokingbandit** [comment]
Fixed in 65f3c684f886e2f38266ece0b1264537920a689f

You can give a url but no api key, but will still let you know if you gave an api key without a url.

**Comment by tl-pierre** [comment]
Great, thank you very much !
