### ISSUE TITLE
Import Library - Gathering Metadata

### ISSUE THREAD

**Issue by Poag** [nosmokingbandit/watcher#224]
**What happened?**

So i was trying to import my existing library, although i encountered an issue like #222 , renaming a few foreign character films corrected the issue and Watcher progressed to the next stage.

**What was supposed to happen?**

Import the existing library.

**How can I reproduce this?**
Attempt import

It gathered the metadata for all my films and then threw an error.

```
INFO 2017-02-21 07:47:03,376 core.library.get_metadata: Gathering metada for /movies/The.Thing.1982/The.Thing.1982.Bluray-1080p.mkv.
INFO 2017-02-21 07:47:04,630 core.sqldb.get_user_movies: Retreving list of user's movies.
ERROR 2017-02-21 07:47:04,938 cherrypy.error.47161362005840.error: [21/Feb/2017:07:47:04]  Traceback (most recent call last):
  File "/watcher/lib/cherrypy/_cpwsgi.py", line 189, in trap
    return func(*args, **kwargs)
  File "/watcher/lib/cherrypy/_cpwsgi.py", line 105, in __call__
    return self.nextapp(environ, start_response)
  File "/watcher/lib/cherrypy/_cpwsgi.py", line 439, in tail
    return self.response_class(environ, start_response, self.cpapp)
  File "/watcher/lib/cherrypy/_cpwsgi.py", line 245, in __init__
    self.run()
  File "/watcher/lib/cherrypy/_cpwsgi.py", line 348, in run
    request.run(meth, path, qs, rproto, headers, rfile)
  File "/watcher/lib/cherrypy/_cprequest.py", line 617, in run
    raise cherrypy.TimeoutError()
TimeoutError

INFO 2017-02-21 07:58:47,983 core.sqldb.get_user_movies: Retreving list of user's movies.
```

The final line is me clicking onto the status page after noting from the log that the import had failed.

**Comment by porkie02** [comment]
I was getting the same error too, if you remove the file and re scan it will continue. Trouble with that is I have quite a big library 600+ so its tedious to keep removing/re scanning. At least the import gets further than it did a day or so ago just this metadata problem now.

**Comment by nosmokingbandit** [comment]
I've been unable to replicate this. I've used all sorts of odd characters on both my Windows 10 and Debian servers and I haven't been able to force any errors.

What specific filenames are you having trouble with?

**Comment by porkie02** [comment]
It happens with standard named files for me, I can post a sample here or give you my full log from when I was removing and rescanning. If you want full log just say and I can email it or something to you.

INFO 2017-02-21 12:43:01,559 cherrypy.error.47268018076880.error: [21/Feb/2017:12:43:01] HTTP 
Request Headers:
  Content-Length: 46
  COOKIE: docker_listview_mode=advanced; dashapps_view_mode=allapps; session=f78c8270-4c6b-416c-b74c-37582c8e2bf3; list_style=compact; session_id=81405c5a40b97320a278a6f18a93de1e7ce11a6a
  HOST: 192.168.0.200:9898
  ORIGIN: http://192.168.0.200:9898
  CONNECTION: keep-alive
  Remote-Addr: 192.168.0.127
  ACCEPT: */*
  USER-AGENT: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36
  X-REQUESTED-WITH: XMLHttpRequest
  ACCEPT-LANGUAGE: en-GB,en-US;q=0.8,en;q=0.6
  Content-Type: application/x-www-form-urlencoded; charset=UTF-8
  REFERER: http://192.168.0.200:9898/import_library
  ACCEPT-ENCODING: gzip, deflate
ERROR 2017-02-21 12:43:01,560 cherrypy.error.47268018076880.error: [21/Feb/2017:12:43:01] HTTP 
Traceback (most recent call last):
  File "/watcher/lib/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/watcher/lib/cherrypy/lib/encoding.py", line 220, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/watcher/lib/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/watcher/core/ajax.py", line 644, in scan_library
    movies = self.library.scan_dir(directory, minsize, recursive)
  File "/watcher/core/library.py", line 48, in scan_dir
    movies[i] = self.get_metadata(i)
  File "/watcher/core/library.py", line 110, in get_metadata
    if width:
UnboundLocalError: local variable 'width' referenced before assignment

**Comment by nosmokingbandit** [comment]
It looks like a cherrypy setting I need to tweak. I found an Sabnzbd issue that dealt with the same timeout error, so I'm going to pick through that and see if I can apply a similar fix.

**Comment by nosmokingbandit** [comment]
Commit https://github.com/nosmokingbandit/watcher/commit/5d36cdd308c8454450e5629295feb11f5c4cd0f3 *should* fix this.

Cherrypy gives up if a process takes more than 5 minutes, which is going to happen when gathering metadata for a huge library. This update should fix that limit.

**Comment by Poag** [comment]
Alas, although it no longer errors at the end it just ends the gather process and stops.

`
INFO 2017-02-23 10:11:11,551 core.library.get_metadata: Gathering metada for /movies/The.Thing.1982/The.Thing.1982.Bluray-1080p.mkv.
INFO 2017-02-23 10:11:12,824 core.sqldb.get_user_movies: Retreving list of user's movies.
`

If i go through my movies one by one and import them its perfectly happy. The logs dont appear to show anything untoward occuring now that the error has gone.

**Comment by nosmokingbandit** [comment]
When you get to that point does your browser's javascript console show any errors?

Ctrl + Shift + J opens it in most modern browsers.

**Comment by Poag** [comment]
`
Dark-Soundjesterstyle.css Failed to load resource: the server responded with a status of 404 (Not Found)
Dark-Soundjesterimport_library.css Failed to load resource: the server responded with a status of 404 (Not Found)
Dark-Soundjesterimport_library.css Failed to load resource: the server responded with a status of 404 (Not Found)
scan_library Failed to load resource: the server responded with a status of 504 (Gateway Time-out)
Dark-Soundjesterstyle.css Failed to load resource: the server responded with a status of 504 (Gateway Time-out)
Dark-Soundjesterimport_library.css Failed to load resource: the server responded with a status of 504 (Gateway Time-out)
`

From the console log after attempting an import.

**Comment by nosmokingbandit** [comment]
That is strange. If you are getting a 504 the Watcher log should show that since it is considered an exception...

This might be similar to https://github.com/nosmokingbandit/watcher/issues/222, which I'm 90% sure I fixed (William didn't get back to me about that yet).

Were you having this error after that update or before?

**Comment by Poag** [comment]
To be honest prior to #5d36cdd i had not opened the Javascript console to check for errors. So..maybe?

It definately working. If i put 5-15 films in one folder and get it to scan that folder it'll happily add them in to the DB.
However if i run it against my full movie share it gets to the end of gather and then does not move onto the 'choose your imports' page. Its as if the processing waiting for the gather metadata process to finish has timed out and exited due to the time it takes to gather all the metadata.

**Comment by nosmokingbandit** [comment]
I think part of this problem was the list of import being sent to the backend before it was complete. I was able to pull off an import of 375 movies* in about 5 minutes.


*I don't have 375 movies, but I made fake movies to test this. They are just text files with an mkv extension and a movie title for the filename. But they get treated just like a movie except Watcher can't get the resolution from the video metadata. If anything this actually makes it a hair slower.

**Comment by jaketame** [comment]
Maybe related but I did at import on 800ish movies and it scanned them all in and collected the metadata however once it displayed all the movies at the bottom of the son output it did nothing and I can see existing movies.

INFO 2017-03-13 10:15:04,646 core.sqldb.get_user_movies: Retreving list of user's movies.
DEBUG 2017-03-13 10:15:04,648 core.ajax.scan_library: Sending import list to html template:
DEBUG 2017-03-13 10:15:04,698 core.ajax.scan_library: {
....
....
...
}
}
INFO 2017-03-13 11:36:46,442 core.rss.predb.check_all: Checking predb.me for new available releases.

**Comment by nosmokingbandit** [comment]
I don't understand what you are saying.

What didn't happen?

**Comment by jaketame** [comment]
Two things
1) It processed the library but didn't actually import anything.
2) Watcher is checking for metadata against each item... This doesn't play nicely with Google Drive... Are we able to pull the information from Plex itself?

**Comment by nosmokingbandit** [comment]
If google restricts file reading there isn't much I can do about that.

I'll check into the plex api. Importing from both plex and kodi would be nice.
