### ISSUE TITLE
Not listing any valid possible downloads

### ISSUE THREAD

**Issue by WilliamJBrown** [nosmokingbandit/watcher#225]
#### What happened?

No results are being shown when searching for a movie. It seems that the resolution/size match is removing all possible options. 

#### What was supposed to happen?

core.scoreresults.score_sources: Filtering resolution and size requirements.

This removes all possible downloads from this list and then returns 0 results. 

```
INFO 2017-02-23 00:44:51,850 core.scoreresults.remove_ignored: Keeping 99 results.
INFO 2017-02-23 00:44:51,850 core.scoreresults.retention_check: Checking retention.
INFO 2017-02-23 00:44:51,851 core.scoreresults.retention_check: Keeping 99 results.
INFO 2017-02-23 00:44:51,852 core.scoreresults.seed_check: Checking torrent seeds.
INFO 2017-02-23 00:44:51,852 core.scoreresults.seed_check: Keeping 99 results.
INFO 2017-02-23 00:44:51,852 core.scoreresults.score_sources: Filtering resolution and size requirements.
INFO 2017-02-23 00:44:51,852 core.scoreresults.score_sources: Keeping 0 results.
INFO 2017-02-23 00:44:51,852 core.scoreresults.fuzzy_title: Checking title match.
INFO 2017-02-23 00:44:51,852 core.scoreresults.fuzzy_title: Keeping 0 results.
INFO 2017-02-23 00:44:51,852 core.scoreresults.score_preferred: Scoring Preferred Words.
```

This happens for all movies I have tried searching. Old and new. It seems that the filter for resolution/size is too aggressive or not filtering correctly. 

#### How can I reproduce this?

Search a movie? 

On a side note I miss the basic 720p 1080p and size quality profiles. It seemed to pick up much more results and filtering out fake searches was easy with the ignored words section.

**Comment by nosmokingbandit** [comment]
Looking a little close at the output of a few methods is looks like
anything with DTS is being called a Telesync because it has TS in the
title. I'm betting almost everyone has Telesync disabled, so we are missing
out on a lot of goo quality search results. I've got a fix but I want to
run a few more rounds of searches.

I might entertain the idea of a 'basic' quality profile like the old method
and an 'advanced' profile like I have now. I want to get the stupid library
import figured out before I work on any other major changes first, though.

**Comment by WilliamJBrown** [comment]
I loved the basic quality profile settings. Also my library import works now. Just doesn't match a lot of IMDB up. About half of my titles matched with a IMDB number.

**Comment by WilliamJBrown** [comment]
Can confirm it looks like ts, was removing the results. All good now.

**Comment by nosmokingbandit** [comment]
I saw in your log that a movie was missing the imdb number, but it shows up on both TMDB and IMDB using the imdb number... I'll have to play around with their api a bit more and see if the results are formatted differently some times.

Regardless, after commit 14447ea72a4064373405bad0338434c3e36d9fb0 you can put 'ts' back in your telesync aliases, it won't call DTS a telesync any more.
