### ISSUE TITLE
Feature request: File size displayed on movie information

### ISSUE THREAD

**Issue by WilliamJBrown** [nosmokingbandit/watcher#226]
When importing the library I see there is the file sizes listed. Would it be possible to put that also in the movie information panel. That way we can keep track of file sizes and quality of out library. 

[Example](https://gyazo.com/152da910ca0d2f69309aa8b227dfe09d)

Not a major request would just be a nice addition. Kind of keep tabs on the library. 

Keep up the great work :)

**Comment by nosmokingbandit** [comment]
When you import a movie it is supposed to create a fake search result:
http://i.imgur.com/BURpS6a.png

And it did. But it also deleted it the next time the movie was searched for. It originally worked fine but after changing the default encoding the title matches got a little weird and it was checking the import size. As of commit https://github.com/nosmokingbandit/watcher/commit/346cd0acefea30d64ba7cdb5ad5d51486d4b6241 there should be no circumstance that deletes an 'import' search result. It won't bring back those that already were deleted, of course, but it is back to the way it is supposed to be.

**Comment by nosmokingbandit** [comment]
Closed for inactivity. Comment if we need to keep this open.
