### ISSUE TITLE
Trigger a re-download of metadata

### ISSUE THREAD

**Issue by calebcall** [nosmokingbandit/watcher#228]
I'm running my watcher in a docker container.  Works great except that I had to recreate my container because I had mapped the drives incorrectly.  Not a big deal except that upon recreation, I kept all my movie statuses (Wanted, Snatched, and Found) but lost all the metadata so now I no longer have any cover art.  

Is there a way to trigger a re-download of that info?

**Comment by nosmokingbandit** [comment]
There is not (other than deleting all of the movies and re-importing, which sounds like a dreadful job).

The posters are stored in `watcher/static/images/posters`, so if you happen to have your old directory around you can just copy them to whatever you have the container mapped to now.

Posters are named using their imdb #, ie `tt0063350.jpg`

I might add a method to refresh the metadata. It would be on a movie-by-movie basis so we don't hammer the api with a refresh call on a few hundred movies. Either way, that is going to be pretty low on the to-do list.

**Comment by nosmokingbandit** [comment]
In commit 324dc55752623c7c808993f27f3998df0450f5bb you can update metadata in the movie's status page. Click the refresh button next to the search button and the data will re-download. You'll have to refresh the page to the see effects, but it will update scores, re-grab the poster, etc.

I'm going to close this, but let me know if you have any trouble.

**Comment by calebcall** [comment]
nice job, upon initial testing it works great!
