### ISSUE TITLE
Some Icons Not Showing in FF

### ISSUE THREAD

**Issue by whispy** [nosmokingbandit/watcher#232]
#### What happened?

Icons are not showing up in the results list: https://vgy.me/giUgDz.png. The icons above the results list appear fine.

#### What was supposed to happen?

The icons should show up.

#### How can I reproduce this?

Using FF v52. The icons show fine in Chrome Canary. The issue was present before the release of FF v52. I have `gfx.downloadable_fonts.woff2.enabled` set to true in my `about:config`, so that is not the issue.

**Comment by whispy** [comment]
After playing with it a bit, if I set the `.fa` to `display: block`, instead of `display: inline-block`, then the icons appear (albeit positioned incorrectly). Perhaps it's an issue with that? Or with the `::before` pseudo element and `inline-block` together?

**Comment by nosmokingbandit** [comment]
Firefox seems to render fonts quite a bit differently than Chrome. The problem is the spans being slightly too wide, pushing the buttons span down below.

I have the css fixed, i'll push the update later today. I'm just going to change the width of `span.name` to `width: calc(100% - 4.5em);`
