### ISSUE TITLE
Cannot connect with Deluge 1.3.14 (.13 works)

### ISSUE THREAD

**Issue by ItsMeMike** [nosmokingbandit/watcher#234]
#### What happened?
Deluge updated their client to 1.3.14. This breaks something.
#### What was supposed to happen?
Watcher connects to Deluge without a problem
#### How can I reproduce this?
Install the latest Deluge and try to connect.

```ERROR 2017-03-11 10:25:06,117 core.downloaders.deluge._login: DelugeWeb test_connection
Traceback (most recent call last):
  File "C:\watcher\core\downloaders\deluge.py", line 236, in _login
    response = urllib2.urlopen(request)
  File "C:\Python27\lib\urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python27\lib\urllib2.py", line 437, in open
    response = meth(req, response)
  File "C:\Python27\lib\urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Python27\lib\urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "C:\Python27\lib\urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "C:\Python27\lib\urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 500: Internal Server Error
```

Running Deluge on Windows 10 x64, tried connecting with and without password on localhost & pc-name & ip-address.

**Comment by nosmokingbandit** [comment]
Commit https://github.com/nosmokingbandit/watcher/commit/cf45a589e5792b684d57c41aaa1143fb98bcdc8a should restore compatibility with the WebUI. I don't think the rpc methods were affected at all.

Sending torrent files has broken, so only magnet links will go through. I posted on their forum to see what the deal is. Deluge's dev is pretty great so I'm sure we'll get that sorted out.

**Comment by ItsMeMike** [comment]
Cool, I will update and see if it connects via webUI. Keep up the good work 😄

**Comment by ItsMeMike** [comment]
Connection works, and torrent gets send to Deluge indeed. However label is not send along with it.

**Comment by nosmokingbandit** [comment]
This is normal. The files will download to your normal download dir/category. For example `/home/mike/downloads/deluge/Watcher`

I don't remember exactly why I did it like this, but there was a good reason.

**Comment by ItsMeMike** [comment]
It's a bummer that the Execute plugin cannot read the label of a torrent. I remember having to fill it out in the post script.

They are not only cosmetic by the way. You can set the labels to move the downloaded files into a separate location. It is in the left sidebar, when you right click on a label and choose options.
Example:
Default folder = Downloads
Movies label = Downloads/Movies
TV Shows label = Downloads/TV Shows

This way you can set different programs to send a label to the client, to make sure everything is neatly placed in different folders for post processing scripts.

**Comment by nosmokingbandit** [comment]
Commit b60495e44567446b26287e7f3ca6e9360740c401 fixes sending torrents to Deluge, so I'm going to close this.
