### ISSUE TITLE
got a KeyError: 'finisheddate' 

### ISSUE THREAD

**Issue by SuperPotatoMen** [nosmokingbandit/watcher#235]
Having a problem? Bummer. Watcher is under constant development, so bear with us while we sort this out.

Meanwhile, you can help us get this fixed more quickly by following this format:

#### What happened?
Its look like one of a taskscheduler failed to run after the last update
```
Exception in thread Thread-34:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\Python27\lib\threading.py", line 1073, in run
    self.function(*self.args, **self.kwargs)
  File "C:\watcher\watcher-master\core\cp_plugins\taskscheduler.py", line 114, in task
    self.func()
  File "C:\watcher\watcher-master\core\searcher.py", line 86, in auto_search_and_grab
    rss_movies = self._get_rss_movies(movies)
  File "C:\watcher\watcher-master\core\searcher.py", line 435, in _get_rss_movies
    finisheddateobj = datetime.datetime.strptime(i['finisheddate'], '%Y-%m-%d').date()
KeyError: 'finisheddate'
```

#### How can I reproduce this?

Including logs of the event are often neccessary to find out exactly what is going on.
If the log section is short feel free to post is here, but make sure to remove any personal information (ie IP address) and remove any references to movie or release titles.
If the logs are long, or require release title names to troubleshoot, submit an issue here, then send the logs to watchernzb@gmail.com.
Put a link to your issue in the email body so we know exactly who it belongs to.

**Comment by nosmokingbandit** [comment]
What blows my mind is that this error didn't come up sooner. In a *very* old database schema it was called finisheddate, then I decided I like underscores and changed it. But that was several months ago.

Commit b2b428ee096de7c3acb5eccee6f965efb710206d should take care of this.
