### ISSUE TITLE
Score and filter titles seems to be too aggressive in it's filtering

### ISSUE THREAD

**Issue by calebcall** [nosmokingbandit/watcher#237]
Having a problem? Bummer. Watcher is under constant development, so bear with us while we sort this out.

Meanwhile, you can help us get this fixed more quickly by following this format:

#### What happened?
Valid Results are being incorrectly filtered

#### How can I reproduce this?
Don't know, see the logs for a release that wasn't working.

#### What else do I need to know?
Running in a docker container

I've emailed the logs to you.

I found if I disable the "Score and filter titles" option, it finds all the results I expect it to.

**Comment by nosmokingbandit** [comment]
Thanks for the logs, super helpful. I'm getting the update ready now.

**Comment by nosmokingbandit** [comment]
Fixed in https://github.com/nosmokingbandit/watcher/commit/16df5d5eff56e2f168369765deed26c57cd95f2b

I can confirm it works for the example you sent as well as a few other oddities. Let me know if it still acts dumb. Until then I'm closing this.
