### ISSUE TITLE
Term search TorzNab gives 0 results 

### ISSUE THREAD

**Issue by shippern** [nosmokingbandit/watcher#239]
#### What happened?
Searching using TorzNab is broken if using term instead of imdbid

#### How can I reproduce this?
Try to search for a movie that has spaces in it using its term instead of imdbid.

#### What else do I need to know?
Below is the logged search
```
INFO 2017-03-19 11:45:50,127 root.search_newznab: SEARCHING: http://localhost:9117/torznab/TRACKER/api?apikey=APIKEY&t=search&cat=2000&q=movetitlethathasspacesandstuff2007
```
Notice that the search term doesn't contain `+`s as spaces but it is instead just one big string and thus gives 0 results.

The problem is that the spaces has been removed instead of being url encoded `+`s.

It looks like this commit 16df5d5eff56e2f168369765deed26c57cd95f2b has caused this, where `encode` has been changed.

For example
`Url.encode('move title that has spaces and stuff 2007')` result in `'move+title+that+has+spaces+and+stuff+2007'`

`Url.encode('move+title+that+has+spaces+and+stuff+2007')` result in `'movetitlethathasspacesandstuff2007'`

If the string to be encoded already has `+`s instead of spaces, then the `+`s will be removed.

Let me know if you need more information to address this.

I am not sure why it doesn't search using imdbid and has to fallback to term search. I will investigate that separately.

**Comment by nosmokingbandit** [comment]
a7fe5b93c3cabf0e65977cf1808539734dee2400 Should take care of this. Let me know.

**Comment by shippern** [comment]
a7fe5b93c3cabf0e65977cf1808539734dee2400 fixes the issue with searching using a term and TorzNab. Thank you!

I'm closing this one and we can continue the discussion around imdbid and term over at #241
