### ISSUE TITLE
TorzNab always search by term and never imdbid

### ISSUE THREAD

**Issue by shippern** [nosmokingbandit/watcher#241]
#### What happened?
Searching using TorzNab will always result in a term search and not the more accurate imdbid search

#### How can I reproduce this?
Search using TorzNab and see from the logs that it searches using term and never using imdbid

#### What else do I need to know?
The problem seems to be here https://github.com/nosmokingbandit/watcher/blob/master/core/providers/torrent.py#L53. The imdbid is not passed to the search method, but only the search term.

**Comment by nosmokingbandit** [comment]
See my explanation here:
https://github.com/nosmokingbandit/watcher/issues/239

The short answer is that neither Jackett or Cardigann follow newznab spec, so this is the only method that works for both of them.

**Comment by shippern** [comment]
I added your comment from #239 for context

> edit:
Just ran a quick test.
Using Jackett with TPB searching an imdbid returns 0 results. Searching the title+year gets 29 results, all of which are valid.
edit2:
Seems like Torznab doesn't exactly follow newznab spec. I was able to search with imdbid as the q= param rather than imdbid= param like newznab spec states. I want to test a bit more, but if it is consistent I'll push that out later today.
edit3:
Upon further testing I'm back to where I started. Cardigann won't find anything with q=tt0123456 and returns a 502 on imdbid=tt0123456.
So since neither Jackett or Cardigann follow newznab spec the only way to make it work with both is to search with q=title+year

I unfortunately have experienced examples of movies that would give 0 or only few results when searching using terms. Sometimes the name of the movie given by the TMDb contains words that is not a part of what the releases are called and thus they will not show up when searching by title+year. Searching using imdbid fixes this and thus I believe it would improve the result if imdbid was used as often as possible.

I tried setting up both Jackett and Cardigann and also experienced different behaviours.

Jackett only supports using the `imdbid` parameter if the `t` is set to `movie`.
`http://JACKETT/torznab/TRACKER/api?apikey=APIKEY&t=movie&imdbid=IMDBID`

Cardigann on the other hand doesn't support the type `movie` but instead expects the `imdbid` parameter to be used with `search`.
http://CARDIGANN/torznab/TRACKER/api?apikey=APIKEY&t=search&imdbid=IMDBID

As you mention Jackett also support using an imdbid as the value for the `q` parameter, however I also found that this was supported by Cardigann.
http://JACKETT/torznab/TRACKER/api?apikey=APIKEY&t=search&q=IMDBID
http://CARDIGANN/torznab/TRACKER/api?apikey=APIKEY&t=search&q= IMDBID

I found that both of these returned many results. Can you please try to test this out once again?

Thank you in advance.

**Comment by nosmokingbandit** [comment]
After testing as many combinations of types and search parameters as I could think of there is only one that gets results from both Cardigann and Jackett:

`t=search&q=tt0087928`

This doesn't follow [newznab spec](http://newznab.readthedocs.io/en/latest/misc/api/), so brute-forcing it like this is the only way I would have figured it out.

The class I wrote for interacting with newznab is kind of built around newznab spec, so I'll have to do a quick re-write. Shouldn't be too bad. I'll let you know when I push the update.

**Comment by nosmokingbandit** [comment]
Commit da26a4d5ece96ad07e8cc76d1a6f813073b1124a changes all torznab searches to `t=search&cat=2000&q=tt0087928`

I've tested it to work with both Cardigann and Jackett using ThePirateBay feed.

**Comment by shippern** [comment]
I updated to my commit sha was at 8116e47. I tested with Jackett and found that it did the following search:
http://JACKETT/torznab/TRACKER/api?apikey=APIKEY&imdbid=tt3748528&t=search&cat=2000

As you can see the `imdbid` parameter is used instead of the `q` parameter for the imdbid. This is not supported by Jackett when using `t=search`

**Comment by nosmokingbandit** [comment]
I was typing faster than I was thinking. Happens too often.

77434bfef95da8e7e6ff16672f200a4d077c82b2 corrects this. This search method doesn't work with every indexer (ie Torrentz2) but TPB gets results from both Jackett and Cardigann.

I think the only way for this to be identical to newznab is for Jackett and Cardigann to convert imdbids to titles on their side and use that to search indexers that don't support imdbid searches.

**Comment by shippern** [comment]
Thanks, I can confirm that it works great.

If someone is using an indexer where this method doesn't work, I guess a work around could be to add a setting where you can specify if it should search by term or imdbid.

I'm closing this for now since the issue has been resolved.

**Comment by OldMike** [comment]
Hi,

Sorry to reopen but my Watcher can't find anything using Jackett on a famous French site "T411". Here's an example for Rogue One but it can't find anything. What did I miss?

Watcher build: Current version hash: de13996
"Nothing found yet."
Logs
[code]INFO 2017-03-26 07:26:41,276 core.sqldb.get_user_movies: Retreving list of user's movies.
INFO 2017-03-26 07:26:41,054 core.sqldb.get_search_results: Retreving Search Results for tt3748528.
INFO 2017-03-26 07:26:40,801 core.searcher.search: 0 results found.
INFO 2017-03-26 07:26:40,801 core.sqldb.get_search_results: Retreving Search Results for tt3748528.
INFO 2017-03-26 07:26:40,191 root.search_newznab: SEARCHING: http://xxx:xx/torznab/hdonly/api?apikey=APIKEY&q=tt3748528&t=search&cat=2000
HTTPError: HTTP Error 500: Internal Server Error
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
  File "/usr/lib/python2.7/urllib2.py", line 558, in http_error_default
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 475, in error
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 550, in http_response
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 437, in open
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    r = urllib2.urlopen(request, timeout=timeout)
  File "/home/mike/watcher-master/core/helpers.py", line 58, in open
    response = Url.open(request)
  File "/home/mike/watcher-master/core/providers/base.py", line 50, in search_newznab
Traceback (most recent call last):
ERROR 2017-03-26 07:26:40,191 root.search_newznab: Newz/TorzNab backlog search.
INFO 2017-03-26 07:26:39,389 root.search_newznab: SEARCHING: http://xxx:xx/torznab/elitetracker/api?apikey=APIKEY&q=tt3748528&t=search&cat=2000
INFO 2017-03-26 07:26:38,282 root.search_newznab: SEARCHING: http://xxx:xx/torznab/xthor/api?apikey=APIKEY&q=tt3748528&t=search&cat=2000
INFO 2017-03-26 07:26:37,511 root.search_newznab: SEARCHING: http://xxx:xx/torznab/qctorrent/api?apikey=APIKEY&q=tt3748528&t=search&cat=2000
timeout: timed out
    data = self._sock.recv(self._rbufsize)
  File "/usr/lib/python2.7/socket.py", line 476, in readline
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/lib/python2.7/httplib.py", line 400, in _read_status
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 444, in begin
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 1111, in getresponse
    r = h.getresponse(buffering=True)
  File "/usr/lib/python2.7/urllib2.py", line 1200, in do_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1227, in http_open
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 449, in _open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 431, in open
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    r = urllib2.urlopen(request, timeout=timeout)
  File "/home/mike/watcher-master/core/helpers.py", line 58, in open
    response = Url.open(request)
  File "/home/mike/watcher-master/core/providers/base.py", line 50, in search_newznab
Traceback (most recent call last):
ERROR 2017-03-26 07:26:37,511 root.search_newznab: Newz/TorzNab backlog search.
INFO 2017-03-26 07:26:07,487 root.search_newznab: SEARCHING: http://xxx:xx/torznab/t411/api?apikey=APIKEY&q=tt3748528&t=search&cat=2000
INFO 2017-03-26 07:26:05,884 core.sqldb.get_search_results: Retreving Search Results for tt3748528.
INFO 2017-03-26 07:26:05,883 core.sqldb.get_movie_details: Retreving details for tt3748528.[/code]
