### ISSUE TITLE
Feature request: Multiple/Custom download directories

### ISSUE THREAD

**Issue by Arathen** [nosmokingbandit/watcher#243]
Can the ability to post process and move files into multiple and/or custom destination folders on a per-movie basis be added please? For example, childrens movies move to one location, adult movies to another.

Many thanks :)

**Comment by nosmokingbandit** [comment]
I'll think about it. It would take a good bit of work to add post-processing profiles.

I'd probably rather add the quality profile to the info passed to a post-processing plugin. Then after Watcher is done you can see if the profile was 'Children' and move it wherever you like.

**Comment by nosmokingbandit** [comment]
The `{quality}` tag was always available, but 948e69cc2ee95a26593b472befb9a5a13002ed1f actually lists it.

You can set the mover path to `/home/arathen/movies/{quality}/{title} ({year})` and your movies will get sorted as `/home/arathen/movies/Kids Movies/Gulliver's Travels (1939)`

There are no plans to add more depth to post-processing for now.
