### ISSUE TITLE
Feature request: Allow movie selection based on FreeLeech flag

### ISSUE THREAD

**Issue by Arathen** [nosmokingbandit/watcher#244]
Many sites offer FreeLeech as a download type, particularly for large files. Jackett also passes through the FreeLeech flag to the searching client when it exists. It would be great if Watcher could select a download based on whether or not that FreeLeech flag was present.

Cheers :)

**Comment by nosmokingbandit** [comment]
I don't have an account at any sites that employ freeleech. If anyone wants to invite me somewhere I'll be able to check it out.

**Comment by nosmokingbandit** [comment]
I gained access to a site with freeleech torrents.


Commit 6b80c56f632f30ca6fe456b6ccdd2798ef17f44f allows you to add an arbitrary amount of bonus points for freeleech torrents.

Search results are sorted by score > size > freeleech flag. Without extra points Watcher will prefer a freeleech when sizes and scores are identical.
