### ISSUE TITLE
API Key not being redacted in logs

### ISSUE THREAD

**Issue by bgavin** [nosmokingbandit/watcher#246]
#### What happened?
My API Key isn't being removed from all locations in the logs. Early in a search, the API Key is replaced with "APIKEY", but later in the logs, it is left in plain text.

#### How can I reproduce this?
Search for a movie.

#### What else do I need to know?
See email with same subject. Log included in email.

2012r2
Python 2.7.13
Git 2.12.0

**Comment by nosmokingbandit** [comment]
Commit 917bcbd65135969435d4828fdfccdf55fb6bd7cd should take care of this. The log will be truncated to the actual nzb file, removing user auth information.

Thanks for the logs, always helpful.

**Comment by bgavin** [comment]
Hey, 
Thanks for looking into this.
I sent another log. The api key is still showing... 

If it helps, this is my build number as displayed in Watcher: Current version hash: 625f192

**Comment by nosmokingbandit** [comment]
There were s few I missed, but I'm pretty sure 8116e47213edd1147c7de7b5d364c21e4752c041 got them all.

**Comment by bgavin** [comment]
It looks like you got them all now. Thanks!
