### ISSUE TITLE
Alternative name(s)? Example inside

### ISSUE THREAD

**Issue by ItsMeMike** [nosmokingbandit/watcher#247]
#### What happened?
A movie that was added a long time ago can be found on the web for a couple of days now.
Watcher ignores 99% of the results because of the title that it uses in the releases vs. the original promotional title.
#### How can I reproduce this?
Search for "Rogue One". You know which one to add ;)
Watchers places it in the library as: Rogue One: A Star Wars Story 2016
This is not wrong.
Looking at the logs for a good example:
```
DEBUG 2017-03-21 18:52:38,598 core.scoreresults.fuzzy_title: rogue+one+2016+1080p+bluray+x264+sparks only matched 52\% of rogue+one+a+star+wars+story, removing search result.
```
So a good solution would be to take in account all the alternative names from IMDb (http://www.imdb.com/title/tt3748528/releaseinfo#akas) Or the option to choose the title?

#### What else do I need to know?
I think this is enough, if not just reply. Happy to help.

**Comment by nosmokingbandit** [comment]
I noticed this a few days ago and just started looking into it. I'm a little surprised that release groups didn't use the full title, but I can get a list of alternative titles from tmdb and see if any of those match the title. It makes title matching a little less reliable, but I don't think there is any other way to do it.

**Comment by ItsMeMike** [comment]
Well, the title that is picked now can stay. Let the user pick another title if needed.
In the end, still only 1 title is used, making the algorithm just as good.

I am curious though as why it still picks 'Rogue One: A Star Wars Story', since the title on IMDb is changed to only 'Rogue One'.

**Comment by nosmokingbandit** [comment]
Because I use [themoviedb](https://www.themoviedb.org/movie/330459-rogue-one-a-star-wars-story). Imdb doesn't have an api.

**Comment by shippern** [comment]
This issue is related to #241

**Comment by nosmokingbandit** [comment]
Not exactly.

Commit 625f1927c9198a2a9f747e70209125f55c16f237 uses tmdb's alternative titles to check for a title match when filtering/scoring results.

@shippern
I'll get back to you about that soon. I want to run as many tests as I can think of before I start tweaking anything.

I'm closing this since the actual issue is resolved.

**Comment by shippern** [comment]
This fix breaks searching for movies that were added before the fix since they do not have the `alternative_titles` in the database. Trying to search for a movie that has added before the fix gives the following trace. Removing and adding the movie fixes the problem for that movie.

```
AttributeError: 'NoneType' object has no attribute 'split'
    titles = movie_details['alternative_titles'].split(',') + [movie_details['title']]
  File "/home/pi/watcher/core/scoreresults.py", line 53, in score
    scored_results = self.score.score(results, imdbid=imdbid)
  File "/home/pi/watcher/core/searcher.py", line 187, in search
    self.searcher.search(imdbid, title, year, quality)
  File "/home/pi/watcher/core/ajax.py", line 276, in search
    return self.callable(*self.args, **self.kwargs)
  File "/home/pi/watcher/lib/cherrypy/_cpdispatch.py", line 60, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/home/pi/watcher/lib/cherrypy/lib/encoding.py", line 220, in __call__
    response.body = self.handler()
  File "/home/pi/watcher/lib/cherrypy/_cprequest.py", line 670, in respond
Traceback (most recent call last):
```

**Comment by nosmokingbandit** [comment]
Fixed in https://github.com/nosmokingbandit/watcher/commit/9840ff7f2ccea75d539c850d15824a2c58789dde
