### ISSUE TITLE
Create QPKG - package fos QNAP NAS.

### ISSUE THREAD

**Issue by antakar** [nosmokingbandit/watcher#249]
I do understand it is early work in progress, but i wanted to suggest that having ready package may make this service much more popular and speed up the release of the final version.
This is due to more people using, testing and raising defects.

Great job gents, and thank you for this awesome service!

**Comment by nosmokingbandit** [comment]
Everything is a work in progress. There will never be a 'final version' of Watcher. At least not intentionally.

If someone wants to make a package go for it. I am the only person writing Watcher, so tertiary things like a qnap package or docker containers is left to the community to assemble.
