### ISSUE TITLE
Move movies into folders organized by letters

### ISSUE THREAD

**Issue by notexe** [nosmokingbandit/watcher#25]
Hi,

My current setup is organized like this:
\#  - This one is for movies starting with a number
A
B
C
D
And so on for my movies.

I'm wondering if you can add support for this in a feature update, it would be awesome.

Thank you.

**Comment by notexe** [comment]
Damn Github formatting my text.

**Comment by Aireezz** [comment]
It would be cool to see this added but instead of letters, sort by quality. Below is an example, and how I currently have mine set up.

1080p
720p
576p
480p
360p

**Comment by nosmokingbandit** [comment]
You can put

`{resolution}` 

In the mover field and it will create a folder with that releases resolution.

ie:

`/Users/Linus/Movies/{resolution}/{title} {year}/`

Will move it to

`/Users/Linus/Movies/1080P/This Is A Movie 2017/`

**Comment by nosmokingbandit** [comment]
While not a direct fix for what you were asking, you can now use plugins to sort things any way you see fit.

Look at commit https://github.com/nosmokingbandit/watcher/commit/73e2ed01548d32db97b1868482c1cc1d653cfb63
https://github.com/nosmokingbandit/watcher/wiki/Plugins

I'm going to go ahead and close this.
