### ISSUE TITLE
Movie search hosts unable to find some recent movies

### ISSUE THREAD

**Issue by j-shade** [nosmokingbandit/watcher#26]
Hi,

I was wondering if the sites used to find movies to add to the list of wanted movies could be expanded? I just tried searching for Passengers (the 2016 one) and it couldnt be found. This happened with a few other movies which i know were spelt correctly, so thought it might be a movie indexer issue?

Otherwise great work! 👍 

EDIT: It appears testing the OMDB API reveals that the searching works fine, it just doesnt return the latest movie.. if i append the year on https://www.omdbapi.com/ example it finds it, if i dont, it finds the 2008 version just like watcher

http://www.omdbapi.com/?type=movie&r=json&s=Passengers&y=2016 returns as expected
http://www.omdbapi.com/?type=movie&r=json&s=Passengers returns as watcher

**Comment by j-shade** [comment]
It appears testing the OMDB API reveals that the searching works fine, it just doesnt return the latest movie.. if i append the year on https://www.omdbapi.com/ example it finds it, if i dont, it finds the 2008 version just like watcher

**Comment by nosmokingbandit** [comment]
This seems to be a weird bug in their API. Searching on their site with the imdbid turns up the correct movie as well.

So there really isn't much I can do about this, but I'm going to leave this open. I'll add an ability to the search method to accept an imdb id instead of a title, so if something like this pops up again we'll still be able to find the correct title.

**Comment by kaibosh** [comment]
IMO the ability to add by imdbid would be very useful, especially if this could be exposed via API sometime in the future.

**Comment by soundjester** [comment]
@kaibosh The API actually does have that. [Check the wiki for API usage and format info](https://github.com/nosmokingbandit/watcher/wiki/API).

**Comment by nosmokingbandit** [comment]
I'm half tempted to try to switch to https://www.themoviedb.org/, but I haven't found any good way to get an imdb id # from their results, and I need the imdb # to search predb for releases.

**Comment by nosmokingbandit** [comment]
This should help: https://github.com/nosmokingbandit/watcher/commit/f96ad0976c59191216840eff4af6ba64de671680

You can now search for a imdb number (ie 'tt1234567'), or add the year to your search (ie 'Assassin's Creed 2016') and it should come up with the exact result you want.

**Comment by kaibosh** [comment]
Awesome, thanks!
