### ISSUE TITLE
Post-Processing Mover

### ISSUE THREAD

**Issue by Firemad03** [nosmokingbandit/watcher#28]
Hi,

First of all I want to congratulate you about your software. I love it. Simpler, easier and faster then CouchPotato. If more people know about your software CouchPotato will have a hard time.

I have an issue about the post-processing when Watcher try to move the movie after the download is finish.

I put this string: /mnt/Plex/Movies/{title} {year} {resolution} {videocodec} {audiocodec} and the Jail have access to it with a full write and I tried it manually to make sure that it wasn't a permission problem.

I found the logs and the logs doesn't show anything about it. The Jail have access to the source file but I can't confirm what watcher really saw for the source path and maybe I did something wrong.

Let me know where that I can check the source path that he needs.

Thanks

**Comment by Firemad03** [comment]
I checked the logs and I saw that Watcher snapped and searched well the movie and sent it to SABnzbd but I never saw something like: I grapped it from SABnzbd and I moved it somewhere or I try to do it but I got an errors.

I think the feature doesn't work if the logs doesn't show anything ?

**Comment by Firemad03** [comment]
My bad it's my fault. I didn't read the part about the Post Processing:

"Watcher supports post-processing for Sabnzb and NZBGet. To enable, copy the appropriate script from watcher/post scripts to your downloader's scripts directory."

I expected an error somewhere ;) logs or in the webpage. 

I will leave it open for the error message if you want to add one but you can close it since it's working fine.

**Comment by nosmokingbandit** [comment]
Cool bean, sorry for the delayed response. This has gotten more popular than I expected in a short amount of time.

But I will say this.

> CouchPotato will have a hard time.

Its not a competition. CP is one way of doing something and Watcher is my way. Some people will like CP more, and that is fine. I didn't make this to take users from CP. We are all in this thing together.
