### ISSUE TITLE
Add a link to the GitHub inside the webpage

### ISSUE THREAD

**Issue by Firemad03** [nosmokingbandit/watcher#29]
Hi,

I suggest that you add a link inside the webpage for the GitHub or the website if you have any because I had a hard time to find it again on google ;) 

I suggest that the logo Watcher is clickable also to the Github/Website.

I suggest that you add a button if someone want to request a feature or submit a bug that they can click on it and it will redirect to the Issue webpage ;)

Maybe add your name with the developers also on a page and a way to contact you :) since the software is great it's can give you free publicity.

Maybe you have better ideas then mine :)

Thanks

**Comment by soundjester** [comment]
A link to the git _is_ a nice idea. A small, simple footer could accommodate this, and simply be pulled in with an include statement on the main page(s). Perhaps with a copyright mentioning the desired licensing. This will be important once awareness of this repo hits critical mass (which it will).  Perhaps this can be rolled in with CSS theming, once development reaches that milestone.

If the logo links anywhere, it should link back to the webroot/main page. Linking off-site is unexpected behavior.

Anything else, including listing main and major contributors and/or contact info can be listed in a text file within the git repo, once that point is reached.

**Comment by nosmokingbandit** [comment]
Added in commit https://github.com/nosmokingbandit/watcher/commit/77239011765dae4a75dbcb4afce1a9c0721961c0

An About page was always something I just never really got to, but this should help everyone understand exactly where to find more information about anything regarding the project.

**Comment by soundjester** [comment]
Groovy. I saw you also added a license. Nice!
