### ISSUE TITLE
Build or Version Number

### ISSUE THREAD

**Issue by Firemad03** [nosmokingbandit/watcher#34]
Hi,

I suggest a build or version number. I love btw the update button that is very easy but I don't know on what version I am. I don't see it anywhere on the webpage except that the update button is telling me that I'm on the latest version.

I suggest also to add a logs of what is new in the webpage. For example if I click on the check what is news button and I can see the changes and if I want and I'm happy I can click on the update button.

I suggest to add a reverse button too just in case something is broken and I want to reverse it back.

I'm sure you will have a better ideas to integrate it very well ;)

Thanks

**Comment by soundjester** [comment]
This is on the "Server" settings page in the lower right.  The version "number" is the git hash and automatically calculates/recalculates when you call for an update.  If you click the hash, it will take you to the latest commit log.

**Comment by Firemad03** [comment]
Your right. I never saw it 👍 :)
