### ISSUE TITLE
Feature Request: Add a profile for quality

### ISSUE THREAD

**Issue by Firemad03** [nosmokingbandit/watcher#35]
Hi,

I suggest to add a profile for the quality setting. 

If for example I want to search movies in french with different keywords and other movies in english with different keyword I can't. I will need to edit manually the movie or install another watcher.

I know that some movies I will prefer it in multi language and it's fine but some movies is only in french.

I'm sure others we will find the same problems with other language.

If I had the possibility to have multiple profile for the quality it will be great too. I add the movie and I select the profile that I want to use it for this one.

You can have also multiple profiles for different Quality for the movies. I want this movie only in SD but the other one I want it in 4k because I like it.

Thanks

**Comment by Quiksmage** [comment]
I want to be able to decide what gets categorized as BR-Rip, Screener, R5, etc based on its processing of the file name.

For instance,
One of the below terms should be in the file name to be matched at that quality.
Cam: HDcam, HD-TS, CAM, HDTS, TS, TELESYNC, HQHDT
Screener: DVDScr
WEB-DL: WEBRip, HDRip, WEB-DL,
DVD: DVDRip, DVD,
BR-Rip: BR-Rip, BRRip
720p: 720p BluRay, 720p Blu-Ray
1080p: 1080p BluRay, 1080p Blu-Ray

**Comment by nosmokingbandit** [comment]
Added in https://github.com/nosmokingbandit/watcher/commit/0c15a800a0fc27ae9342501809d634e89c3aae8d
