### ISSUE TITLE
sabnzbd.py arg error if I run it manually

### ISSUE THREAD

**Issue by Firemad03** [nosmokingbandit/watcher#39]
Hi,

I did a mistake inside the configuration file for the API and I wanted to run it again after my movie was downloaded from sabnzbd.

When I ran: python sabnzbd.py I got the following error: 
Post-processing failed. Incorrect args.

I understand that maybe if sabnzbd use it I won't get an error but at least we need an option to run it again or force the script to run it again instead of downloading the movie again.

I expected that he will do is job to move the file.

Thanks

**Comment by soundjester** [comment]
There is no way (that I know of) to force SAB to re-run a failed script.  That functionlity would have to be added to SAB, not this application.  To manually run the python script, you need to provide the following arguments like so:

`"/Path/to/the/downloaded.file.folder.Watcher", "NOTUSED","The.title.of.the.download.mkv.Watcher","NOTUSED","NOTUSED","NOTUSED",0`

so, for example, the call would look like this:

`python sabnzbd.py "/mnt/share/movies/Title.of.movie.1080p.Watcher", ,"Title.of.movie.1080p.Watcher", , , ,0`

**Comment by nosmokingbandit** [comment]
Yeah, this was a huge pain when testing. NZBGet has a method to re-execute post-processing scripts, but Sab doesn't. Doing it manually is kind of a pain as well.

If you are re-configuring, update and grab the latest post-processing scripts. I made a mistake in the Sab script, so you'll want the newest one. With any luck this will be the last post-script modification.

When testing I'd manually build the urls so I could test several times for the same download.

The full post-processing request looks like this:

`/postprocessing?apikey=*&mode=*&guid=*&path=*&downloadid=*`

apikey = your watcher key
mode = 'failed' or 'complete'
guid = url-encoded download link for the nzb
path = url-encoded filesystem path to download
downloadid = sab's nzo_id

This should probably be in the wiki. I'll eventually add documentation for it, but this isn't necessary 99% of the time (hopefully).

Anyway, there is nothing more I can do about this, so I'm closing the issue.
