### ISSUE TITLE
Add RSS support

### ISSUE THREAD

**Issue by kaboomwarrior** [nosmokingbandit/watcher#45]
Please add RSS support for new releases like sonarr does.

**Comment by nosmokingbandit** [comment]
I don't know what sonarr does. Explain this better.

**Comment by Crowley007** [comment]
I'll give it a try. To reduce load to the indexers, Sonarr does not search automatically for every missing episode, only when adding new shows or when telling it to do so manually. Instead, it uses the rss feed and matches missing episodes against that. Default setting refreshes the rss feed once in 15 minutes.

**Comment by nosmokingbandit** [comment]
Two full months, but you can't say I don't deliver.

See commit https://github.com/nosmokingbandit/watcher/commit/08c7ba821f666b67137d1f2f7f9ae8be25b6d8bc.

Its quite a bit different to do this for movies than it is for tv shows. Sonarr (as far as I know) doesn't store any search results, it just searches and grabs. But Watcher needs to store results to cover the waiting period, scoring the releases, getting a better copy, etc.

Check out the reddit post for a bit more of an explanation:
https://www.reddit.com/r/watcher/comments/5x0u0t/rss_sync_functionality/

But I think this works just fine.
