### ISSUE TITLE
Add custom dowload folders for downloaders

### ISSUE THREAD

**Issue by kaboomwarrior** [nosmokingbandit/watcher#47]
Add custom download folders for downloaders. This is most important for remote (not on the same machine) downloaders. Please see sonarr 'remote path mapping'.

**Comment by nosmokingbandit** [comment]
Downloaders can use a custom download path based on category. In addition, neither the [NZBGet](https://github.com/nzbget/nzbget/wiki/API-Method-%22append%22) or [Sab](https://sabnzbd.org/wiki/advanced/api#addurl) api allow for a download path to be passed along with an nzb add request.
