### ISSUE TITLE
[ Question ] Will watcher move the subtitles files that came with movie 

### ISSUE THREAD

**Issue by flixajki** [nosmokingbandit/watcher#49]
Will watcher move the subtitles files that came with movie

**Comment by porkie02** [comment]
yes it does, I was just looking through my folders to see how the renamer was working and it moved sub files

**Comment by soundjester** [comment]
I may be mistaken, but I believe that unpacking takes place in the particular downloader (NZBGet or SAB). The post-processing script only handles moving, renaming, and file cleanup.

**Comment by porkie02** [comment]
yeah the downloader handles the unpacking within its designated folder, this is a example image of what gets unpacked using the rename and move post process. 

https://i.imgur.com/BqxSLZV.png

All nice, clean and tidy and no leftovers which CP sometimes did.

**Comment by porkie02** [comment]
One thing if you use the postprocess script for for sab or nzbget, watcher will no longer put the files into its own folder with the subs etc. It works fine without the postprocess script but kinda need to use the script to tell watcher that the file is finished.

**Comment by nosmokingbandit** [comment]
Watcher is not set up to transfer anything except the actual movie file at this moment. I'll soon add the ability for the user to add a list of file extensions to move along with the movie (ie nfo, srt, etc).
