### ISSUE TITLE
API with basic information

### ISSUE THREAD

**Issue by tidusjar** [nosmokingbandit/watcher#50]
Hi! 

Can we add a new API endpoint where it just returns some version information?

Just so I can have a nice place to check if I can connect successfully to your service (From Ombi)

**Comment by nosmokingbandit** [comment]
Added in commit https://github.com/nosmokingbandit/watcher/commit/5c5f1f9a1ec55b65bdbdbeab24aaf860632acd08

`/api?apikey=*APIKEY*&mode=version`

Returns:
`{"version": "a1353128cb53e58a157734b1a81b1a48a79ced63", "response": "true"}`

If this is satisfactory let me know so I can close this issue.

**Comment by tidusjar** [comment]
That's perfect.  
Regarding the response messages,  that would be nice,  currently in some circumstances plain text is returned rather than Json too,  e.g. When the API key is incorrect

**Comment by tidusjar** [comment]
@nosmokingbandit if you make the wiki publicly editable I'll gladly add this to it.

**Comment by nosmokingbandit** [comment]
Wiki is open for editing. I thought I had done that before but apparently not :/

I like to always respond with a dict. It makes ajax responses easier to handle in javascript.
