### ISSUE TITLE
Add Movie page only returns 6 results

### ISSUE THREAD

**Issue by duckduckquack** [nosmokingbandit/watcher#52]
I haven't seen this mentioned, but searching for movies only returns 6 results.

**Comment by Firemad03** [comment]
I suggest to have an option to show more if we wanted to see other results.

**Comment by TheRealShiz** [comment]
For those having this issue you can add the year to the name of the movie restrict the results better and hopefully find your movie.

For example, when searching for "Lion" you will get some Lion King movies, etc. but you will not get Lion released this year.  Using "Lion 2016" as your search term will trim the results down to include the movie you are looking for in the top 6.

**Comment by duckduckquack** [comment]
@TheRealShiz I tried that earlier, and kept getting a blank page... Just updated to the latest and now search's work with the year...
