### ISSUE TITLE
Update failed

### ISSUE THREAD

**Issue by Scoboose** [nosmokingbandit/watcher#54]
watcher is failing to slelf update and telling me to look at the logs.  I have run watcher.py as admin on windows and it is getting an back up user files.  Here is my logs for the update.

`INFO 2016-12-28 18:26:12,990 core.version.update_check: Checking git for a new Zip.
INFO 2016-12-28 18:26:12,990 core.version.update_check: Getting local version hash.
INFO 2016-12-28 18:26:12,990 core.version.update_check: Getting newest version hash.
INFO 2016-12-28 18:26:15,710 cherrypy.access.63059664.access: 192.168.1.109 - - [28/Dec/2016:18:26:15] "POST /ajax/update_check HTTP/1.1" 200 154 "http://192.168.1.102:8083/settings/server" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36"
INFO 2016-12-28 18:26:17,272 cherrypy.access.63059664.access: 192.168.1.109 - - [28/Dec/2016:18:26:17] "POST /ajax/update_now HTTP/1.1" 200 7 "http://192.168.1.102:8083/settings/server" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36"
INFO 2016-12-28 18:26:17,303 cherrypy.access.63059664.access: 192.168.1.109 - - [28/Dec/2016:18:26:17] "GET /update/ HTTP/1.1" 200 1069 "http://192.168.1.102:8083/settings/server" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36"
INFO 2016-12-28 18:26:17,678 core.version.execute_update: Updating from Zip file.
INFO 2016-12-28 18:26:17,678 core.version.execute_update: Cleaning up old update files.
INFO 2016-12-28 18:26:17,678 core.version.execute_update: Downloading latest Zip.
INFO 2016-12-28 18:26:19,069 core.version.execute_update: Extracting Zip to temporary directory.
INFO 2016-12-28 18:26:22,615 core.version.execute_update: Backing up user files.
ERROR 2016-12-28 18:26:22,615 core.version.execute_update: Could not back up user files.
Traceback (most recent call last):
  File "C:\watcher\core\version.py", line 376, in execute_update
    if os.path.ispath('logs'):
AttributeError: 'module' object has no attribute 'ispath'
INFO 2016-12-28 18:26:22,615 core.ajax._update_now: Update Failed.
INFO 2016-12-28 18:26:22,615 cherrypy.access.63059664.access: 192.168.1.109 - - [28/Dec/2016:18:26:22] "POST /ajax/update_now HTTP/1.1" 200 6 "http://192.168.1.102:8083/update/" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36"`

**Comment by nosmokingbandit** [comment]
That is a bug from a long time ago. Manually update to the latest version and everything should be ok.

**Comment by rcurcio** [comment]
I'm seeing the same issue after manually updating a few times. I changed `os.path.ispath` to `os.path.isdir` and that seems to bypass that line, but produces a new error:
`watcher-master\core\version.py", line 377, in execute_update
    shutil.copytree('logs', backup_path)
File "C:\Python27\lib\shutil.py", line 177, in copytree
    os.makedirs(dst)
File "C:\Python27\lib\os.py", line 157, in makedirs
    mkdir(name, mode)
WindowsError: [Error 183] Cannot create a file when that file already exists: 'update\\backup'`

Is there documentation on `os.path.ispath`? I can't seem to find anything.

**Comment by nosmokingbandit** [comment]
Commit https://github.com/nosmokingbandit/watcher/commit/38636efa366bf5e36768b1826430012a3d0045c1 should take care of zip updating.

You'll need to manually install this, so do a backup:

`python backup.py -b`

Put the new watcher.zip somewhere safe for a minute.

Grab the latest zip from github and extract it wherever you like.

Move the watcher.zip to the new install `watcher/` directory.

Restore the backup:

`python backup.py -r`
