### ISSUE TITLE
Mark as Complete or Scan Drive option for movie

### ISSUE THREAD

**Issue by serversage** [nosmokingbandit/watcher#56]
If I find a movie, or rip a movie, and copy into the appropriate folder, it would be nice if there was a way in the Watcher UI to either mark the movie as complete, or to have Watcher scan the drive and/or handle the renaming of the movie.

**Comment by duckduckquack** [comment]
i believe the post processing scripts mark them complete. I know it does for the nzbget one.

**Comment by serversage** [comment]
It does, but consider this scenario:

1. I add a movie to Watcher
2. I obtain said movie on DVD
3. I rip the DVD and copy file to my movies directory
4. ???

There is currently no way to inform Watcher that the movie has been obtained by an alternate method.

**Comment by TheRealShiz** [comment]
I have a similar scenario.  I have a Sab script that moves and renames everything based on category.  I don't use the post processing in Watcher at all.  Consequently, everything that is actually complete is still marked as Snatched.

**Comment by blackhawkpr** [comment]
@duckduckquack It didn't mark as complete for me on Sabnzbd.

I added a movie and it couldn't find it for whatever reason, so I manually download it. It gets correctly processed by Watcher's PP script but it didn't get marked as finished.

**Comment by nosmokingbandit** [comment]
@serversage 
I'll add an option to manually mark a movie as 'Finished'

@TheRealShiz 
> I don't use the post processing in Watcher at all

That is probably why they don't get processed. Just a wild guess.

@blackhawkpr 
I'll need logs to figure anything out.

**Comment by nosmokingbandit** [comment]
As of commit 5dec5146be55f773187c8ff6d7c3ddd0deba88d7 you can manually get a movie to Finished. This will disable automatic searching and grabbing, but keeps the movie in your Watcher list.
