### ISSUE TITLE
Feature Request: Add Movies from IMDB Watchlist

### ISSUE THREAD

**Issue by lessthantom** [nosmokingbandit/watcher#58]
would be really cool if it could pull daily from an IMDB watch list. or even if on the add movie page it shows upcoming movies. 

I never remember movies by the time i get home or whatever. 

p.s. it already works brilliantly thanks for your hard work.

**Comment by simonk83** [comment]
Personally I'd really appreciate some sort of Chrome add-in or similar that pops up when on an IMDB page and pushes that movie directly to Watcher.  I use that all the time in CP (but I don't use IMDB watchlists at all).

**Comment by lessthantom** [comment]
I manage my entire setup from my phone so rarely if ever hit an actual webpage IMDb I use the app. Different folks different stroke so I guess, I've been using dogs watchlist for a while and it looks after itself with IMDb watchlist.

**Comment by nosmokingbandit** [comment]
I plan on adding this in the near future.

A chrome addon would be nice too, but I've never made one and I don't want to start leaning new things while I have plenty of work to do here.

The Watcher api is pretty easy to use, so if someone wanted to make an addon I imagine it would be pretty easy.

**Comment by Flippage** [comment]
I actually just requested this on the Web To Plex chrome extension, which currently works with CouchPotato,  and puts a link on IMDB, Trakt.tv and Movieo.

I've asked for Watcher as an alternative downloader to CP for the extension.

**Comment by MartinAyla** [comment]
An extension would be very nice (IMDB watchlist support also) :)

**Comment by nosmokingbandit** [comment]
Added in commit https://github.com/nosmokingbandit/watcher/commit/cae29c593c7cbdaa605337b471a92186f4d3fcde.

Add the feed rss in Settings>Search and restart to enable the task scheduler.
