### ISSUE TITLE
Missing movies from the ListStatus API

### ISSUE THREAD

**Issue by tidusjar** [nosmokingbandit/watcher#59]
Hi,

So I'm working on adding this into Ombi, and I have found a scenario where the API is not returning what I expect.

Reproduction Steps:

1. Add two movies, and one of them it should find some content
1. We should have 1 movie as wanted, the other as Available
1. Mark all the found results on the Available movie as Bad
1. We should now have 2 movies as wanted 
1. Call the `mode=liststatus` API and it will only show the movie that has always been Wanted and will not show the other

Images:

Note: Star wars was the movie where everything was marked as Bad
![image](https://cloud.githubusercontent.com/assets/6642220/21543228/2f0a464a-cdbc-11e6-8caa-3a7862592799.png)

Api Result:

```
[
 {
  "status": "Wanted", 
  "plot": "A linguist is recruited by the military to assist in translating alien communications.", 
  "rated": "PG-13", 
  "title": "Arrival", 
  "finishedscore": null, 
  "predb": "found", 
  "year": "2016", 
  "poster": "images/poster/tt2543164.jpg", 
  "tomatourl": "http://www.rottentomatoes.com/m/story_of_your_life/", 
  "released": "11 Nov 2016", 
  "finisheddate": null, 
  "dvd": "N/A", 
  "tomatorating": "8.4", 
  "imdbid": "tt2543164", 
  "quality": {
   "Quality": {
    "720P": [
     "true", 
     "2", 
     "500", 
     "10000"
    ], 
    "1080P": [
     "true", 
     "1", 
     "2000", 
     "10000"
    ], 
    "4K": [
     "false", 
     "0", 
     "10000", 
     "50000"
    ], 
    "SD": [
     "false", 
     "3", 
     "200", 
     "1000"
    ]
   }, 
   "Filters": {
    "preferredwords": "", 
    "ignoredwords": "subs,german,dutch,french,truefrench,danish,swedish,spanish,italian,korean,dubbed,swesub,korsub,dksubs,vain,HC,blurred", 
    "requiredwords": ""
   }
  }
 }
]
```

Referenced issue: https://github.com/tidusjar/Ombi/issues/844

**Comment by nosmokingbandit** [comment]
This was fixed in https://github.com/nosmokingbandit/watcher/commit/9e8f13764bb0023029ef1f84514b049514efeaf2#diff-fc43f66a28c14343e7c6d33735e1ad3a

Now returns a json dict
```
{"response": "true",
 "movies": [ {blah blah blah}, {blah blah blah}]
}
```

**Comment by tidusjar** [comment]
OK. Out of curiosity, do you plan to make any other changes to the API? 
As I need to change my side of things.

**Comment by nosmokingbandit** [comment]
I just pushed commit https://github.com/nosmokingbandit/watcher/commit/7d15c8825de152d7b2482f8570cc94ca49e5d0b2 where I cleaned up and normalize api responses. 

I don't plan on modifying it any more, but I'm sure I'll add new modes. Anything already implemented that you want to use should be final.
