### ISSUE TITLE
Reverse proxy support?

### ISSUE THREAD

**Issue by Crowley007** [nosmokingbandit/watcher#6]
Hello, does this software have reverse proxy support for remote access like Sonarr, nzbget etc? Can't seem to get this to work, no matter what config I try with Nginx.

**Comment by nosmokingbandit** [comment]
I'm looking into this. I know very little about nginx, so I read a few articles and now I feel like I know less. I'll see what I can find out.

**Comment by Crowley007** [comment]
So the point of this is, you can use front end like this https://github.com/mescon/Muximux, and remote access all your apps through it, and just open one port for it. Nginx (I suppose you can use other webservers as well) then remaps to the local address and port.

Sonarr, Nzbget, CP, Qbittorrent, etc. all support this, so it would be a nice feature to have. I'm no coder so I have no idea what changes it requires to the webui, but in practice you access the app through "localhost:9999/app/" instead of "localhost:9999".

**Comment by Crowley007** [comment]
To add a better example:

I have three apps, APP1, APP2, APP3 and each have a local web server like:

Localhost:1111
Localhost:2222
Localhost:3333

If I want to access them remotely, I would need to open each of those ports. But when I use Nginx reverse proxy, I can connect to everything using a single open port.

For example, 88.177.16.76:5000/APP1 (imaginary public ip)
                      88.177.16.76:5000/APP2
                      88.177.16.76:5000/APP3

I only need to open port 5000 for remote access. Hopefully someone with more experience on this could elaborate.

**Comment by CHBMB** [comment]
On this topic, it would be useful to be able to run the app with support to run it behind a reverse proxy.

ie access it from http://192.168.1.2:9090/watcher

That would make it far easier to place behind a reverse proxy to access it externally on https://server.com/watcher

**Comment by duckduckquack** [comment]
Honestly it's not just NGINX, Apache also works quite well as a reverse proxy, and the app should have support independent of whatever people use. 

Some of these "examples" above aren't quite right, at least IMO. Generally when you run a reverse proxy there are a couple reasons... security & convenience first come to mind. I run Linux, so i want my iptables rules to block everything except 80 & 443 to the LAN(or outside world) I don't want to have to remember that this app uses 9090, couchpotato uses 5050, etc... or have to poke holes in the firewall for each app.

Using a reverse proxy allows me to use go to https://server.domain.com/watcher or https://server.domain.com/movies which is much easier to remember than https://server.domain.com:9090/ especially when you have 10+ apps installed...

Another part is if you run TLS/SSL, you only need one cert. I can get a cert for server.domain.com and use it for all apps on the server. Doing this and keeping the app traffic behind the firewall traversing the localhost IP (IMO) keeps the server more secure.

I can assist in testing both Apache and NGINX if needed. I'm not a dev, so i could be way off, but i think the stuff you need is 'url base' (if i understand this is based off CherryPy)
https://docs.python.org/2/library/urlparse.html
https://cherrypy.readthedocs.io/en/3.3.0/refman/_cprequest.html#cherrypy._cprequest.Request.base
https://cherrypy.readthedocs.io/en/3.3.0/refman/_cprequest.html#cherrypy._cprequest.Request.script_name

I hope this helps.

**Comment by CHBMB** [comment]
@duckduckquack Yeah, that's my understanding too regarding cherrypy.

**Comment by Crowley007** [comment]
Well, those are just my usage cases, others will of course vary. Main usage case is, I only need to open one port from  my router to remote access all software.

**Comment by nosmokingbandit** [comment]
I just pushed an update that should take care of this. I tested it a bit throughout the morning, but one person testing can only figure out so much.

Give it a try, and if you have anything to add to the wiki feel free to edit:
https://github.com/nosmokingbandit/watcher/wiki/Reverse-Proxy-Support

**Comment by duckduckquack** [comment]
Confirmed working in NGINX, only downside is it only works with /watcher at this point, but this is a great start! Thanks for this!!

**Comment by nosmokingbandit** [comment]
Cool beans. It's easy enough to change the subdirectory name, I just wanted to limit the variables for now. I'll add that ability in an update soon. 

I'll mark this closed. Thanks for the feedback.

**Comment by CHBMB** [comment]
Yeah thanks for this! Merry Christmas.

**Comment by Crowley007** [comment]
I don't know why, but for me it still will not work. Must be something about my Nginx config. If you got it to work, perhaps one of you could take a look?

    server {
        listen       PORT;
        server_name  My_public_IP;

        #charset koi8-r;

        access_log off;


        location / {
            root   html;
            index  index.php index.php;
        }
proxy_set_header Host $host;
location /sonarr/ {
                proxy_pass http://192.168.0.2:8989/sonarr/;
        }
location /watcher/ {

    proxy_pass http://127.0.0.1:9090/watcher/;


Sonarr works at "My_public_IP:PORT/sonarr"

Watcher does not.  I have no idea why not, localhost:9090/watcher works fine.

**Comment by duckduckquack** [comment]
So... there are a few things you need to know do. First make sure your watcher service/app is stopped before manually editing the config.cfg file. Make sure you have `behindproxy = true` set. If you have iptables enabled, I would disable it for testing.

But as far as nginx...

server {
    listen 80;
    server_name fqdn.server.name;

location /watcher {
    proxy_pass http://127.0.0.1:9090;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}

Make sure you close all your brackets, the message i saw had the last 2 missing.

**Comment by Crowley007** [comment]
It works fine locally, "localip:port/watcher"

I'm copying your config exactly(except the port number), but it does not work at all remotely, "publicip:port/watcher"

"publicip:port/watcher/status" works, but when I click "Add a movie" it tries to connect to my public ip directly and brings up router login page. 

Other apps are working fine like this, I'm only having problems witch watcher.

**Comment by nosmokingbandit** [comment]
I cannot replicate this. Try a different browser to make sure it isn't
loading old, cached resources.

**Comment by Crowley007** [comment]
I found out the problem, It was the different listen port. Changing this to 80 seems to fix it. Everything else worked fine with the previous port, but I have very little knowledge in these things so I have no idea why.

**Comment by nosmokingbandit** [comment]
That is odd. I know nothing about nginx (I only installed it to help troubleshoot for Watcher users), but I just changed my listen port to a random number, forwarded it in my router, and everything still works great.

I haven't modified anything else in my nginx config, just adding the /watcher entry and the listen port.

**Comment by Crowley007** [comment]
Weird indeed. I probably know even less than you, but since using port 80 fixes this, I consider this solved. :)

**Comment by nosmokingbandit** [comment]
> I probably know even less than you

Impossible.

**Comment by Crowley007** [comment]
Ok, so I'm still playing around with this. 

Watcher for me does not pass the port along, but for example Sonarr does. So while Sonarr uses "publicip:port/sonarr" and works, watcher uses "publicip/watcher" and fails. The reason why port 80 works, it seems to be  default port of some sort and browser redirects automatically. Might be a a less secure option to use that port.

The really strange thing is, why it works for you but not for me. It must be my config. So if one of you can spot what I'm doing wrong, hopefully you can help. Below a simple config to illustrate the problem.

worker_processes  1;
events {
    worker_connections  1024;
}
http {
    include       mime.types;
    default_type  application/octet-stream;
	sendfile        on;
	keepalive_timeout  65;
	server {
		listen 55555;
		server_name publicip, 192.168.0.2, localhost;
		proxy_set_header                        Host                             $host;
		proxy_set_header                        X-Real-IP                      $remote_addr;
		proxy_set_header                        X-Forwarded-For         $proxy_add_x_forwarded_for;

			location /watcher {
			proxy_pass http://192.168.0.2:3535;
			}
			location /sonarr/ {
                proxy_pass http://192.168.0.2:8989/sonarr/;
			}
		}
}

With this, Sonarr works, Watcher does not.

**Comment by duckduckquack** [comment]
@Crowley007 what IP are you using to listen on for watcher? maybe try listening on all `0.0.0.0` instead of `127.0.0.1` ? Just an idea...

**Comment by Crowley007** [comment]
Already using that, does not fix this issue.

**Comment by nosmokingbandit** [comment]
I've been trying to look at this problem for a while but something was broken between my router and my ddns service, so I had to figure that out first. I don't know what was wrong, but it finally connected to the ddns service.

Regardless, mine is working fine. Check the wiki again to make sure you have everything set up correctly, some things may have changed a little throughout updates. I've never used nginx before getting the request for support here, so bear with me while I learn it and implement it in Watcher at the same time.

Set up your config according to the [Wiki](https://github.com/nosmokingbandit/watcher/wiki/Reverse-Proxy-Support).

This is exactly what I have in my nginx conf:
```
    server {
        listen 80;
        server_name ddns.address.com local.ip.address;

        location /watcher {
            proxy_pass http://127.0.0.1:9090;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
```

Change ddns.address.com and local.ip.address to match yours, of course.

**Comment by Crowley007** [comment]
I tried again, and no, still not working. I have 3 other webui's in the same config that all work, so watcher is doing something differently. 

Exactly the same issue as before,

http://ddns.address.com:port/watcher/status/ works

http://ddns.address.com:port/watcher/ does not work and clicking on any of the links in the webui here also do no not work.

For some reason, watcher does not use the port so it tries http://ddns.address.com/watcher/ and fails. In every other Webui the correct port shows in the url bar.  "Listen port 80" gets around this, because it seems to be a default port that browsers use automatically.

Not a huge deal since port 80 works. I have a hunch this is the same issue, but not sure: https://github.com/nosmokingbandit/watcher/issues/53

**Comment by Crowley007** [comment]
This is finally fixed with the latest update!
