### ISSUE TITLE
Wait X days for best release

### ISSUE THREAD

**Issue by TheRealShiz** [nosmokingbandit/watcher#60]
When changing this setting it does not appear to re-evaluate previously found movies according to the new criteria.

**Comment by nosmokingbandit** [comment]
Commit https://github.com/nosmokingbandit/watcher/commit/c3ae2e65896ccc303fab73063960555095f5657f should correct this. Before, when changing search criteria, all results would be purged and re-written, which set their found date to today. Now the only way a result's found date will change is if the provider for that release is removed, which purges all results from that provider.
