### ISSUE TITLE
Can add TV shows - but get error when select it

### ISSUE THREAD

**Issue by estrellagus** [nosmokingbandit/watcher#63]
during testing, did a search for Gotham, and found the first choice returned was the TV series,  clicked on add, and now it shows on the status page as "Wanted".  However, when click on the movie icon on the wanted page get just a black screen and the following error on the console -

29/Dec/2016:13:57:09] HTTP 
Request Headers:
  Content-Length: 16
  COOKIE: session_id=c7934ffc85b53935fa8cc1c6765bd5797d344382
  HOST: 192.168.1.90:9090
  ORIGIN: http://192.168.1.90:9090
  CONNECTION: keep-alive
  Remote-Addr: 192.168.1.90
  ACCEPT: */*
  USER-AGENT: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/602.2.14 (KHTML, like Gecko) Version/10.0.1 Safari/602.2.14
  X-REQUESTED-WITH: XMLHttpRequest
  ACCEPT-LANGUAGE: en-us
  Content-Type: application/x-www-form-urlencoded; charset=UTF-8
  REFERER: http://192.168.1.90:9090/status/
  ACCEPT-ENCODING: gzip, deflate
[29/Dec/2016:13:57:09] HTTP 
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/CherryPy-3.8.0-py2.7.egg/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/Library/Python/2.7/site-packages/CherryPy-3.8.0-py2.7.egg/cherrypy/lib/encoding.py", line 217, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/CherryPy-3.8.0-py2.7.egg/cherrypy/_cpdispatch.py", line 61, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/Users/gusestrella/Applications/watcher/core/ajax.py", line 78, in movie_status_popup
    return msp.html(imdbid)
  File "/Users/gusestrella/Applications/watcher/templates/movie_status_popup.py", line 20, in html
    title_date = data['title'] + " " + str(data['year'])
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2013' in position 4: ordinal not in range(128)
192.168.1.90 - - [29/Dec/2016:13:57:09] "POST /ajax/movie_status_popup HTTP/1.1" 500 1723 "http://192.168.1.90:9090/status/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/602.2.14 (KHTML, like Gecko) Version/10.0.1 Safari/602.2.14"

------

I also found the TV series can also be added though the API call too.

**Comment by soundjester** [comment]
Looks like we need a little database input sanitation.  For this particular "Gotham" example, the year has that goofy em-dash at the end (`2014–`), since the series is continuing.  On the main "status" page, when the query runs to bring back the detailed information for the item, it chokes on that dash character.

```
File "/nzbwatcher/watcher/templates/movie_status_popup.py", line 20, in html
    title_date = data['title'] + " " + str(data['year'])
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2013' in position 4: ordinal not in range(128)
```

Since it is probable that this applicaiton wasn't intended for managing items that are not movies, handling a "year" field that contains non-numeric digits wasn't huge a consideration.  Still, a little input sanitation is probably a good idea.  You don't want to encounter ol' Bobby Drop Tables and lose all your downloaded data.

**Comment by nosmokingbandit** [comment]
Fixed in https://github.com/nosmokingbandit/watcher/commit/f3688de67e68dabf9e48314424b34a40346b0c07

It should not have been returning tv show results.

The database will not accept any destructive results, the status popup error is from python 2's poor unicode handling.
