### ISSUE TITLE
Ubuntu 14.04 Python SSL Fix

### ISSUE THREAD

**Issue by matzi11a** [nosmokingbandit/watcher#68]
Upon updating to latest code e0389d958c3af99f8d153905371bd1aa3cbe28f8 i cant start service on ubuntu 14.04

Traceback (most recent call last):
  File "watcher.py", line 74, in <module>
    ssl._create_default_https_context = ssl._create_unverified_context
AttributeError: 'module' object has no attribute '_create_unverified_context'

I've patched this here: 
https://github.com/matzi11a/watcher/commit/8e5287df013fb22a30addf8e83893e3412c36b64

and i will send a pull request

**Comment by nosmokingbandit** [comment]
Update your python binary. I have no desire to deal with the poor handling of ssl in <2.7.9.

**Comment by matzi11a** [comment]
fair enough, but on ubuntu 14.04 that means doing something horrible. seems a small patch to make it work but heyho.

**Comment by nosmokingbandit** [comment]
I found during early testing that older builds of python don't easily connect to indexers over https, and I'm really just not going to put a lot of time into supporting an outdated python build.

**Comment by matzi11a** [comment]
Sure no worries fwiw it's working fine for me. Thanks anyway great work.
