### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by DariusIII** [nosmokingbandit/watcher#7]
When using python 3, following error is shown;

> SyntaxError: Missing parentheses in call to 'print'

Issue is explained here:

[Stackoverflow](http://stackoverflow.com/questions/25445439/what-does-syntaxerror-missing-parentheses-in-call-to-print-mean-in-python)

**Comment by nosmokingbandit** [comment]
Python 2.X and 3.X are vastly  different. Python 3 support would require a re-write of the entire application. Just use python 2.7.9+.

**Comment by kaboomwarrior** [comment]
Can You reconsider this? Python3 has so much better support for a lot interesting things for kind of functionality to be considered for this kind of software (async, coroutines etc) and is future proof (as new development is in 3.X branch).

As an excersize I ported almost all functionalities within about 1,5 hour (though breaking compatibility with 2.7) . No major problems, almost no serious rewrites actually (mainly urllib/urllib2). If You consider this I can create pull request with my changes. This is big opportunity to switch to python3 on this stage. Once project matures and codebase grows, it would be impossible.
