### ISSUE TITLE
Enhancement: Add start-up argument for a pidfile

### ISSUE THREAD

**Issue by soundjester** [nosmokingbandit/watcher#70]
Add a "pidfile" argument to the user-passed argument section in watcher.py for daemon control and startup scripts used by Ubuntu, Fedora/CentOS, and FreeBSD.

**Comment by nosmokingbandit** [comment]
Added in commit https://github.com/nosmokingbandit/watcher/commit/5d9b1936d8bf017d039b587c9ab454d77c15ea2e

Specify file with watcher.py --pid /path/to/pid.file

**Comment by soundjester** [comment]
Excellent!
