### ISSUE TITLE
Can't get it to start as a service on Ubuntu 16.10

### ISSUE THREAD

**Issue by blackhawkpr** [nosmokingbandit/watcher#71]
Tried using the [Sickrage guide](https://github.com/SickRage/SickRage/wiki/Sickrage-installation-Debian-Ubuntu-14-15-16) the dev suggested, but I can't get it to work.

I'm new to Linux and Ubuntu so I guess I'm missing some of the assumptions that are being made in between the instructions to install Watcher and Sickrage's guide for making it a service.

Things go awry when I run `systemctl start watcher`. What I can gather when I run `journalctl -xe` is that the glaring issue is:

`Dec 30 14:25:25 mediaserver python2.7[20950]: /opt/watcher/lib/fuzzywuzzy/fuzz.py:35: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning`
`Dec 30 14:25:25 mediaserver python2.7[20950]:   warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')`
`Dec 30 14:25:25 mediaserver python2.7[20950]: Config file found, merging any new options.`
`Dec 30 14:25:25 mediaserver python2.7[20950]: Traceback (most recent call last):`
`Dec 30 14:25:25 mediaserver python2.7[20950]:   File "/opt/watcher/watcher.py", line 104, in <module>`
`Dec 30 14:25:25 mediaserver python2.7[20950]:     conf.merge_new_options()`
`Dec 30 14:25:25 mediaserver python2.7[20950]:   File "/opt/watcher/core/config.py", line 90, in merge_new_options`
`Dec 30 14:25:25 mediaserver python2.7[20950]:     with open(self.file, 'w') as cfgfile:`
`Dec 30 14:25:25 mediaserver python2.7[20950]: IOError: [Errno 13] Permission denied: 'config.cfg'`
`Dec 30 14:25:25 mediaserver systemd[1]: watcher.service: Control process exited, code=exited status=1`
`Dec 30 14:25:25 mediaserver systemd[1]: Failed to start Watcher Daemon.`

It should be noted that I get the same error if I plainly try to run Watcher from CLI without sudo like the [readme suggests](https://github.com/nosmokingbandit/watcher/blob/master/README.md), but launches successfully with sudo. I'm sure the fix is very simple, i just don't know what it is. Maybe fixing permissions in `/opt/watcher`, but to what?

**Comment by blackhawkpr** [comment]
Apparently I'm dumb. `/opt/watcher`'s permissions were incorrect. It's working as intended now.

I really should learn more about this Linux thing.

**Comment by nosmokingbandit** [comment]
Linux is a beautiful thing that is terrifying when you are starting to learn. But if you take the time to get comfy with it you'll never be able to live without it.
