### ISSUE TITLE
Misc Enhancement to Status Page

### ISSUE THREAD

**Issue by estrellagus** [nosmokingbandit/watcher#73]
Some ideas while started to add hundred of movies as a test -

1.  Would be great to allow for select only a specific type only .  Most time I might want to select a specific file if found.  So bets to only see status of Found - where I can then pick the right file 

2. Ability to sort on added VS alpha would be good.  Many times just interested on things looking for long time and might choose to find other ways 

3. Ability to hide files snatched after X timeframe ?  (Perhaps option on config page) . Note as can see as time passed will be very hard to navigate and see all oft he snatched files.

**Comment by nosmokingbandit** [comment]
FYI I'll probably start working on this soon. Using strictly javascript to order/sort things would probably be easiest, but JS is the language I am least familiar with. I'm sure I'll figure something out :)

**Comment by nosmokingbandit** [comment]
Additional Status layouts introduced in commit https://github.com/nosmokingbandit/watcher/commit/b33a7103c4a8c8c95e3eaa517ca5a43bc40f524c.

I plan on adding a more compact option soon.

You can also sort results in various ways.
