### ISSUE TITLE
Post Process Problems

### ISSUE THREAD

**Issue by Crowley007** [nosmokingbandit/watcher#74]
I've been testing the watcher PP script again, but I just can't get this to work properly. I sent the download from Nzbhydra.  This is what I get in watcher log:

INFO 2016-12-31 12:20:21,687 core.postprocessing.get_filename: Finding movie file name.
INFO 2016-12-31 12:20:21,691 core.postprocessing.get_filename: Post-processing file Z:\Data\Download\Movies\************************.BrRip.264.YIFY\LHd2kosrjUhSMNEy**************************.mp4.
INFO 2016-12-31 12:20:21,691 core.postprocessing.GET: Parsing release name for information.
INFO 2016-12-31 12:20:21,707 core.postprocessing.GET: Gathering release information.
INFO 2016-12-31 12:20:21,707 core.postprocessing.get_movie_info: Searching local database for guid.
INFO 2016-12-31 12:20:21,707 core.sqldb.get_single_search_result: Retreving search result details for http://192.168.0.2:5075/nzbhydra/getnzb?apikey*****************************searchresultid=*********&downloader=NZBGet.
INFO 2016-12-31 12:20:21,713 core.postprocessing.get_movie_info: Searching local database for downloadid.
INFO 2016-12-31 12:20:21,713 core.sqldb.get_single_search_result: Retreving search result details for 132.
INFO 2016-12-31 12:20:21,717 core.postprocessing.get_movie_info: Unable to find local data for release. Searching OMDB.
INFO 2016-12-31 12:20:21,717 core.postprocessing.get_movie_info: Searching omdb for LHd2kosrjU**************************** 
INFO 2016-12-31 12:20:23,568 core.postprocessing.get_movie_info: Nothing found in OMDB.
ERROR 2016-12-31 12:20:23,569 cherrypy.error.69840568.error: [31/Dec/2016:12:20:23] HTTP 
Traceback (most recent call last):

It seems to me, that the problem is the weird filename (LHd2kosrjUhSMNEy**************************.mp4), and watcher can't find the proper information for it. The folder name is sane, so perhaps watcher should try to use that if the filename check fails? Other pp scripts like videosort do find the correct information for these and renames correctly.

**Comment by nosmokingbandit** [comment]
I need the full log for this. NZBHydra makes everything more complicated than it needs to be.

http://192.168.0.2:5075/nzbhydra/getnzb?apikey*****************************searchresultid=*********&downloader=NZBGet should be saved in the searchresults table in the database. If NZBHydra is sending a different link to NBZGet than it sends to Watcher it makes this all 1000x more difficult.

**Comment by Crowley007** [comment]
I don't really understand what you are saying here. I added the download directly from NZBhydra, watcher only became involved to post process the download. But, I'll test again and edit this post with the full watcher log.

**Comment by nosmokingbandit** [comment]
Oh..... ok then.

Yeah, that makes sense.

I'll get it to parse the parent folder as well.

**Comment by Crowley007** [comment]
Another problem I encountered, you can't use watcher PP script as global PP script in NZBget if you use Sonarr. I had it set so, and watched moved an episode of a TV series incorrectly. This problem is of course solved by using the script for only "Movies" category.

Checking watcher log, it actually found the correct information on for the series on OMDB, but since this is for movies only shouldn't renamer/mover skip TV series?

**Comment by nosmokingbandit** [comment]
It will attempt to process everything you tell it to. If you don't want it processed by Watcher just don't ask it to.

**Comment by nosmokingbandit** [comment]
Commit https://github.com/nosmokingbandit/watcher/commit/8451bbf2eace748db71f05e17bf5cd20df605475 looks for the parent folder if the filename doesn't give enough information.
