### ISSUE TITLE
Option to handle 'the'?

### ISSUE THREAD

**Issue by jtscott** [nosmokingbandit/watcher#75]
Watcher is awesome, seriously great work!

I was wondering if there is a way to handle release titles starting with 'The'? Currently it names "Magnificent Seven, The", and I was looking to specify "The Magnificent Seven".

Thanks!

**Comment by nosmokingbandit** [comment]
At what point does this happen?

**Comment by jtscott** [comment]
Sorry I should have clarified, this happens during post processing. Creating the folder and renaming the file resulted in this formatting.

**Comment by nosmokingbandit** [comment]
I just ran a test with a magnificent seven release and it didn't move the 'The', it came out 'The Magnificent Seven'

Can you get me the logs from that post-processing?
