### ISSUE TITLE
Accessing Watcher from another computer on the local network?

### ISSUE THREAD

**Issue by Jimmni** [nosmokingbandit/watcher#76]
I've had no trouble accessing NZBGet, Sonarr, CP etc. from another computer on the network, but I have had no luck in getting Watcher to work this way. I'm running on Windows 7, trying to access from various different Mac and Windows machines. Turning off the firewall does not help. I also tried passing the specific port through the Firewall before turning it off.

Any idea what I might be doing wrong? Thanks for any help anyone can provide!

**Comment by LastStarFighter** [comment]
Try setting the Host IP in server settings to 0.0.0.0 and see if that fixes your issue?

**Comment by Jimmni** [comment]
No change. I tried 0.0.0.0, 127.0.0.1, localhost, 192.168.0.10 (computer's IP), none were successful. I'm no Windows expert so could very well have done something stupid, but had no issues with any of the other applications. Tested again both with Firewall on and off.

**Comment by LastStarFighter** [comment]
There must be something with either the router or windows settings that's causing the issue. Try using a different port # and see if that does anything?

**Comment by Jimmni** [comment]
It appears that either I was misunderstanding something or there's a bug. I was changing the Host in server settings, and assuming it was changing the host. However, it appears that neither the Host or Port setting actually get changed when I change them in the Settings page and hit Save. However, I just launched it with "python watcher.py --host 192.168.0.10" and now it works. I assume 0.0.0.0 there would work too. The settings in Server settings seem to actually have no connection to the actual settings used?

**Comment by Jimmni** [comment]
(Restarting after hitting save didn't commit the changes either.)

**Comment by LastStarFighter** [comment]
Yeah i just did a test and seems like there might be an issue with committed changes being saved.  So you will just have to edit the config.cfg manually until it can be addressed.

**Comment by Jimmni** [comment]
Not a problem at all! Glad I wasn't going insane :D Thanks a ton for your help sorting this out!

**Comment by nosmokingbandit** [comment]
I am unable to replicate this.

I changed my host to a different port, clicked Save, and the config file was changed to reflect this. Upon restarting the server it was hosted on the new address.
