### ISSUE TITLE
When Mover fails I'd like the option to force cleanup to fail.

### ISSUE THREAD

**Issue by TheRealShiz** [nosmokingbandit/watcher#78]
When mover fails, cleanup then deletes what it was trying to move.  I'd at least like the option to force cleanup to fail if moving fails.

**Comment by nosmokingbandit** [comment]
The cleanup method checks for mover failure before doing anything. If you can, send me your Watcher log for a movie that did this incorrectly. I need to find out why the mover is returning success when it shouldn't be.

**Comment by TheRealShiz** [comment]
[log.txt](https://github.com/nosmokingbandit/watcher/files/681603/log.txt)

It was happening to Sin City: A Dame to Kill For.  The mover was failing on creating the folder because of the illegal character in the name.

**Comment by nosmokingbandit** [comment]
Commit https://github.com/nosmokingbandit/watcher/commit/60ead27229526181452991b35f50bbaeaf549ae6 should fix this.

Cleanup wouldn't run if the mover was disabled, but I forgot to check the mover response as well before continuing.
