### ISSUE TITLE
Status page optimization for users with many items

### ISSUE THREAD

**Issue by 4getit** [nosmokingbandit/watcher#79]
Please optimize the status page for many items. 
I have an IMDb watchlist with thousands of items but I know from CP already that this is barely workable. With a large list of thumbnails, things become very slow and difficult to navigate.
Instead of thumbnails only, an option to switch to 'List mode' would be great. 

And also, at this moment a thumbnail needs to be clicked before any action can be taken. It would be great to have some action/shortcut links on the status page itself as well.

**Comment by WilliamJBrown** [comment]
I too like the idea of having a list instead of thumbnails. :) 👍

**Comment by nosmokingbandit** [comment]
> And also, at this moment a thumbnail needs to be clicked before any action can be taken. It would be great to have some action/shortcut links on the status page itself as well.

The only action that can be done in one step is removing the movie. I'd rather not have this trigger easier to accidentally click.
