### ISSUE TITLE
Use NZBGet/SAB API instead of PP-script

### ISSUE THREAD

**Issue by Safihre** [nosmokingbandit/watcher#8]
Looking forward to see where this project goes 👍 

In mean time some comments:

- Why use a post-processing script? Why not periodically call SAB/NZBGet API and use that information to see if a movie is finished like Sonarr/CP do? It will increase the ease of use for end-user. SAB for example will return the NZO_ID after you send it a job, this you can then use to track the download through the Queue and History.
- SAB's default HTTPS's port is also 9090, maybe pick another one as default just to be on safe side?
- Binding to 0.0.0.0 will expose it to all PC's within the networks, maybe bind to localhost only so it's limited to only the current PC?

**Comment by Crowley007** [comment]
This is a good idea. The PP script for Nzbget keeps failing no matter what I do, I tested it with many files. But rather than opening new issue about it, I think this is a better way to do this.

**Comment by nosmokingbandit** [comment]
Check your nzbget and watcher log for any abnormalities or just send them to me.

I like the post-processing script for a few reasons. One, it lets Watcher process movies that weren't snatched from Watcher. Second, I don't like making any more http requests than possible. A lot of people run their media servers on raspberry pis and other low-power hardware. Every processor cycle matters. The pp script takes about 30 seconds to set up, I'm not worried about inconveniencing anyone.

It should, by default, bind to 127.0.0.1, which makes it accessible only on the local machine. Binding to 'localhost' by default can cause weird problems for people using ipv6.

**Comment by WilliamJBrown** [comment]
I will chime in on the NZBGet processing script. You need to check the logs to see what volume is being listed as the directory for where the completed download is located. 

You need to then mount that directory in the same fashion as how the downloaded sends the directory to Watcher. NZBGet will say movie completed, loacted /volume/some/place/here. Watcher will need to have the directory mounted the same way or have access to what is reported by NZBGet. 

I feel like I am explaining my self but it is mostly permission issues or incorrect pathing.

**Comment by Crowley007** [comment]
Well I can understand the CPU concerns, I'm running this on a low power CPU myself. Hopefully I can get it to work.

Since we are discussing it here, I'll list the problems I'm having:

At first it errored out constantly, but I think that had something to do with my network settings, I got it to run but inconsistently. Once, it put the wrong year in the end of a movie (same name), the right year was present in the original file name.  Twice now it only moved an *.nfo file but not the video file. 

Will test more later when I have the time.

**Comment by Safihre** [comment]
@WilliamJBrown check the contents of the post-processing script.. All it does is call the SAB API and then call the Watcher API, so no processing happens at all.

@nosmokingbandit Indeed, I was wrong about the `0.0.0.0`, sorry!
But regarding the API: the costs of responding to an API request for history once every 2 or 3 minutes is so much lower than even decoding a simple yEnc article of which each article has thousands. I know, because I have been spending hours on optimizing SAB's API resource usage.
Regarding the non-Watcher movies: I think you should default to using the `movies` category, because NZBGet and SAB will auto-categorize NZB's downloaded from Newznab Indexers (which is 95% of them) that have a category tag that starts with `Movies` (which is true for all movies on Newznab Indexers). 
So this way when you request only the history API for the `movies` category, you can catch _all_ movies.

Just a suggestion 😉

**Comment by Crowley007** [comment]
Ok, these are the errors I get with the PP script often:

`Sat Dec 24 21:12:18 2016	INFO	Executing post-process-script nzbget.py for Superman.1978.720.BrRip.264.YIFY
Sat Dec 24 21:12:19 2016	INFO	nzbget: Sending ****************** to Watcher as Complete.
Sat Dec 24 21:12:19 2016	INFO	nzbget: Traceback (most recent call last):
Sat Dec 24 21:12:19 2016	INFO	nzbget:   File "C:\ProgramData\NZBGet\scripts\nzbget.py", line 69, in <module>
Sat Dec 24 21:12:19 2016	INFO	nzbget:     response = json.loads(urllib2.urlopen(request).read())
Sat Dec 24 21:12:19 2016	INFO	nzbget:   File "C:\Python27\lib\urllib2.py", line 154, in urlopen
Sat Dec 24 21:12:19 2016	INFO	nzbget:     return opener.open(url, data, timeout)
Sat Dec 24 21:12:19 2016	INFO	nzbget:   File "C:\Python27\lib\urllib2.py", line 437, in open
Sat Dec 24 21:12:19 2016	INFO	nzbget:     response = meth(req, response)
Sat Dec 24 21:12:19 2016	INFO	nzbget:   File "C:\Python27\lib\urllib2.py", line 550, in http_response
Sat Dec 24 21:12:19 2016	INFO	nzbget:     'http', request, response, code, msg, hdrs)
Sat Dec 24 21:12:19 2016	INFO	nzbget:   File "C:\Python27\lib\urllib2.py", line 475, in error
Sat Dec 24 21:12:19 2016	INFO	nzbget:     return self._call_chain(*args)
Sat Dec 24 21:12:19 2016	INFO	nzbget:   File "C:\Python27\lib\urllib2.py", line 409, in _call_chain
Sat Dec 24 21:12:19 2016	INFO	nzbget:     result = func(*args)
Sat Dec 24 21:12:19 2016	INFO	nzbget:   File "C:\Python27\lib\urllib2.py", line 558, in http_error_default
Sat Dec 24 21:12:19 2016	INFO	nzbget:     raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
Sat Dec 24 21:12:19 2016	INFO	nzbget: urllib2.HTTPError: HTTP Error 500: Internal Server Error
Sat Dec 24 21:12:19 2016	ERROR	Post-process-script nzbget.py for **************************** failed (terminated with unknown status)`

In this case, the downloaded file had a weird name extracted, probably obfuscated. The post processing seems to be pretty picky, and when it doesn't like something it throws those errors. And wiht some files, it only moves nfo file, perhaps the movie file in those cases is in a format it does not like.
