### ISSUE TITLE
Please add basic authentication

### ISSUE THREAD

**Issue by 4getit** [nosmokingbandit/watcher#80]
Please add basic authentication to the Server settings.

**Comment by LastStarFighter** [comment]
In the server settings there should be an option to password protect the web-ui.

**Comment by 4getit** [comment]
Hmm... I'm confused now.
I noticed /core/auth.py but I really don't see it.

I see:

- Host  
- Port  
- API Key  
- Open browser on launch.
- Check for updates every  
- Automatically install updates at  
- Check for updates now.
- Keep x days of logs.
- Restart  Shutdown 
- Save Settings

Current version hash: 7d15c88

**Comment by LastStarFighter** [comment]
Are you up to date with the latest commits?

**Comment by 4getit** [comment]
Ah, it works now.
What happened was that it updated things successfully but it was never restarted. The shutdown function also didn't seem to work.
I killed it manually and now it works. The shutdown now works as well.
Thanks!
