### ISSUE TITLE
Docker Database Mountable Volume

### ISSUE THREAD

**Issue by WilliamJBrown** [nosmokingbandit/watcher#83]
Hey there, 

Just wondering if we can get a defining variable for the database. That way we can get access/custom folder mapping for the docker container in regards to updates. I hope this wont be a big issue for you. I'll keep an eye on this :) similar to what we did with the config and logs. If we can just get the same thing for the database it will be perfect :)

Have a great new year! 

btw the docker container has 2,000 downloads :) Well done!

**Comment by nosmokingbandit** [comment]
Done in commit https://github.com/nosmokingbandit/watcher/commit/1d776f244bb5586a1065acb16c492b3ba4575513

Usage:
`watcher.py --db /path/to/database.sqlite`

You should use the absolute file path, and point toward a file, not a folder.
