### ISSUE TITLE
how to reset user/pass ?

### ISSUE THREAD

**Issue by pducharme** [nosmokingbandit/watcher#85]
It seems i can't recall the user/pass to connect.  I'm displayed the Login page.  I tried finding it in the Config.cfg, but what I found there doesn't work.   Any help appreciated.

**Comment by rickytin** [comment]
I have the same problem.

**Comment by kaibosh** [comment]
After editing the credentials in config.php, be sure to restart the watcher process.

**Comment by nrlatsha** [comment]
I think it's a bug.  I didn't have the option, "Password-protect web-ui" checked, but watcher still asked me for a password anyway.

The answer is in config.cfg.  Authuser & authpass.

**Comment by nosmokingbandit** [comment]
This was fixed this morning with commit
https://github.com/nosmokingbandit/watcher/commit/48dd9399dc53ba63e661c1db6212f20a6e145f0d

When I switched the auth method I neglected to check this. Its complicated
how it works, but it is all good on the latest commit.

Default user/pass is watcher/rehctaw
