### ISSUE TITLE
Error when Saving Settings on Provider Page

### ISSUE THREAD

**Issue by chadbaum** [nosmokingbandit/watcher#9]
After attempting to add 3 NZB sites and clicking save settings, this error appears:

`INFO 2016-12-24 13:49:56,500 cherrypy.access.139781931790864.access: 192.168.1.190 - - [24/Dec/2016:13:49:56] "POST /save_set$
INFO 2016-12-24 13:49:59,917 core.ajax.save_settings: Saving settings.
ERROR 2016-12-24 13:49:59,919 core.ajax.save_settings: Writing config.
Traceback (most recent call last):
  File "/opt/watcher/app/core/ajax.py", line 182, in save_settings
    self.config.write_dict(data)
  File "/opt/watcher/app/core/config.py", line 71, in write_dict
    self.stash()
  File "/opt/watcher/app/core/config.py", line 98, in stash
    d['Indexers'][k] = v.split(',')
AttributeError: 'dict' object has no attribute 'split'
INFO 2016-12-24 13:49:59,919 cherrypy.access.139781931790864.access: 192.168.1.190 - - [24/Dec/2016:13:49:59] "POST /save_set$`

**Comment by chadbaum** [comment]
Ignore, I was 69 commits behind.  This is fixed. :p

**Comment by chadbaum** [comment]
Spoke too soon.  As soon as I try to enable any of the providers I get the same error.  Tried with a fresh docker container and config and same error.

**Comment by nosmokingbandit** [comment]
If you were using an old docker build you might have cached javascript sending wrong information to the server (the ajax method for saving settings changed a few times).

Open a different browser and try again. See if it works when we know there are no cached files.

**Comment by nosmokingbandit** [comment]
Closed due to lack of response.

**Comment by jaketame** [comment]
I believe I'm experiencing this issue, unable to add provider, tickbox is selected. I click Save Settings however doesn't do anything. Running Safari, no logs in console.

Log at same time to test connection, which seems to suggest nothing has been entered but it has.

ERROR 2017-01-21 20:59:13,379 core.newznab.test_connection: NewzNab connection check.
Traceback (most recent call last):
  File "/opt/watcher/core/newznab.py", line 163, in test_connection
    response = ET.fromstring(xml).attrib
  File "<string>", line 125, in XML
ParseError: no element found: line 1, column 0

**Comment by nosmokingbandit** [comment]
This was fixed in https://github.com/nosmokingbandit/watcher/commit/42363d7fb1639069ec3a8fcfa0be6fd3efb71923.
