### ISSUE TITLE
Downloader Settings Dissapearing Bug

### ISSUE THREAD

**Issue by JoeStratton** [nosmokingbandit/watcher#93]
When you save your NZBGet downloader settings and then go back to the page and click the filled in "circle", it hides all the settings until you refresh the page.
![downloader_ui_error](https://cloud.githubusercontent.com/assets/6180439/21615934/cf77178c-d19c-11e6-89dc-b945c182da6c.PNG)

**Comment by nosmokingbandit** [comment]
Corrected in https://github.com/nosmokingbandit/watcher/commit/06a0745bf21735ac8aa388bfe9437620d3495ce7.
