### ISSUE TITLE
Synology

### ISSUE THREAD

**Issue by ash212** [nosmokingbandit/watcher#94]
Hi,

Is there any chance you can show me how to install it in synology? i have done all the steps in creating a registry and can see it in the docker as a container.  However when i start it, it shuts down a second later without any error messages.

**Comment by WilliamJBrown** [comment]
Are you using synology docker Web hi? Or cli?

**Comment by JoeStratton** [comment]
I had a permissions issue when using the container, check the logs and verify it has appropriate access to the paths you passed. I fixed it by brute force, running chmod 777 -R on the directory (not recommended)

**Comment by Elfman72** [comment]
I had this working fine on Synology through the web UI, however with the recent change of adding the /database var, I can no longer get this package to work.  I created a blank txt file and renamed it to database.sqlite and added the var in the container.  However, it just quits with the following watcher log message:

```
INFO 2017-01-05 18:14:58,143 __main__.<module>: SQL DB not found. Creating.
INFO 2017-01-05 18:14:58,151 core.sqldb.create_database: Creating tables.
```

If I monitor the Docker Container log, I see the following traceback.

```
/opt/watcher/app/lib/fuzzywuzzy/fuzz.py:35: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')
Config file found, merging any new options.
Traceback (most recent call last):
  File &quot;/opt/watcher/app/watcher.py&quot;, line 133, in &lt;module&gt;
    sql.create_database()
  File &quot;/opt/watcher/app/core/sqldb.py&quot;, line 70, in create_database
    self.metadata.create_all(self.engine)
  File &quot;/opt/watcher/app/lib/sqlalchemy/sql/schema.py&quot;, line 3848, in create_all
    tables=tables)
  File &quot;/opt/watcher/app/lib/sqlalchemy/engine/base.py&quot;, line 1922, in _run_visitor
    with self._optional_conn_ctx_manager(connection) as conn:
  File &quot;/usr/lib64/python2.7/contextlib.py&quot;, line 17, in __enter__
    return self.gen.next()
  File &quot;/opt/watcher/app/lib/sqlalchemy/engine/base.py&quot;, line 1915, in _optional_conn_ctx_manager
    with self.contextual_connect() as conn:
  File &quot;/opt/watcher/app/lib/sqlalchemy/engine/base.py&quot;, line 2106, in contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File &quot;/opt/watcher/app/lib/sqlalchemy/engine/base.py&quot;, line 2145, in _wrap_pool_connect
    e, dialect, self)
  File &quot;/opt/watcher/app/lib/sqlalchemy/engine/base.py&quot;, line 1456, in _handle_dbapi_exception_noconnection
    exc_info
  File &quot;/opt/watcher/app/lib/sqlalchemy/util/compat.py&quot;, line 202, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File &quot;/opt/watcher/app/lib/sqlalchemy/engine/base.py&quot;, line 2141, in _wrap_pool_connect
    return fn()
  File &quot;/opt/watcher/app/lib/sqlalchemy/pool.py&quot;, line 387, in connect
    return _ConnectionFairy._checkout(self)
  File &quot;/opt/watcher/app/lib/sqlalchemy/pool.py&quot;, line 766, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File &quot;/opt/watcher/app/lib/sqlalchemy/pool.py&quot;, line 516, in checkout
    rec = pool._do_get()
  File &quot;/opt/watcher/app/lib/sqlalchemy/pool.py&quot;, line 1229, in _do_get
    return self._create_connection()
  File &quot;/opt/watcher/app/lib/sqlalchemy/pool.py&quot;, line 333, in _create_connection
    return _ConnectionRecord(self)
  File &quot;/opt/watcher/app/lib/sqlalchemy/pool.py&quot;, line 461, in __init__
    self.__connect(first_connect_check=True)
  File &quot;/opt/watcher/app/lib/sqlalchemy/pool.py&quot;, line 651, in __connect
    connection = pool._invoke_creator(self)
  File &quot;/opt/watcher/app/lib/sqlalchemy/engine/strategies.py&quot;, line 105, in connect
    return dialect.connect(*cargs, **cparams)
  File &quot;/opt/watcher/app/lib/sqlalchemy/engine/default.py&quot;, line 385, in connect
    return self.dbapi.connect(*cargs, **cparams)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file

```

Not sure the best way to get my db over to the new file.  I have no problem starting with a blank db either.  Just need some advice on getting this going again.  Love this software and really appreciate the Docker for it.

Much appreciated!

**Comment by WilliamJBrown** [comment]
Prob best to start fresh. All you need to do is mount the folder where you want the database to be stored. So you just mount /path/to/database/ then you just mount that as /database on the right hand portion similar to the logs and config folder directories. I didn't not have to create a file myself. I just mounted the directory and watcher did everything for me. If you need more help i can screen shot my current set up for you. I maintaine the docker container my self fyi

**Comment by Elfman72** [comment]
So strange.  I thought I tried that but I think I was trying to link it to a file instead of folder.  I guess you only want to do that when you already have a formatted sqlite db.  I started new and was able to use my old config without issue.  Re-added my movies and am back up and running.  It will be handy to have the DB exposed too so I can get that backed up along with my config.

Thanks for your help!

**Comment by WilliamJBrown** [comment]
All good don't forget to close this issue so our awesome Dev doesn't have to worry about this :)

**Comment by Elfman72** [comment]
Well, I kind of thread-jacked the thread that @ash212 started.  I believe we could take this one off-line.

That said, @ash212 are you running this in Docker?

**Comment by ash212** [comment]
Yes i am but like i said i am a complete newbie to synology and docker.

What i did was put in the repository link in docker as a source and found the watcher.

I added it and all is good with default settings.. my issue was when i tried to connect it registers ram and hdd usage for a second then disconnects immediately..

Ran cp the same way and it was working fine.

Sorry if i took a while to answer but i have had some rl issues i had to deal with.

Any chance anyone has a step by step guide i can follow?

Thanks for all the help.

Get Outlook for Android<https://aka.ms/ghei36>



On Fri, Jan 6, 2017 at 4:59 AM +0300, "Elfman72" <notifications@github.com<mailto:notifications@github.com>> wrote:


Well, I kind of thread-jacked the thread that @ash212<https://github.com/ash212> started. I believe we could take this one off-line.

That said, @ash212<https://github.com/ash212> are you running this in Docker?

**Comment by nosmokingbandit** [comment]
I'm going to close this. Feel free to keep chatting about it here, but I want to clear this out of Open Issues since I won't be involved in any tertiary installations like this.

If you need any specific input from me just tag me with @nosmokingbandit
