### ISSUE TITLE
NZBGet endless fetching with NZBHydra

### ISSUE THREAD

**Issue by JoeStratton** [nosmokingbandit/watcher#95]
When Watcher passes the URL format to NZBGet from NZBHydra it sits on "fetching" for about 5 minutes before timing out. 

URL format received: http://192.168.1.X:5075/nzbhydra/getnzb?apikey=XXXXXXXXXXXXXXXXXX&searchresultid=c3a0e0fff225df2e30bea05806abf13a46df1db0

Error received (from nzbget): Connection to 192.168.1.X failed: ErrNo 110, Connection timed out

I know this is not NZBGet or NZBHydra's fault because they are both working fine for Sonarr and the original Couchpotato. It is only when Watcher uses NZBHydra that the failure occurs.

There are no proxy's involved.

Attached are the logs with my API key removed.
[log.zip](https://github.com/nosmokingbandit/watcher/files/683523/log.zip)

**Comment by nosmokingbandit** [comment]
Hmmmmmm.

I just sent a movie from NZBHydra > Watcher > NZBGet and it started downloading just fine. I'll take a look at your logs, things like this are usually something easy that looks complicated.

**Comment by JoeStratton** [comment]
Yes I am using the docker container created by Linuxserver.io

I am thinking it is this: NZBHydra > Watcher > NZBGet because if it was NZBH-> NZBGet I dont think the issue would occur, but thats an educated guess.

**Comment by JoeStratton** [comment]
Just an update that the latest commit did not fix the issue.

**Comment by nosmokingbandit** [comment]
Talk to the container creator/maintainer. The way docker containers communicate with each other makes things rather complicated. Watcher works fine when running the script directly.

**Comment by JoeStratton** [comment]
Thanks, submitted to the linuxserver.io team.
