### ISSUE TITLE
Changing search settings doesn't change already added movies

### ISSUE THREAD

**Issue by Flippage** [nosmokingbandit/watcher#96]
Just something I noticed when I was trying to test today. I had already added a bunch of movies, and wasn't finding anything. So I changed the overall search settings.

At the moment, this does not affect already added movies, but only movies yet to be added.

Any chance you could add an option when saving those settings, to apply the same settings (required words, preferred words, max and min size, etc.) to ALL movies, future and ones already in the watch list?

That'd be the best way to handle it I think.

E.g.
**"Save"**
**"Save & Apply To All"**

**Comment by nosmokingbandit** [comment]
That one was closed because the issuer presented it as a bug, which it is not.

This is on my to-do list, but bugs must come first.

**Comment by soundjester** [comment]
A man's got to have a code *:Omar voice*

**Comment by nosmokingbandit** [comment]
Added in commit https://github.com/nosmokingbandit/watcher/commit/b33a7103c4a8c8c95e3eaa517ca5a43bc40f524c.

When changing anything in Settings > Quality you will be asked to apply it to all movies.
